import { EmployeeData } from "../types";

/**
 * Civil Servant sample dataset — sourced from ZESt (RCSC).
 * Includes agency code, department, and subdivision so the Employee Master
 * table can filter dynamically based on the signed-in user's agency context.
 *
 * Agencies covered (sample):
 *   70 · GovTech (Government Technology Agency) — 2 departments, each with subdivisions
 *   10 · Ministry of Finance
 *   21 · Ministry of Health
 *   22 · Ministry of Education & HR Development
 *   31 · Department of Road Safety & Transport
 */
export const CS_SAMPLE_EMPLOYEES: EmployeeData[] = [
  /* ── GovTech · Code 70 · Department of Digital Transformation ── */
  { employeeId: 20001, firstName: "Tenzin", lastName: "Dorji", gender: "Male", cid: "10701010001", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "ICT Officer", designation: "Officer", positionLevel: "P3", workingAgency: "Government Technology Agency", agencyCode: "70", department: "Department of Digital Transformation", subdivision: "Digital Service Transformation Division", yearsOfService: 7, employeeStatus: "Active" },
  { employeeId: 20002, firstName: "Pema", lastName: "Yangzom", gender: "Female", cid: "10701010002", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Systems Analyst", designation: "Analyst", positionLevel: "P4", workingAgency: "Government Technology Agency", agencyCode: "70", department: "Department of Digital Transformation", subdivision: "Digital Service O&M Division", yearsOfService: 8, employeeStatus: "Active" },
  { employeeId: 20003, firstName: "Sonam", lastName: "Tshering", gender: "Male", cid: "10701010003", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Emerging Tech Specialist", designation: "Specialist", positionLevel: "P2", workingAgency: "Government Technology Agency", agencyCode: "70", department: "Department of Digital Transformation", subdivision: "Emerging Technologies Division", yearsOfService: 9, employeeStatus: "Active" },
  { employeeId: 20004, firstName: "Dechen", lastName: "Wangmo", gender: "Female", cid: "10701010004", employeeCategory: "civil-servant", employeeType: "Contract", positionTitle: "Data Engineer", designation: "Engineer", positionLevel: "P4", workingAgency: "Government Technology Agency", agencyCode: "70", department: "Department of Digital Transformation", subdivision: "Digital Service Development Division", yearsOfService: 10, employeeStatus: "Active" },
  { employeeId: 20005, firstName: "Karma", lastName: "Norbu", gender: "Male", cid: "10701010005", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Industry Liaison", designation: "Officer", positionLevel: "P5", workingAgency: "Government Technology Agency", agencyCode: "70", department: "Department of Digital Transformation", subdivision: "Tech Industry Development Division", yearsOfService: 11, employeeStatus: "Active" },
  { employeeId: 20006, firstName: "Jigme", lastName: "Wangchuk", gender: "Male", cid: "10701010006", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "DevOps Engineer", designation: "Engineer", positionLevel: "P3", workingAgency: "Government Technology Agency", agencyCode: "70", department: "Department of Digital Transformation", subdivision: "Digital Service O&M Division", yearsOfService: 12, employeeStatus: "Active" },
  { employeeId: 20007, firstName: "Tashi", lastName: "Lhamo", gender: "Female", cid: "10701010007", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Database Administrator", designation: "Administrator", positionLevel: "P4", workingAgency: "Government Technology Agency", agencyCode: "70", department: "Department of Digital Transformation", subdivision: "Digital Service Development Division", yearsOfService: 13, employeeStatus: "Study Leave" },
  { employeeId: 20008, firstName: "Ugyen", lastName: "Zangmo", gender: "Female", cid: "10701010008", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Service Design Lead", designation: "Lead", positionLevel: "O2", workingAgency: "Government Technology Agency", agencyCode: "70", department: "Department of Digital Transformation", subdivision: "Digital Service Transformation Division", yearsOfService: 14, employeeStatus: "Active" },

  /* ── GovTech · Code 70 · Department of Digital Infrastructure ── */
  { employeeId: 20009, firstName: "Phuntsho", lastName: "Gyeltshen", gender: "Male", cid: "10702020001", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Network Manager", designation: "Manager", positionLevel: "P2", workingAgency: "Government Technology Agency", agencyCode: "70", department: "Department of Digital Infrastructure", subdivision: "Government Network Division", yearsOfService: 15, employeeStatus: "Active" },
  { employeeId: 20010, firstName: "Kinley", lastName: "Dem", gender: "Female", cid: "10702020002", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Cloud Engineer", designation: "Engineer", positionLevel: "P4", workingAgency: "Government Technology Agency", agencyCode: "70", department: "Department of Digital Infrastructure", subdivision: "Cloud Service Division", yearsOfService: 1, employeeStatus: "Active" },
  { employeeId: 20011, firstName: "Namgay", lastName: "Tshomo", gender: "Female", cid: "10702020003", employeeCategory: "civil-servant", employeeType: "Contract", positionTitle: "WoG Integration Analyst", designation: "Analyst", positionLevel: "P5", workingAgency: "Government Technology Agency", agencyCode: "70", department: "Department of Digital Infrastructure", subdivision: "Whole of Government Division", yearsOfService: 2, employeeStatus: "Active" },
  { employeeId: 20012, firstName: "Yeshey", lastName: "Dorji", gender: "Male", cid: "10702020004", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Cloud Architect", designation: "Architect", positionLevel: "P3", workingAgency: "Government Technology Agency", agencyCode: "70", department: "Department of Digital Infrastructure", subdivision: "Cloud Service Division", yearsOfService: 3, employeeStatus: "Active" },
  { employeeId: 20013, firstName: "Choki", lastName: "Wangmo", gender: "Female", cid: "10702020005", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Network Coordinator", designation: "Coordinator", positionLevel: "O1", workingAgency: "Government Technology Agency", agencyCode: "70", department: "Department of Digital Infrastructure", subdivision: "Government Network Division", yearsOfService: 4, employeeStatus: "Active" },
  { employeeId: 20014, firstName: "Dorji", lastName: "Penjor", gender: "Male", cid: "10702020006", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Infrastructure Engineer", designation: "Engineer", positionLevel: "P4", workingAgency: "Government Technology Agency", agencyCode: "70", department: "Department of Digital Infrastructure", subdivision: "Government Network Division", yearsOfService: 5, employeeStatus: "Separated" },
  { employeeId: 20015, firstName: "Lhaden", lastName: "Choden", gender: "Female", cid: "10702020007", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "WoG Service Engineer", designation: "Engineer", positionLevel: "P5", workingAgency: "Government Technology Agency", agencyCode: "70", department: "Department of Digital Infrastructure", subdivision: "Whole of Government Division", yearsOfService: 6, employeeStatus: "Active" },

  /* ── Ministry of Finance · Code 10 ── */
  { employeeId: 21001, firstName: "Tshewang", lastName: "Rinzin", gender: "Male", cid: "11001010001", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Director of Budget Planning", designation: "Director", positionLevel: "EX", workingAgency: "Ministry of Finance", agencyCode: "10", department: "Department of National Budget", subdivision: "Budget Policy Division", yearsOfService: 2, employeeStatus: "Active" },
  { employeeId: 21002, firstName: "Sangay", lastName: "Wangdi", gender: "Male", cid: "11001010002", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Senior Budget Officer", designation: "Senior Officer", positionLevel: "P2", workingAgency: "Ministry of Finance", agencyCode: "10", department: "Department of National Budget", subdivision: "Capital Budget Division", yearsOfService: 3, employeeStatus: "Active" },
  { employeeId: 21003, firstName: "Rinchen", lastName: "Dolma", gender: "Female", cid: "11001010003", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Revenue Analyst", designation: "Analyst", positionLevel: "P3", workingAgency: "Ministry of Finance", agencyCode: "10", department: "Department of Revenue & Customs", subdivision: "Taxation Division", yearsOfService: 4, employeeStatus: "Active" },
  { employeeId: 21004, firstName: "Tandin", lastName: "Phuntsho", gender: "Male", cid: "11001010004", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Customs Officer", designation: "Officer", positionLevel: "P4", workingAgency: "Ministry of Finance", agencyCode: "10", department: "Department of Revenue & Customs", subdivision: "Customs Division", yearsOfService: 5, employeeStatus: "Active" },
  { employeeId: 21005, firstName: "Dechen", lastName: "Pelden", gender: "Female", cid: "11001010005", employeeCategory: "civil-servant", employeeType: "Contract", positionTitle: "Treasury Analyst", designation: "Analyst", positionLevel: "P4", workingAgency: "Ministry of Finance", agencyCode: "10", department: "Department of Public Accounts", subdivision: "Treasury Division", yearsOfService: 6, employeeStatus: "Active" },
  { employeeId: 21006, firstName: "Kencho", lastName: "Wangmo", gender: "Female", cid: "11001010006", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Audit Officer", designation: "Officer", positionLevel: "P5", workingAgency: "Ministry of Finance", agencyCode: "10", department: "Department of Public Accounts", subdivision: "Internal Audit", yearsOfService: 7, employeeStatus: "EOL" },

  /* ── Ministry of Health · Code 21 ── */
  { employeeId: 22001, firstName: "Sonam", lastName: "Choden", gender: "Female", cid: "12101010001", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Senior Officer, Health Administration", designation: "Senior Officer", positionLevel: "P2", workingAgency: "Ministry of Health", agencyCode: "21", department: "Department of Medical Services", subdivision: "Hospital Administration", yearsOfService: 12, employeeStatus: "Active" },
  { employeeId: 22002, firstName: "Tshering", lastName: "Norbu", gender: "Male", cid: "12101010002", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Medical Officer", designation: "Officer", positionLevel: "P3", workingAgency: "Ministry of Health", agencyCode: "21", department: "Department of Medical Services", subdivision: "Primary Healthcare", yearsOfService: 13, employeeStatus: "Active" },
  { employeeId: 22003, firstName: "Kuenga", lastName: "Dem", gender: "Female", cid: "12101010003", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Nursing Supervisor", designation: "Supervisor", positionLevel: "P4", workingAgency: "Ministry of Health", agencyCode: "21", department: "Department of Medical Services", subdivision: "Nursing Services", yearsOfService: 14, employeeStatus: "Active" },
  { employeeId: 22004, firstName: "Nima", lastName: "Gyeltshen", gender: "Male", cid: "12101010004", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Public Health Inspector", designation: "Inspector", positionLevel: "P5", workingAgency: "Ministry of Health", agencyCode: "21", department: "Department of Public Health", subdivision: "Environmental Health", yearsOfService: 15, employeeStatus: "Active" },
  { employeeId: 22005, firstName: "Yangki", lastName: "Zangmo", gender: "Female", cid: "12101010005", employeeCategory: "civil-servant", employeeType: "Contract", positionTitle: "Epidemiologist", designation: "Specialist", positionLevel: "P2", workingAgency: "Ministry of Health", agencyCode: "21", department: "Department of Public Health", subdivision: "Epidemiology", yearsOfService: 1, employeeStatus: "Active" },

  /* ── Ministry of Education · Code 22 ── */
  { employeeId: 23001, firstName: "Kinzang", lastName: "Dorji", gender: "Male", cid: "12201010001", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Education Program Officer", designation: "Officer", positionLevel: "P4", workingAgency: "Ministry of Education & HR Development", agencyCode: "22", department: "Department of School Education", subdivision: "Curriculum Development", yearsOfService: 7, employeeStatus: "Active" },
  { employeeId: 23002, firstName: "Lhawang", lastName: "Tshomo", gender: "Female", cid: "12201010002", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Senior Curriculum Designer", designation: "Senior Officer", positionLevel: "P2", workingAgency: "Ministry of Education & HR Development", agencyCode: "22", department: "Department of School Education", subdivision: "Curriculum Development", yearsOfService: 8, employeeStatus: "Active" },
  { employeeId: 23003, firstName: "Deki", lastName: "Pem", gender: "Female", cid: "12201010003", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "School Inspector", designation: "Inspector", positionLevel: "P3", workingAgency: "Ministry of Education & HR Development", agencyCode: "22", department: "Department of School Education", subdivision: "Quality Assurance", yearsOfService: 9, employeeStatus: "Active" },
  { employeeId: 23004, firstName: "Passang", lastName: "Wangyal", gender: "Male", cid: "12201010004", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "HR Development Officer", designation: "Officer", positionLevel: "P5", workingAgency: "Ministry of Education & HR Development", agencyCode: "22", department: "Department of HR & Workforce", subdivision: "Capacity Building", yearsOfService: 10, employeeStatus: "Active" },
  { employeeId: 23005, firstName: "Thinley", lastName: "Norbu", gender: "Male", cid: "12201010005", employeeCategory: "civil-servant", employeeType: "Para-Regular", positionTitle: "Records Assistant", designation: "Assistant", positionLevel: "O3", workingAgency: "Ministry of Education & HR Development", agencyCode: "22", department: "Department of HR & Workforce", subdivision: "Records Management", yearsOfService: 11, employeeStatus: "Active" },

  /* ── Department of Road Safety & Transport · Code 31 ── */
  { employeeId: 24001, firstName: "Phurba", lastName: "Tshering", gender: "Male", cid: "13101010001", employeeCategory: "civil-servant", employeeType: "Consolidated-Contract", positionTitle: "Infrastructure Specialist", designation: "Specialist", positionLevel: "P3", workingAgency: "Department of Road Safety & Transport", agencyCode: "31", department: "Roads Division", subdivision: "National Highways", yearsOfService: 2, employeeStatus: "Active" },
  { employeeId: 24002, firstName: "Leki", lastName: "Dolkar", gender: "Female", cid: "13101010002", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Transport Inspector", designation: "Inspector", positionLevel: "P4", workingAgency: "Department of Road Safety & Transport", agencyCode: "31", department: "Transport Regulation", subdivision: "Licensing", yearsOfService: 3, employeeStatus: "Active" },
  { employeeId: 24003, firstName: "Wangchuk", lastName: "Phuntsho", gender: "Male", cid: "13101010003", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Road Safety Officer", designation: "Officer", positionLevel: "P5", workingAgency: "Department of Road Safety & Transport", agencyCode: "31", department: "Transport Regulation", subdivision: "Safety Audits", yearsOfService: 4, employeeStatus: "Study Leave" },
  { employeeId: 24004, firstName: "Tshoki", lastName: "Wangmo", gender: "Female", cid: "13101010004", employeeCategory: "civil-servant", employeeType: "Regular", positionTitle: "Senior Engineer", designation: "Senior Officer", positionLevel: "P2", workingAgency: "Department of Road Safety & Transport", agencyCode: "31", department: "Roads Division", subdivision: "Bridge Engineering", yearsOfService: 5, employeeStatus: "Active" },
];
