import { EmployeeData } from "../types";

/**
 * OPS (Other Public Servant) sample roster.
 *
 * Previously held only 5 rows and omitted the `agencyCode` field, which made
 * the Employee Summary Table show "0 employees" whenever the signed-in
 * persona was acting for an OPS agency like the Royal University of Bhutan
 * (code 68). This roster is now extended to 25+ entries across every OPS
 * agency channel, with an emphasis on RUB so its dashboard shows realistic
 * academic staff when the top-bar role is switched to an RUB persona.
 *
 * Each row carries an `agencyCode` that matches an OPS agency in
 * `shared/data/agencyPersonas.ts`:
 *   60 — BNLI (Legal)            64 — National Council (Parliamentary)
 *   61 — KGUMSB (Medical)        65 — OAG (Constitutional)
 *   62 — HMS4 (Royal Sec.)       66 — RPC (Constitutional)
 *   63 — TPS (Royal Sec.)        68 — RUB (Academic — focus agency)
 *   69 — RBP (pre-existing from legacy 30001 row)
 */
export const OPS_SAMPLE_EMPLOYEES: EmployeeData[] = [
  /* ── Royal University of Bhutan (code 68) — 10 academic staff ─── */
  {
    employeeId: 30101,
    firstName: "Tashi",
    lastName: "Wangchuk",
    gender: "Male",
    cid: "11680010001",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "Vice Chancellor",
    designation: "Vice Chancellor",
    positionLevel: "EX",
    workingAgency: "Royal University of Bhutan",
    agencyCode: "68",
    monthlyBasicPay: 88000,
    employeeStatus: "Active",
    departmentCount: 1,
  },
  {
    employeeId: 30102,
    firstName: "Sonam",
    lastName: "Dorji",
    gender: "Male",
    cid: "11680010002",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "Dean, Academic Affairs",
    designation: "Dean",
    positionLevel: "ES2",
    workingAgency: "Royal University of Bhutan",
    agencyCode: "68",
    monthlyBasicPay: 62000,
    employeeStatus: "Active",
    departmentCount: 6,
  },
  {
    employeeId: 30103,
    firstName: "Pema",
    lastName: "Lhamo",
    gender: "Female",
    cid: "11680010003",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "Professor",
    designation: "Professor",
    positionLevel: "ES3",
    workingAgency: "Royal University of Bhutan",
    agencyCode: "68",
    monthlyBasicPay: 51000,
    employeeStatus: "Study Leave",
    departmentCount: 8,
  },
  {
    employeeId: 30104,
    firstName: "Karma",
    lastName: "Tshering",
    gender: "Male",
    cid: "11680010004",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "Associate Professor",
    designation: "Associate Professor",
    positionLevel: "P1",
    workingAgency: "Royal University of Bhutan",
    agencyCode: "68",
    monthlyBasicPay: 42000,
    employeeStatus: "EOL",
    departmentCount: 12,
  },
  {
    employeeId: 30105,
    firstName: "Dechen",
    lastName: "Pelden",
    gender: "Female",
    cid: "11680010005",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "Assistant Professor",
    designation: "Assistant Professor",
    positionLevel: "P2",
    workingAgency: "Royal University of Bhutan",
    agencyCode: "68",
    monthlyBasicPay: 35000,
    employeeStatus: "Active",
    departmentCount: 15,
  },
  {
    employeeId: 30106,
    firstName: "Kinley",
    lastName: "Wangmo",
    gender: "Female",
    cid: "11680010006",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "Lecturer",
    designation: "Lecturer",
    positionLevel: "P3",
    workingAgency: "Royal University of Bhutan",
    agencyCode: "68",
    monthlyBasicPay: 29000,
    employeeStatus: "Active",
    departmentCount: 20,
  },
  {
    employeeId: 30107,
    firstName: "Ugyen",
    lastName: "Norbu",
    gender: "Male",
    cid: "11680010007",
    employeeCategory: "other-public-servant",
    employeeType: "Contract",
    positionTitle: "Lecturer",
    designation: "Lecturer",
    positionLevel: "P3",
    workingAgency: "Royal University of Bhutan",
    agencyCode: "68",
    monthlyBasicPay: 28500,
    employeeStatus: "Active",
    departmentCount: 20,
  },
  {
    employeeId: 30108,
    firstName: "Yangzom",
    lastName: "Choden",
    gender: "Female",
    cid: "11680010008",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "Registrar",
    designation: "Registrar",
    positionLevel: "P4",
    workingAgency: "Royal University of Bhutan",
    agencyCode: "68",
    monthlyBasicPay: 25000,
    employeeStatus: "Active",
    departmentCount: 4,
  },
  {
    employeeId: 30109,
    firstName: "Dorji",
    lastName: "Wangchuk",
    gender: "Male",
    cid: "11680010009",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "Research Fellow",
    designation: "Research Fellow",
    positionLevel: "P5",
    workingAgency: "Royal University of Bhutan",
    agencyCode: "68",
    monthlyBasicPay: 21000,
    employeeStatus: "Active",
    departmentCount: 7,
  },
  {
    employeeId: 30110,
    firstName: "Chimi",
    lastName: "Dema",
    gender: "Female",
    cid: "11680010010",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "Library Assistant",
    designation: "Library Assistant",
    positionLevel: "S2",
    workingAgency: "Royal University of Bhutan",
    agencyCode: "68",
    monthlyBasicPay: 15500,
    employeeStatus: "Active",
    departmentCount: 3,
  },

  /* ── BNLI (code 60) ─── */
  {
    employeeId: 30201,
    firstName: "Namgay",
    lastName: "Phuntsho",
    gender: "Male",
    cid: "11600020001",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "Director, BNLI",
    designation: "Director",
    positionLevel: "ES2",
    workingAgency: "Bhutan National Legal Institute",
    agencyCode: "60",
    monthlyBasicPay: 60000,
    employeeStatus: "Active",
    departmentCount: 1,
  },
  {
    employeeId: 30202,
    firstName: "Rinzin",
    lastName: "Dorji",
    gender: "Male",
    cid: "11600020002",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "Senior Legal Trainer",
    designation: "Senior Legal Trainer",
    positionLevel: "P1",
    workingAgency: "Bhutan National Legal Institute",
    agencyCode: "60",
    monthlyBasicPay: 41000,
    employeeStatus: "Active",
    departmentCount: 4,
  },

  /* ── KGUMSB (code 61) ─── */
  {
    employeeId: 30301,
    firstName: "Tshering",
    lastName: "Wangmo",
    gender: "Female",
    cid: "11610030001",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "President, KGUMSB",
    designation: "President",
    positionLevel: "EX",
    workingAgency: "Khesar Gyalpo University of Medical Sciences of Bhutan",
    agencyCode: "61",
    monthlyBasicPay: 86000,
    employeeStatus: "Active",
    departmentCount: 1,
  },
  {
    employeeId: 30302,
    firstName: "Sonam",
    lastName: "Tobgay",
    gender: "Male",
    cid: "11610030002",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "Professor of Medicine",
    designation: "Professor",
    positionLevel: "P1",
    workingAgency: "Khesar Gyalpo University of Medical Sciences of Bhutan",
    agencyCode: "61",
    monthlyBasicPay: 43000,
    employeeStatus: "Active",
    departmentCount: 2,
  },

  /* ── HMS4 (code 62) ─── */
  {
    employeeId: 30401,
    firstName: "Jigme",
    lastName: "Singye",
    gender: "Male",
    cid: "11620040001",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "Chief Secretary, HMS",
    designation: "Chief Secretary",
    positionLevel: "ES1",
    workingAgency: "His Majesty's Secretariat (4th King)",
    agencyCode: "62",
    monthlyBasicPay: 72000,
    employeeStatus: "Active",
    departmentCount: 1,
  },

  /* ── TPS (code 63) ─── */
  {
    employeeId: 30501,
    firstName: "Ashi",
    lastName: "Pema",
    gender: "Female",
    cid: "11630050001",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "Chief Secretary, TPS",
    designation: "Chief Secretary",
    positionLevel: "ES1",
    workingAgency: "The Pema Secretariat",
    agencyCode: "63",
    monthlyBasicPay: 70000,
    employeeStatus: "Active",
    departmentCount: 1,
  },
  {
    employeeId: 30502,
    firstName: "Tashi",
    lastName: "Phuntsho",
    gender: "Male",
    cid: "11630050002",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "Programme Director",
    designation: "Programme Director",
    positionLevel: "P1",
    workingAgency: "The Pema Secretariat",
    agencyCode: "63",
    monthlyBasicPay: 42000,
    employeeStatus: "Active",
    departmentCount: 3,
  },

  /* ── National Council (code 64) ─── */
  {
    employeeId: 30601,
    firstName: "Sangay",
    lastName: "Khandu",
    gender: "Male",
    cid: "11640060001",
    employeeCategory: "other-public-servant",
    employeeType: "Parliamentary",
    positionTitle: "Chairperson, National Council",
    designation: "Chairperson",
    positionLevel: "EX",
    workingAgency: "National Council",
    agencyCode: "64",
    monthlyBasicPay: 90000,
    employeeStatus: "Active",
    departmentCount: 1,
  },
  {
    employeeId: 30602,
    firstName: "Jigme",
    lastName: "Wangchuk",
    gender: "Male",
    cid: "11640060002",
    employeeCategory: "other-public-servant",
    employeeType: "Parliamentary",
    positionTitle: "Member of National Council",
    designation: "MNC",
    positionLevel: "ES2",
    workingAgency: "National Council",
    agencyCode: "64",
    monthlyBasicPay: 60000,
    employeeStatus: "Active",
    departmentCount: 1,
  },

  /* ── OAG (code 65) ─── */
  {
    employeeId: 30701,
    firstName: "Karma",
    lastName: "Dorji",
    gender: "Male",
    cid: "11650070001",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "Attorney General",
    designation: "Attorney General",
    positionLevel: "EX",
    workingAgency: "Office of the Attorney General",
    agencyCode: "65",
    monthlyBasicPay: 92000,
    employeeStatus: "Active",
    departmentCount: 1,
  },
  {
    employeeId: 30702,
    firstName: "Pema",
    lastName: "Dorji",
    gender: "Female",
    cid: "11650070002",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "Senior Legal Officer",
    designation: "Senior Legal Officer",
    positionLevel: "P1",
    workingAgency: "Office of the Attorney General",
    agencyCode: "65",
    monthlyBasicPay: 41500,
    employeeStatus: "Active",
    departmentCount: 2,
  },

  /* ── RPC (code 66) ─── */
  {
    employeeId: 30801,
    firstName: "Dasho",
    lastName: "Neten",
    gender: "Male",
    cid: "11660080001",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "Chairperson, RPC",
    designation: "Chairperson",
    positionLevel: "ES1",
    workingAgency: "Royal Privy Council",
    agencyCode: "66",
    monthlyBasicPay: 71000,
    employeeStatus: "Active",
    departmentCount: 1,
  },

  /* ── Legacy rows (preserved for backwards compatibility) ─── */
  {
    employeeId: 30001,
    firstName: "Jigmi",
    lastName: "Thinley",
    gender: "Male",
    cid: "10101010101",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "Inspector General",
    designation: "Inspector General",
    positionLevel: "EX",
    workingAgency: "Royal Bhutan Police",
    agencyCode: "69",
    monthlyBasicPay: 42000,
    employeeStatus: "Active",
    departmentCount: 78,
  },
  {
    employeeId: 30002,
    firstName: "Namgyel",
    lastName: "Choden",
    gender: "Female",
    cid: "10202020202",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "Magistrate",
    designation: "Magistrate",
    positionLevel: "ES2",
    workingAgency: "Judiciary",
    agencyCode: "60",
    monthlyBasicPay: 36000,
    employeeStatus: "Active",
    departmentCount: 18,
  },
  {
    employeeId: 30003,
    firstName: "Kunzang",
    lastName: "Gyatso",
    gender: "Male",
    cid: "10303030303",
    employeeCategory: "other-public-servant",
    employeeType: "Regular",
    positionTitle: "Dzongrab",
    designation: "Dzongrab",
    positionLevel: "P2",
    workingAgency: "Local Government",
    agencyCode: "63",
    monthlyBasicPay: 28000,
    employeeStatus: "Active",
    departmentCount: 25,
  },
  {
    employeeId: 30004,
    firstName: "Chimi",
    lastName: "Dorji",
    gender: "Male",
    cid: "10404040404",
    employeeCategory: "other-public-servant",
    employeeType: "Contract",
    positionTitle: "Senior Constable",
    designation: "Senior Constable",
    positionLevel: "S1",
    workingAgency: "Royal Bhutan Police",
    agencyCode: "69",
    monthlyBasicPay: 19500,
    employeeStatus: "Active",
    departmentCount: 42,
  },
  {
    employeeId: 30005,
    firstName: "Tashi",
    lastName: "Wangdi",
    gender: "Male",
    cid: "10505050505",
    employeeCategory: "other-public-servant",
    employeeType: "Parliamentary",
    positionTitle: "Member of National Assembly",
    designation: "MNA",
    positionLevel: "P1",
    workingAgency: "Parliament",
    agencyCode: "64",
    monthlyBasicPay: 31000,
    employeeStatus: "Active",
    departmentCount: 60,
  },
];
