/* Initial states for SanctionManagementPage forms */
import type {
  ContractorSanctionRecord,
  ContractualAdvanceRecord,
  EmployeeImprestRecord,
} from "../../types";

export const INITIAL_SANCTION: ContractorSanctionRecord = {
  sanctionId: "",
  contractorId: "",
  contractorName: "",
  sanctionType: "",
  sanctionStartDate: "",
  sanctionEndDate: "",
  autoReactivation: "N",
  sanctionReason: "",
  sanctionCategory: "",
  suspensionCategory: "",
  affectedAgencies: [],
  sanctioningAgency: "",
  supportingDocuments: [],
  sanctionStatus: "Active",
  createdAt: "",
  lastAmendedAt: "",
};

export const INITIAL_ADVANCE: ContractualAdvanceRecord = {
  advanceId: "",
  contractId: "",
  contractorId: "",
  agencyId: "",
  advanceType: "",
  amount: "",
  maxAllowable: "",
  purpose: "",
  contractStatus: "",
  workStatus: "",
  ucoaLevel: "",
  bankGuaranteeRef: "",
  bankGuaranteeValid: false,
  bankGuaranteeAmount: "",
  physicalProgressPercent: "",
  siteInspectionReport: false,
  materialAtApprovedSite: false,
  securityDocuments: false,
  verificationCertificate: false,
  status: "Pending",
  sanctioningAuthority: "",
  approvedAt: "",
  adjustedAgainstRAB: false,
};

export const INITIAL_IMPREST: EmployeeImprestRecord = {
  imprestId: "",
  employeeId: "",
  employeeName: "",
  designation: "",
  agencyCode: "",
  amount: "",
  purpose: "",
  ceilingLimit: "",
  previousImprestSettled: false,
  budgetAvailable: false,
  commitmentLinked: false,
  status: "Pending",
  approvedAt: "",
  settledAt: "",
  taxApplicable: false,
};

/* mock existing sanctions for the listing */
export const MOCK_SANCTIONS: ContractorSanctionRecord[] = [
  {
    sanctionId: "SAN-2026-0012",
    contractorId: "CTR-BH-4421",
    contractorName: "Druk Construction Pvt. Ltd",
    sanctionType: "Suspension",
    sanctionStartDate: "2026-01-15",
    sanctionEndDate: "2026-07-15",
    autoReactivation: "Y",
    sanctionReason: "Delayed completion of Thimphu bypass road Phase III beyond acceptable limit",
    sanctionCategory: "Contractual",
    suspensionCategory: "Temporary Suspension",
    affectedAgencies: ["Ministry of Works and Human Settlement", "PPD"],
    sanctioningAgency: "Ministry of Finance",
    supportingDocuments: [{ id: "d1", label: "Show Cause Notice", fileName: "SCN_4421.pdf", fileSize: "1.2 MB", uploadedAt: "2025-12-20" }],
    sanctionStatus: "Active",
    createdAt: "2026-01-10",
    lastAmendedAt: "",
  },
  {
    sanctionId: "SAN-2025-0087",
    contractorId: "CTR-BH-3208",
    contractorName: "Himalayan Supplies Co.",
    sanctionType: "Warning",
    sanctionStartDate: "2025-09-01",
    sanctionEndDate: "",
    autoReactivation: "N",
    sanctionReason: "Non-compliance with quality standards on ICT equipment delivery",
    sanctionCategory: "Financial",
    suspensionCategory: "",
    affectedAgencies: ["Ministry of Information and Communications"],
    sanctioningAgency: "PPD",
    supportingDocuments: [],
    sanctionStatus: "Active",
    createdAt: "2025-08-28",
    lastAmendedAt: "",
  },
  {
    sanctionId: "SAN-2025-0041",
    contractorId: "CTR-BH-1192",
    contractorName: "Eastern Bhutan Roads Corp.",
    sanctionType: "Debarment",
    sanctionStartDate: "2025-03-01",
    sanctionEndDate: "2028-03-01",
    autoReactivation: "N",
    sanctionReason: "Fraudulent documentation submitted for Trashigang bridge tender",
    sanctionCategory: "Legal",
    suspensionCategory: "Permanent Suspension",
    affectedAgencies: ["All Agencies"],
    sanctioningAgency: "Anti-Corruption Commission",
    supportingDocuments: [
      { id: "d2", label: "ACC Investigation Report", fileName: "ACC_1192.pdf", fileSize: "3.4 MB", uploadedAt: "2025-02-20" },
      { id: "d3", label: "Court Order", fileName: "Court_Order_1192.pdf", fileSize: "0.8 MB", uploadedAt: "2025-02-25" },
    ],
    sanctionStatus: "Active",
    createdAt: "2025-02-28",
    lastAmendedAt: "",
  },
];
