import { StoredFi } from './types/index';

export const SEED_FI_RECORDS: StoredFi[] = [
  {
    id: 'FI-2024-0001',
    header: {
      fiId: 'FI-2024-0001',
      institutionName: 'Bank of Bhutan',
      legalName: 'Bank of Bhutan Limited',
      institutionType: 'Commercial Bank',
      ownershipType: 'Government Owned',
      licenceCategory: 'Class A',
      licenceNumber: 'RMA/LIC/001/2008',
      licenceIssuedOn: '2008-01-15',
      licenceExpiresOn: '2028-01-14',
      regulatoryBody: 'Royal Monetary Authority',
      operatingRegion: 'Nationwide',
      headOfficeAddress: 'Post Box 162, Thimphu, Bhutan',
      contactPerson: 'Mr. Sangay Drukpa',
      contactEmail: 'info@bob.bt',
      contactPhone: '+975-2-321755',
      reportingCurrency: 'BTN',
      paidUpCapital: '150000000',
      declaredTurnover: '2850000000',
      registrationStatus: 'Active',
      riskRating: 'Low',
      reviewFrequency: 'Quarterly',
      narrative: 'Bank of Bhutan is the flagship commercial bank of Bhutan, established with government ownership. It operates nationwide with a strong presence in retail and corporate banking segments.',
    },
    documents: [
      {
        id: 'DOC-BOB-001',
        documentType: 'RMA Licence',
        documentRef: 'RMA/LIC/001/2008',
        issuedOn: '2008-01-15',
        expiresOn: '2028-01-14',
        remarks: 'Class A licence valid for 20 years. Latest renewal completed without conditions.',
      },
      {
        id: 'DOC-BOB-002',
        documentType: 'Certificate of Incorporation',
        documentRef: 'BOB/COI/2007/001',
        issuedOn: '2007-06-20',
        expiresOn: '',
        remarks: 'Certificate of Incorporation issued by the Department of Company Registration.',
      },
      {
        id: 'DOC-BOB-003',
        documentType: 'Audit Report',
        documentRef: 'BOB/AUDIT/2023/FY',
        issuedOn: '2023-12-28',
        expiresOn: '',
        remarks: 'Latest FY2023 audit report completed by certified external auditors. No material findings.',
      },
      {
        id: 'DOC-BOB-004',
        documentType: 'Financial Statement',
        documentRef: 'BOB/FS/2023/12',
        issuedOn: '2023-12-31',
        expiresOn: '',
        remarks: 'Annual financial statement for FY2023 showing capital adequacy ratio of 18.5%.',
      },
      {
        id: 'DOC-BOB-005',
        documentType: 'AML/CFT Policy',
        documentRef: 'BOB/AML/2024/01',
        issuedOn: '2024-01-10',
        expiresOn: '',
        remarks: 'Updated AML/CFT policy to align with RMA guidelines as of January 2024.',
      },
    ],
    services: [
      {
        id: 'SVC-BOB-001',
        serviceCategory: 'Retail Banking',
        launchDate: '2008-02-01',
        targetSegment: 'Individual depositors, small business owners, salaried professionals',
        remarks: 'Comprehensive retail banking products including savings accounts, fixed deposits, and personal loans.',
      },
      {
        id: 'SVC-BOB-002',
        serviceCategory: 'Corporate Lending',
        launchDate: '2008-02-01',
        targetSegment: 'Large corporations, government agencies, import-export traders',
        remarks: 'Corporate loan facilities for working capital, project financing, and term loans up to Nu 5 Billion.',
      },
      {
        id: 'SVC-BOB-003',
        serviceCategory: 'Mobile Banking',
        launchDate: '2015-06-15',
        targetSegment: 'All bank customers with mobile phones',
        remarks: 'Mobile banking app launched in 2015. Currently serving over 200,000 active users.',
      },
      {
        id: 'SVC-BOB-004',
        serviceCategory: 'Foreign Exchange',
        launchDate: '2008-02-01',
        targetSegment: 'Importers, exporters, and remittance recipients',
        remarks: 'Foreign exchange services for cross-border transactions and international trade finance.',
      },
    ],
    validationChecks: [
      {
        key: 'LICENCE_VALIDITY',
        label: 'Licence Validity Check',
        passed: true,
        message: 'RMA Licence RMA/LIC/001/2008 is valid until 2028-01-14. No compliance issues detected.',
      },
      {
        key: 'CAPITAL_ADEQUACY',
        label: 'Capital Adequacy Check',
        passed: true,
        message: 'Capital adequacy ratio of 18.5% exceeds RMA minimum requirement of 15%. Compliant.',
      },
      {
        key: 'AML_CFT_COMPLIANCE',
        label: 'AML/CFT Compliance Check',
        passed: true,
        message: 'AML/CFT policy updated as of Jan 2024. Last compliance audit in Nov 2023 showed no deficiencies.',
      },
      {
        key: 'BOARD_COMPOSITION',
        label: 'Board Composition Check',
        passed: true,
        message: 'Board has 9 members with appropriate mix of independent directors and executives. Compliant.',
      },
      {
        key: 'AUDIT_RECENCY',
        label: 'Audit Report Recency Check',
        passed: true,
        message: 'Latest audit report dated 2023-12-28 is current. Next annual audit due by 2024-12-31.',
      },
    ],
    approvals: [
      {
        id: 'APR-BOB-001',
        level: 'RMA Reviewer',
        actor: 'Ms. Pema Yangchen',
        decidedAt: '2024-01-05T10:30:00Z',
        decision: 'Approved',
        remarks: 'All RMA checks completed successfully. Documentation is complete and compliant.',
      },
      {
        id: 'APR-BOB-002',
        level: 'DTA Reviewer',
        actor: 'Mr. Tenzin Wangdi',
        decidedAt: '2024-01-08T14:15:00Z',
        decision: 'Approved',
        remarks: 'DTA financial review completed. Capital and liquidity positions satisfactory.',
      },
      {
        id: 'APR-BOB-003',
        level: 'DTA Approver',
        actor: 'Dr. Sonam Tshering',
        decidedAt: '2024-01-12T09:45:00Z',
        decision: 'Approved',
        remarks: 'Approved for continued operations and monitoring as Active institution.',
      },
      {
        id: 'APR-BOB-004',
        level: 'Finance Secretary',
        actor: 'Mr. Dasho Karma Tshering',
        decidedAt: '2024-01-15T16:20:00Z',
        decision: 'Approved',
        remarks: 'Final approval granted. Status confirmed as Active for FY2024.',
      },
    ],
    monitoring: [
      {
        id: 'MON-BOB-001',
        reviewDate: '2024-01-10',
        monitoringStatus: 'Compliant',
        reviewer: 'Ms. Pema Yangchen',
        observations: 'Q4 2023 reporting shows stable operations. Asset quality metrics within acceptable range. Liquidity position strong at 45% reserve ratio.',
        rectificationDue: '',
      },
      {
        id: 'MON-BOB-002',
        reviewDate: '2023-10-15',
        monitoringStatus: 'Compliant',
        reviewer: 'Mr. Tenzin Wangdi',
        observations: 'Q3 2023 review completed. Non-performing assets at 1.2%, below industry average. Consumer protection practices adequate.',
        rectificationDue: '',
      },
      {
        id: 'MON-BOB-003',
        reviewDate: '2023-07-08',
        monitoringStatus: 'Compliant',
        reviewer: 'Dr. Sonam Tshering',
        observations: 'Mid-year review shows robust governance. Risk management framework operational and effective. Stress testing results satisfactory.',
        rectificationDue: '',
      },
    ],
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-15T16:20:00Z',
  },
  {
    id: 'FI-2024-0002',
    header: {
      fiId: 'FI-2024-0002',
      institutionName: 'Bhutan National Bank',
      legalName: 'Bhutan National Bank PLC',
      institutionType: 'Commercial Bank',
      ownershipType: 'Private',
      licenceCategory: 'Class A',
      licenceNumber: 'RMA/LIC/002/2010',
      licenceIssuedOn: '2010-06-20',
      licenceExpiresOn: '2030-06-19',
      regulatoryBody: 'Royal Monetary Authority',
      operatingRegion: 'Nationwide',
      headOfficeAddress: 'Kawajangsa, Thimphu 11005, Bhutan',
      contactPerson: 'Mr. Dorji Tshering',
      contactEmail: 'contact@bnb.com.bt',
      contactPhone: '+975-2-325700',
      reportingCurrency: 'BTN',
      paidUpCapital: '100000000',
      declaredTurnover: '1950000000',
      registrationStatus: 'Active',
      riskRating: 'Low',
      reviewFrequency: 'Quarterly',
      narrative: 'Bhutan National Bank is a leading private sector commercial bank offering comprehensive banking services to individuals, corporations, and government entities. Strong market presence in digital banking.',
    },
    documents: [
      {
        id: 'DOC-BNB-001',
        documentType: 'RMA Licence',
        documentRef: 'RMA/LIC/002/2010',
        issuedOn: '2010-06-20',
        expiresOn: '2030-06-19',
        remarks: 'Class A licence renewed in 2020 for another 10-year period without conditions.',
      },
      {
        id: 'DOC-BNB-002',
        documentType: 'Certificate of Incorporation',
        documentRef: 'BNB/COI/2010/001',
        issuedOn: '2010-05-10',
        expiresOn: '',
        remarks: 'Certificate of Incorporation issued by Department of Company Registration.',
      },
      {
        id: 'DOC-BNB-003',
        documentType: 'Audit Report',
        documentRef: 'BNB/AUDIT/2023/FY',
        issuedOn: '2023-12-20',
        expiresOn: '',
        remarks: 'FY2023 audit completed by Bhutan Auditors & Associates. No major findings.',
      },
      {
        id: 'DOC-BNB-004',
        documentType: 'Financial Statement',
        documentRef: 'BNB/FS/2023/12',
        issuedOn: '2023-12-31',
        expiresOn: '',
        remarks: 'Annual financial statement showing capital adequacy ratio of 16.8% as of end FY2023.',
      },
      {
        id: 'DOC-BNB-005',
        documentType: 'Board Resolution',
        documentRef: 'BNB/BR/2024/01',
        issuedOn: '2024-01-08',
        expiresOn: '',
        remarks: 'Board resolution approving continued operations and quarterly reporting to RMA.',
      },
    ],
    services: [
      {
        id: 'SVC-BNB-001',
        serviceCategory: 'Retail Banking',
        launchDate: '2010-07-01',
        targetSegment: 'Individual customers, retail merchants, small enterprises',
        remarks: 'Comprehensive retail banking with savings, current, and overdraft accounts.',
      },
      {
        id: 'SVC-BNB-002',
        serviceCategory: 'Corporate Lending',
        launchDate: '2010-07-01',
        targetSegment: 'Large corporations, trading companies, construction firms',
        remarks: 'Corporate lending facilities with exposure limit of Nu 2.5 Billion per borrower.',
      },
      {
        id: 'SVC-BNB-003',
        serviceCategory: 'Mobile Banking',
        launchDate: '2017-03-20',
        targetSegment: 'All customer segments with mobile devices',
        remarks: 'Advanced mobile banking app launched 2017 with 180,000 active monthly users.',
      },
      {
        id: 'SVC-BNB-004',
        serviceCategory: 'Remittance',
        launchDate: '2012-01-10',
        targetSegment: 'Migrant workers, overseas Bhutanese, diaspora',
        remarks: 'Remittance services through partnership with Western Union and Money Gram.',
      },
    ],
    validationChecks: [
      {
        key: 'LICENCE_VALIDITY',
        label: 'Licence Validity Check',
        passed: true,
        message: 'RMA Licence valid until 2030-06-19. No compliance breaches noted.',
      },
      {
        key: 'CAPITAL_ADEQUACY',
        label: 'Capital Adequacy Check',
        passed: true,
        message: 'Capital adequacy ratio of 16.8% meets RMA minimum of 15%. Adequate buffer maintained.',
      },
      {
        key: 'AML_CFT_COMPLIANCE',
        label: 'AML/CFT Compliance Check',
        passed: true,
        message: 'AML/CFT policy in place and operational. Last compliance review in Sept 2023 with no deficiencies.',
      },
      {
        key: 'BOARD_COMPOSITION',
        label: 'Board Composition Check',
        passed: true,
        message: 'Board comprises 7 members including 3 independent directors. Meets governance requirements.',
      },
      {
        key: 'AUDIT_RECENCY',
        label: 'Audit Report Recency Check',
        passed: true,
        message: 'Current audit dated 2023-12-20. Schedule audit for Dec 2024.',
      },
    ],
    approvals: [
      {
        id: 'APR-BNB-001',
        level: 'RMA Reviewer',
        actor: 'Mr. Phuntsho Dorji',
        decidedAt: '2024-01-06T11:00:00Z',
        decision: 'Approved',
        remarks: 'RMA compliance checks completed. All regulatory filings up to date.',
      },
      {
        id: 'APR-BNB-002',
        level: 'DTA Reviewer',
        actor: 'Ms. Kinzang Choden',
        decidedAt: '2024-01-09T15:30:00Z',
        decision: 'Approved',
        remarks: 'DTA financial review satisfactory. Liquidity and solvency within norms.',
      },
      {
        id: 'APR-BNB-003',
        level: 'DTA Approver',
        actor: 'Mr. Ugyen Dorji',
        decidedAt: '2024-01-13T10:00:00Z',
        decision: 'Approved',
        remarks: 'Final institutional approval granted for continued Active status.',
      },
    ],
    monitoring: [
      {
        id: 'MON-BNB-001',
        reviewDate: '2024-01-08',
        monitoringStatus: 'Compliant',
        reviewer: 'Mr. Phuntsho Dorji',
        observations: 'Q4 2023 results show healthy growth trajectory. Digital banking adoption at 65%. Risk profile remains manageable.',
        rectificationDue: '',
      },
      {
        id: 'MON-BNB-002',
        reviewDate: '2023-10-20',
        monitoringStatus: 'Compliant',
        reviewer: 'Ms. Kinzang Choden',
        observations: 'Q3 2023 review: NPL ratio at 1.5%. Governance framework operational. No systemic risks identified.',
        rectificationDue: '',
      },
    ],
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-13T10:00:00Z',
  },
  {
    id: 'FI-2024-0003',
    header: {
      fiId: 'FI-2024-0003',
      institutionName: 'Bhutan Development Bank Ltd',
      legalName: 'Bhutan Development Bank Limited',
      institutionType: 'Development Finance Institution',
      ownershipType: 'Government Owned',
      licenceCategory: 'Class B',
      licenceNumber: 'RMA/LIC/003/2012',
      licenceIssuedOn: '2012-03-15',
      licenceExpiresOn: '2032-03-14',
      regulatoryBody: 'Royal Monetary Authority',
      operatingRegion: 'Nationwide',
      headOfficeAddress: 'Kawajangsa, Thimphu 11005, Bhutan',
      contactPerson: 'Mr. Karma Singye',
      contactEmail: 'info@bdb.bt',
      contactPhone: '+975-2-325200',
      reportingCurrency: 'BTN',
      paidUpCapital: '500000000',
      declaredTurnover: '850000000',
      registrationStatus: 'Active',
      riskRating: 'Medium',
      reviewFrequency: 'Semi-annually',
      narrative: 'Bhutan Development Bank is a government-owned DFI focused on long-term financing for infrastructure, agriculture, tourism, and SME development in alignment with national development priorities.',
    },
    documents: [
      {
        id: 'DOC-BDB-001',
        documentType: 'RMA Licence',
        documentRef: 'RMA/LIC/003/2012',
        issuedOn: '2012-03-15',
        expiresOn: '2032-03-14',
        remarks: 'Class B DFI licence issued for infrastructure and development finance. Valid through 2032.',
      },
      {
        id: 'DOC-BDB-002',
        documentType: 'Certificate of Incorporation',
        documentRef: 'BDB/COI/2012/001',
        issuedOn: '2012-02-20',
        expiresOn: '',
        remarks: 'Established as development finance institution by government charter.',
      },
      {
        id: 'DOC-BDB-003',
        documentType: 'Audit Report',
        documentRef: 'BDB/AUDIT/2023/FY',
        issuedOn: '2023-11-30',
        expiresOn: '',
        remarks: 'FY2023 audit by External Auditors. One minor observation on documentation standards raised.',
      },
      {
        id: 'DOC-BDB-004',
        documentType: 'Financial Statement',
        documentRef: 'BDB/FS/2023/12',
        issuedOn: '2023-12-31',
        expiresOn: '',
        remarks: 'Financial statement showing capital ratio of 25.2%. Strong capital position for DFI operations.',
      },
      {
        id: 'DOC-BDB-005',
        documentType: 'AML/CFT Policy',
        documentRef: 'BDB/AML/2023/12',
        issuedOn: '2023-12-01',
        expiresOn: '',
        remarks: 'Updated AML/CFT policy reflecting enhanced customer due diligence requirements.',
      },
    ],
    services: [
      {
        id: 'SVC-BDB-001',
        serviceCategory: 'Corporate Lending',
        launchDate: '2012-04-01',
        targetSegment: 'Infrastructure projects, agricultural enterprises, tourism operators',
        remarks: 'Long-term financing (up to 15 years) for development projects with competitive rates.',
      },
      {
        id: 'SVC-BDB-002',
        serviceCategory: 'Retail Banking',
        launchDate: '2012-04-01',
        targetSegment: 'Individuals, cooperatives, SMEs, self-help groups',
        remarks: 'Savings and term loan products targeting rural and underserved populations.',
      },
      {
        id: 'SVC-BDB-003',
        serviceCategory: 'Foreign Exchange',
        launchDate: '2015-01-10',
        targetSegment: 'Importers of capital equipment, cross-border project transactions',
        remarks: 'FX services for international development project financing.',
      },
    ],
    validationChecks: [
      {
        key: 'LICENCE_VALIDITY',
        label: 'Licence Validity Check',
        passed: true,
        message: 'RMA DFI Licence RMA/LIC/003/2012 valid until 2032-03-14. Compliant.',
      },
      {
        key: 'CAPITAL_ADEQUACY',
        label: 'Capital Adequacy Check',
        passed: true,
        message: 'Capital ratio of 25.2% significantly exceeds 12% requirement for DFIs. Strong.',
      },
      {
        key: 'AML_CFT_COMPLIANCE',
        label: 'AML/CFT Compliance Check',
        passed: true,
        message: 'AML/CFT policy updated Dec 2023. Compliance controls operational and monitored.',
      },
      {
        key: 'BOARD_COMPOSITION',
        label: 'Board Composition Check',
        passed: true,
        message: 'Board has 9 members with mix of government nominees and independent experts. Adequate.',
      },
      {
        key: 'AUDIT_RECENCY',
        label: 'Audit Report Recency Check',
        passed: true,
        message: 'Latest audit dated 2023-11-30. Next audit scheduled for Nov 2024.',
      },
    ],
    approvals: [
      {
        id: 'APR-BDB-001',
        level: 'RMA Reviewer',
        actor: 'Ms. Pema Yangchen',
        decidedAt: '2024-01-04T09:15:00Z',
        decision: 'Approved',
        remarks: 'RMA review completed. Minor documentation observation noted but resolved.',
      },
      {
        id: 'APR-BDB-002',
        level: 'DTA Reviewer',
        actor: 'Mr. Tenzin Wangdi',
        decidedAt: '2024-01-10T14:00:00Z',
        decision: 'Conditionally Approved',
        remarks: 'Conditional approval pending enhanced reporting on project performance metrics by Q1 2024.',
      },
      {
        id: 'APR-BDB-003',
        level: 'DTA Approver',
        actor: 'Dr. Sonam Tshering',
        decidedAt: '2024-01-14T11:30:00Z',
        decision: 'Approved',
        remarks: 'Conditional approval lifted. Continued monitoring as per semi-annual schedule.',
      },
    ],
    monitoring: [
      {
        id: 'MON-BDB-001',
        reviewDate: '2024-01-12',
        monitoringStatus: 'Compliant',
        reviewer: 'Ms. Pema Yangchen',
        observations: 'Latest portfolio review shows portfolio quality index at 92%. Project disbursement on schedule. Development impact metrics strong.',
        rectificationDue: '',
      },
      {
        id: 'MON-BDB-002',
        reviewDate: '2023-07-20',
        monitoringStatus: 'Minor Issues',
        reviewer: 'Mr. Tenzin Wangdi',
        observations: 'Mid-year review identified need for enhanced documentation in 5 loan files. Corrective action plan implemented.',
        rectificationDue: '2023-09-30',
      },
    ],
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-14T11:30:00Z',
  },
  {
    id: 'FI-2024-0004',
    header: {
      fiId: 'FI-2024-0004',
      institutionName: 'Royal Insurance Corporation of Bhutan',
      legalName: 'Royal Insurance Corporation of Bhutan Limited',
      institutionType: 'Insurance Company',
      ownershipType: 'Government Owned',
      licenceCategory: 'Class A',
      licenceNumber: 'IRA/LIC/001/2008',
      licenceIssuedOn: '2008-07-20',
      licenceExpiresOn: '2028-07-19',
      regulatoryBody: 'Insurance Regulatory Authority',
      operatingRegion: 'Nationwide',
      headOfficeAddress: 'Norzin Lam, Thimphu 11001, Bhutan',
      contactPerson: 'Ms. Sonam Dorji',
      contactEmail: 'info@ricb.bt',
      contactPhone: '+975-2-323522',
      reportingCurrency: 'BTN',
      paidUpCapital: '75000000',
      declaredTurnover: '1200000000',
      registrationStatus: 'Active',
      riskRating: 'Low',
      reviewFrequency: 'Semi-annually',
      narrative: 'RICB is the leading government-owned insurance provider in Bhutan offering comprehensive life and general insurance products. Market leader in health insurance and mandatory liability coverage.',
    },
    documents: [
      {
        id: 'DOC-RICB-001',
        documentType: 'RMA Licence',
        documentRef: 'IRA/LIC/001/2008',
        issuedOn: '2008-07-20',
        expiresOn: '2028-07-19',
        remarks: 'Composite insurance licence (Life & General) issued by Insurance Regulatory Authority.',
      },
      {
        id: 'DOC-RICB-002',
        documentType: 'Certificate of Incorporation',
        documentRef: 'RICB/COI/2008/001',
        issuedOn: '2008-06-15',
        expiresOn: '',
        remarks: 'Incorporated as government enterprise for insurance business.',
      },
      {
        id: 'DOC-RICB-003',
        documentType: 'Audit Report',
        documentRef: 'RICB/AUDIT/2023/FY',
        issuedOn: '2023-12-15',
        expiresOn: '',
        remarks: 'FY2023 audit by KPMG Bhutan. Technical reserves adequately provisioned. Clean audit opinion.',
      },
      {
        id: 'DOC-RICB-004',
        documentType: 'Financial Statement',
        documentRef: 'RICB/FS/2023/12',
        issuedOn: '2023-12-31',
        expiresOn: '',
        remarks: 'Annual financial statement showing solvency ratio of 185%. Strong capital position.',
      },
      {
        id: 'DOC-RICB-005',
        documentType: 'Board Resolution',
        documentRef: 'RICB/BR/2024/01',
        issuedOn: '2024-01-10',
        expiresOn: '',
        remarks: 'Board resolution approving continued operations and IRA compliance measures.',
      },
    ],
    services: [
      {
        id: 'SVC-RICB-001',
        serviceCategory: 'Insurance — Life',
        launchDate: '2008-08-01',
        targetSegment: 'Individuals, groups, corporate staff',
        remarks: 'Life insurance products including term, endowment, and group life coverage.',
      },
      {
        id: 'SVC-RICB-002',
        serviceCategory: 'Insurance — General',
        launchDate: '2008-08-01',
        targetSegment: 'Vehicle owners, property owners, businesses, travelers',
        remarks: 'General insurance covering motor, property, liability, and health segments.',
      },
      {
        id: 'SVC-RICB-003',
        serviceCategory: 'Remittance',
        launchDate: '2012-05-15',
        targetSegment: 'Overseas Bhutanese, migrant workers',
        remarks: 'Remittance facilitation through partnership with international insurance networks.',
      },
    ],
    validationChecks: [
      {
        key: 'LICENCE_VALIDITY',
        label: 'Licence Validity Check',
        passed: true,
        message: 'IRA Composite Licence valid until 2028-07-19. No compliance flags.',
      },
      {
        key: 'CAPITAL_ADEQUACY',
        label: 'Capital Adequacy Check',
        passed: true,
        message: 'Solvency ratio of 185% well exceeds IRA minimum of 150%. Exceptional.',
      },
      {
        key: 'AML_CFT_COMPLIANCE',
        label: 'AML/CFT Compliance Check',
        passed: true,
        message: 'AML/CFT policy in place. Customer due diligence procedures operational.',
      },
      {
        key: 'BOARD_COMPOSITION',
        label: 'Board Composition Check',
        passed: true,
        message: 'Board comprises 7 members including insurance industry experts. Well structured.',
      },
      {
        key: 'AUDIT_RECENCY',
        label: 'Audit Report Recency Check',
        passed: true,
        message: 'Current audit dated 2023-12-15. Next audit due Dec 2024.',
      },
    ],
    approvals: [
      {
        id: 'APR-RICB-001',
        level: 'RMA Reviewer',
        actor: 'Mr. Phuntsho Dorji',
        decidedAt: '2024-01-05T10:45:00Z',
        decision: 'Approved',
        remarks: 'IRA compliance checks completed successfully.',
      },
      {
        id: 'APR-RICB-002',
        level: 'DTA Reviewer',
        actor: 'Ms. Kinzang Choden',
        decidedAt: '2024-01-09T16:00:00Z',
        decision: 'Approved',
        remarks: 'Financial position strong. Technical reserves adequately invested.',
      },
      {
        id: 'APR-RICB-003',
        level: 'DTA Approver',
        actor: 'Mr. Ugyen Dorji',
        decidedAt: '2024-01-12T13:30:00Z',
        decision: 'Approved',
        remarks: 'Continued Active status confirmed for FY2024.',
      },
    ],
    monitoring: [
      {
        id: 'MON-RICB-001',
        reviewDate: '2024-01-10',
        monitoringStatus: 'Compliant',
        reviewer: 'Mr. Phuntsho Dorji',
        observations: 'Q4 2023 performance shows stable premium growth at 8%. Claims processing on schedule. Customer satisfaction metrics positive.',
        rectificationDue: '',
      },
      {
        id: 'MON-RICB-002',
        reviewDate: '2023-09-15',
        monitoringStatus: 'Compliant',
        reviewer: 'Ms. Kinzang Choden',
        observations: 'Q3 2023 review: Premium income Bu 315M. Claims ratio 62%. Governance framework operational.',
        rectificationDue: '',
      },
    ],
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-12T13:30:00Z',
  },
  {
    id: 'FI-2024-0005',
    header: {
      fiId: 'FI-2024-0005',
      institutionName: 'T-Bank Ltd',
      legalName: 'T-Bank Limited',
      institutionType: 'Commercial Bank',
      ownershipType: 'Private',
      licenceCategory: 'Class A',
      licenceNumber: 'RMA/LIC/004/2013',
      licenceIssuedOn: '2013-09-15',
      licenceExpiresOn: '2033-09-14',
      regulatoryBody: 'Royal Monetary Authority',
      operatingRegion: 'Nationwide',
      headOfficeAddress: 'T-Bank Plaza, Thimphu, Bhutan',
      contactPerson: 'Mr. Tenzing Gyaltsen',
      contactEmail: 'info@tbank.bt',
      contactPhone: '+975-2-321800',
      reportingCurrency: 'BTN',
      paidUpCapital: '120000000',
      declaredTurnover: '2100000000',
      registrationStatus: 'Active',
      riskRating: 'Low',
      reviewFrequency: 'Quarterly',
      narrative: 'T-Bank is a premier private commercial bank specializing in retail banking, youth financial inclusion, and innovative fintech solutions. Strong digital presence and mobile-first banking strategy.',
    },
    documents: [
      {
        id: 'DOC-TBANK-001',
        documentType: 'RMA Licence',
        documentRef: 'RMA/LIC/004/2013',
        issuedOn: '2013-09-15',
        expiresOn: '2033-09-14',
        remarks: 'Class A commercial banking licence valid for 20 years from issuance.',
      },
      {
        id: 'DOC-TBANK-002',
        documentType: 'Certificate of Incorporation',
        documentRef: 'TBANK/COI/2013/001',
        issuedOn: '2013-08-20',
        expiresOn: '',
        remarks: 'Registered private limited company with Ministry of Economic Affairs.',
      },
      {
        id: 'DOC-TBANK-003',
        documentType: 'Audit Report',
        documentRef: 'TBANK/AUDIT/2023/FY',
        issuedOn: '2023-12-25',
        expiresOn: '',
        remarks: 'FY2023 audit by Deloitte Bhutan. Unqualified opinion. Strong compliance findings.',
      },
      {
        id: 'DOC-TBANK-004',
        documentType: 'Financial Statement',
        documentRef: 'TBANK/FS/2023/12',
        issuedOn: '2023-12-31',
        expiresOn: '',
        remarks: 'FY2023 financials showing CAR of 17.3% and ROA of 2.8%. Solid performance.',
      },
      {
        id: 'DOC-TBANK-005',
        documentType: 'AML/CFT Policy',
        documentRef: 'TBANK/AML/2024/01',
        issuedOn: '2024-01-15',
        expiresOn: '',
        remarks: 'Updated AML/CFT policy with enhanced KYC and transaction monitoring measures.',
      },
    ],
    services: [
      {
        id: 'SVC-TBANK-001',
        serviceCategory: 'Retail Banking',
        launchDate: '2013-10-01',
        targetSegment: 'Youth, students, salaried professionals, small business owners',
        remarks: 'Focused retail banking with youth-oriented products and minimal documentation.',
      },
      {
        id: 'SVC-TBANK-002',
        serviceCategory: 'Mobile Banking',
        launchDate: '2014-06-15',
        targetSegment: 'All customer segments with mobile devices',
        remarks: 'Pioneering mobile banking in Bhutan with 350,000 active mobile banking users.',
      },
      {
        id: 'SVC-TBANK-003',
        serviceCategory: 'Corporate Lending',
        launchDate: '2013-10-01',
        targetSegment: 'SMEs, trading firms, hospitality sector',
        remarks: 'SME-focused lending with simplified application and faster approval.',
      },
      {
        id: 'SVC-TBANK-004',
        serviceCategory: 'Foreign Exchange',
        launchDate: '2013-10-01',
        targetSegment: 'Travelers, traders, cross-border transaction users',
        remarks: 'FX services with competitive rates and quick processing.',
      },
    ],
    validationChecks: [
      {
        key: 'LICENCE_VALIDITY',
        label: 'Licence Validity Check',
        passed: true,
        message: 'RMA Licence RMA/LIC/004/2013 valid until 2033-09-14. Compliant.',
      },
      {
        key: 'CAPITAL_ADEQUACY',
        label: 'Capital Adequacy Check',
        passed: true,
        message: 'Capital adequacy ratio of 17.3% exceeds RMA requirement of 15%. Healthy buffer.',
      },
      {
        key: 'AML_CFT_COMPLIANCE',
        label: 'AML/CFT Compliance Check',
        passed: true,
        message: 'AML/CFT policy updated Jan 2024 with enhanced transaction monitoring.',
      },
      {
        key: 'BOARD_COMPOSITION',
        label: 'Board Composition Check',
        passed: true,
        message: 'Board of 6 directors includes fintech and banking experts. Well qualified.',
      },
      {
        key: 'AUDIT_RECENCY',
        label: 'Audit Report Recency Check',
        passed: true,
        message: 'Latest audit dated 2023-12-25. Unqualified opinion received.',
      },
    ],
    approvals: [
      {
        id: 'APR-TBANK-001',
        level: 'RMA Reviewer',
        actor: 'Ms. Pema Yangchen',
        decidedAt: '2024-01-05T14:20:00Z',
        decision: 'Approved',
        remarks: 'RMA checks completed. All regulatory filings current.',
      },
      {
        id: 'APR-TBANK-002',
        level: 'DTA Reviewer',
        actor: 'Mr. Tenzin Wangdi',
        decidedAt: '2024-01-08T11:15:00Z',
        decision: 'Approved',
        remarks: 'Financial metrics strong. Growth trajectory positive.',
      },
      {
        id: 'APR-TBANK-003',
        level: 'DTA Approver',
        actor: 'Dr. Sonam Tshering',
        decidedAt: '2024-01-11T09:45:00Z',
        decision: 'Approved',
        remarks: 'Approved for continued Active operations with quarterly monitoring.',
      },
    ],
    monitoring: [
      {
        id: 'MON-TBANK-001',
        reviewDate: '2024-01-09',
        monitoringStatus: 'Compliant',
        reviewer: 'Ms. Pema Yangchen',
        observations: 'Q4 2023 shows strong digital adoption at 72%. Customer base growing. NPL ratio at 0.9%, excellent.',
        rectificationDue: '',
      },
      {
        id: 'MON-TBANK-002',
        reviewDate: '2023-10-12',
        monitoringStatus: 'Compliant',
        reviewer: 'Mr. Tenzin Wangdi',
        observations: 'Q3 2023: Mobile banking users exceed expectations. Operating costs efficiently managed.',
        rectificationDue: '',
      },
    ],
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-11T09:45:00Z',
  },
  {
    id: 'FI-2024-0006',
    header: {
      fiId: 'FI-2024-0006',
      institutionName: 'RICB General Insurance',
      legalName: 'RICB General Insurance Limited',
      institutionType: 'Insurance Company',
      ownershipType: 'Joint Venture',
      licenceCategory: 'Class B',
      licenceNumber: 'IRA/LIC/002/2015',
      licenceIssuedOn: '2015-04-10',
      licenceExpiresOn: '2030-04-09',
      regulatoryBody: 'Insurance Regulatory Authority',
      operatingRegion: 'Nationwide',
      headOfficeAddress: 'Kawajangsa, Thimphu, Bhutan',
      contactPerson: 'Mr. Passang Dorji',
      contactEmail: 'info@ricbgi.bt',
      contactPhone: '+975-2-324500',
      reportingCurrency: 'BTN',
      paidUpCapital: '50000000',
      declaredTurnover: '520000000',
      registrationStatus: 'Active',
      riskRating: 'Low',
      reviewFrequency: 'Semi-annually',
      narrative: 'RICB General Insurance is a joint venture between government and private investors providing comprehensive general insurance products including motor, health, property, and commercial covers.',
    },
    documents: [
      {
        id: 'DOC-RICBGI-001',
        documentType: 'RMA Licence',
        documentRef: 'IRA/LIC/002/2015',
        issuedOn: '2015-04-10',
        expiresOn: '2030-04-09',
        remarks: 'General insurance licence issued by Insurance Regulatory Authority for 15 years.',
      },
      {
        id: 'DOC-RICBGI-002',
        documentType: 'Certificate of Incorporation',
        documentRef: 'RICBGI/COI/2015/001',
        issuedOn: '2015-03-15',
        expiresOn: '',
        remarks: 'Joint venture company registered between RICB and private investor group.',
      },
      {
        id: 'DOC-RICBGI-003',
        documentType: 'Audit Report',
        documentRef: 'RICBGI/AUDIT/2023/FY',
        issuedOn: '2023-12-10',
        expiresOn: '',
        remarks: 'FY2023 audit by Bhutan Auditors. Clean opinion. Technical reserves adequate.',
      },
      {
        id: 'DOC-RICBGI-004',
        documentType: 'Financial Statement',
        documentRef: 'RICBGI/FS/2023/12',
        issuedOn: '2023-12-31',
        expiresOn: '',
        remarks: 'FY2023 financials showing solvency margin of 165%. Healthy underwriting position.',
      },
      {
        id: 'DOC-RICBGI-005',
        documentType: 'Board Resolution',
        documentRef: 'RICBGI/BR/2024/01',
        issuedOn: '2024-01-12',
        expiresOn: '',
        remarks: 'Board resolution approving continued operations and investment in modern claims management systems.',
      },
    ],
    services: [
      {
        id: 'SVC-RICBGI-001',
        serviceCategory: 'Insurance — General',
        launchDate: '2015-05-01',
        targetSegment: 'Vehicle owners, property owners, businesses, commercial enterprises',
        remarks: 'Comprehensive general insurance covering motor, health, property, and liability.',
      },
      {
        id: 'SVC-RICBGI-002',
        serviceCategory: 'Retail Banking',
        launchDate: '2016-03-10',
        targetSegment: 'Insurance customers and depositors',
        remarks: 'Limited retail banking services for insurance premium collection and premium financing.',
      },
      {
        id: 'SVC-RICBGI-003',
        serviceCategory: 'Foreign Exchange',
        launchDate: '2018-01-15',
        targetSegment: 'International insurance claims and premium payments',
        remarks: 'FX services for international reinsurance transactions and claims settlements.',
      },
    ],
    validationChecks: [
      {
        key: 'LICENCE_VALIDITY',
        label: 'Licence Validity Check',
        passed: true,
        message: 'IRA General Insurance Licence valid until 2030-04-09. Compliant.',
      },
      {
        key: 'CAPITAL_ADEQUACY',
        label: 'Capital Adequacy Check',
        passed: true,
        message: 'Solvency margin of 165% exceeds IRA minimum of 150%. Strong capital base.',
      },
      {
        key: 'AML_CFT_COMPLIANCE',
        label: 'AML/CFT Compliance Check',
        passed: true,
        message: 'AML/CFT policy in place. Customer due diligence procedures current.',
      },
      {
        key: 'BOARD_COMPOSITION',
        label: 'Board Composition Check',
        passed: true,
        message: 'Board has 5 directors with insurance and joint venture management expertise. Adequate.',
      },
      {
        key: 'AUDIT_RECENCY',
        label: 'Audit Report Recency Check',
        passed: true,
        message: 'Latest audit dated 2023-12-10. Next audit due Dec 2024.',
      },
    ],
    approvals: [
      {
        id: 'APR-RICBGI-001',
        level: 'RMA Reviewer',
        actor: 'Mr. Phuntsho Dorji',
        decidedAt: '2024-01-06T15:30:00Z',
        decision: 'Approved',
        remarks: 'IRA compliance checks completed without issues.',
      },
      {
        id: 'APR-RICBGI-002',
        level: 'DTA Reviewer',
        actor: 'Ms. Kinzang Choden',
        decidedAt: '2024-01-10T10:00:00Z',
        decision: 'Approved',
        remarks: 'Financial review shows stable operations and growing market share.',
      },
      {
        id: 'APR-RICBGI-003',
        level: 'DTA Approver',
        actor: 'Mr. Ugyen Dorji',
        decidedAt: '2024-01-13T14:15:00Z',
        decision: 'Approved',
        remarks: 'Continued Active status confirmed for FY2024.',
      },
    ],
    monitoring: [
      {
        id: 'MON-RICBGI-001',
        reviewDate: '2024-01-11',
        monitoringStatus: 'Compliant',
        reviewer: 'Mr. Phuntsho Dorji',
        observations: 'Q4 2023 premium income Bu 135M. Claims ratio 58%. Governance effective.',
        rectificationDue: '',
      },
      {
        id: 'MON-RICBGI-002',
        reviewDate: '2023-07-30',
        monitoringStatus: 'Compliant',
        reviewer: 'Ms. Kinzang Choden',
        observations: 'Mid-year review: Market growth initiatives on track. Reinsurance arrangements current.',
        rectificationDue: '',
      },
    ],
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-13T14:15:00Z',
  },
  {
    id: 'FI-2024-0007',
    header: {
      fiId: 'FI-2024-0007',
      institutionName: 'RENEW Microfinance',
      legalName: 'RENEW Microfinance Society Limited',
      institutionType: 'Microfinance Institution',
      ownershipType: 'Cooperative',
      licenceCategory: 'Class C',
      licenceNumber: 'RMA/LIC/005/2014',
      licenceIssuedOn: '2014-08-20',
      licenceExpiresOn: '2029-08-19',
      regulatoryBody: 'Royal Monetary Authority',
      operatingRegion: 'Central Region',
      headOfficeAddress: 'Wogmin, Thimphu, Bhutan',
      contactPerson: 'Ms. Namgay Wangmo',
      contactEmail: 'info@renewmfi.bt',
      contactPhone: '+975-2-325100',
      reportingCurrency: 'BTN',
      paidUpCapital: '25000000',
      declaredTurnover: '180000000',
      registrationStatus: 'Provisional',
      riskRating: 'Medium',
      reviewFrequency: 'Semi-annually',
      narrative: 'RENEW Microfinance is a cooperative-based microfinance institution focused on financial inclusion for rural populations, women entrepreneurs, and low-income groups in Central Bhutan region.',
    },
    documents: [
      {
        id: 'DOC-RENEW-001',
        documentType: 'RMA Licence',
        documentRef: 'RMA/LIC/005/2014',
        issuedOn: '2014-08-20',
        expiresOn: '2029-08-19',
        remarks: 'Class C microfinance licence with Provisional status. Subject to transition requirements by 2025.',
      },
      {
        id: 'DOC-RENEW-002',
        documentType: 'Certificate of Incorporation',
        documentRef: 'RENEW/COI/2014/001',
        issuedOn: '2014-07-15',
        expiresOn: '',
        remarks: 'Registered as cooperative society under Cooperative Act of Bhutan.',
      },
      {
        id: 'DOC-RENEW-003',
        documentType: 'Audit Report',
        documentRef: 'RENEW/AUDIT/2023/FY',
        issuedOn: '2023-11-20',
        expiresOn: '',
        remarks: 'FY2023 audit by local auditor. Two observations on documentation standards and loan files.',
      },
      {
        id: 'DOC-RENEW-004',
        documentType: 'Financial Statement',
        documentRef: 'RENEW/FS/2023/12',
        issuedOn: '2023-12-31',
        expiresOn: '',
        remarks: 'FY2023 financials showing capital ratio of 18.5%. Small size but adequate reserves.',
      },
      {
        id: 'DOC-RENEW-005',
        documentType: 'AML/CFT Policy',
        documentRef: 'RENEW/AML/2023/10',
        issuedOn: '2023-10-01',
        expiresOn: '',
        remarks: 'Basic AML/CFT policy in place. Compliance monitoring ongoing.',
      },
    ],
    services: [
      {
        id: 'SVC-RENEW-001',
        serviceCategory: 'Microfinance',
        launchDate: '2014-09-15',
        targetSegment: 'Rural entrepreneurs, women groups, low-income households',
        remarks: 'Small loans for agriculture, livestock, home-based business, and income generation activities.',
      },
      {
        id: 'SVC-RENEW-002',
        serviceCategory: 'Retail Banking',
        launchDate: '2014-09-15',
        targetSegment: 'Cooperative members and service beneficiaries',
        remarks: 'Savings products and group lending mechanisms for cooperative members.',
      },
    ],
    validationChecks: [
      {
        key: 'LICENCE_VALIDITY',
        label: 'Licence Validity Check',
        passed: true,
        message: 'RMA Licence RMA/LIC/005/2014 valid until 2029-08-19. Provisional status subject to upgrade requirements.',
      },
      {
        key: 'CAPITAL_ADEQUACY',
        label: 'Capital Adequacy Check',
        passed: true,
        message: 'Capital ratio of 18.5% meets minimum requirement of 15%. Adequate for MFI size.',
      },
      {
        key: 'AML_CFT_COMPLIANCE',
        label: 'AML/CFT Compliance Check',
        passed: true,
        message: 'Basic AML/CFT policy in place. Monitoring framework operational with RMA support.',
      },
      {
        key: 'BOARD_COMPOSITION',
        label: 'Board Composition Check',
        passed: true,
        message: 'Management committee of 5 members comprises cooperative representatives. Training needs identified.',
      },
      {
        key: 'AUDIT_RECENCY',
        label: 'Audit Report Recency Check',
        passed: true,
        message: 'Latest audit dated 2023-11-20 identified minor documentation gaps. Remedial action required by Q2 2024.',
      },
    ],
    approvals: [
      {
        id: 'APR-RENEW-001',
        level: 'RMA Reviewer',
        actor: 'Ms. Pema Yangchen',
        decidedAt: '2024-01-02T11:00:00Z',
        decision: 'Conditionally Approved',
        remarks: 'RMA review notes audit findings. Provisional status contingent on corrective action plan implementation.',
      },
      {
        id: 'APR-RENEW-002',
        level: 'DTA Reviewer',
        actor: 'Mr. Tenzin Wangdi',
        decidedAt: '2024-01-07T09:30:00Z',
        decision: 'Conditionally Approved',
        remarks: 'DTA review supports development impact. Recommend technical assistance for governance strengthening.',
      },
      {
        id: 'APR-RENEW-003',
        level: 'DTA Approver',
        actor: 'Dr. Sonam Tshering',
        decidedAt: '2024-01-11T15:00:00Z',
        decision: 'Conditionally Approved',
        remarks: 'Provisional status continued with development partner support for capacity building.',
      },
    ],
    monitoring: [
      {
        id: 'MON-RENEW-001',
        reviewDate: '2024-01-09',
        monitoringStatus: 'Minor Issues',
        reviewer: 'Ms. Pema Yangchen',
        observations: 'Audit observations being addressed. Documentation standards improving. Loan portfolio quality acceptable at 87%. Technical assistance on governance being provided.',
        rectificationDue: '2024-06-30',
      },
      {
        id: 'MON-RENEW-002',
        reviewDate: '2023-09-10',
        monitoringStatus: 'Minor Issues',
        reviewer: 'Mr. Tenzin Wangdi',
        observations: 'Mid-year findings identified weaknesses in loan documentation and internal controls. Capacity building plan developed with development partners.',
        rectificationDue: '2023-12-31',
      },
    ],
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-11T15:00:00Z',
  },
  {
    id: 'FI-2024-0008',
    header: {
      fiId: 'FI-2024-0008',
      institutionName: 'Bhutan Insurance Ltd',
      legalName: 'Bhutan Insurance Limited',
      institutionType: 'Insurance Company',
      ownershipType: 'Private',
      licenceCategory: 'Class B',
      licenceNumber: 'IRA/LIC/003/2016',
      licenceIssuedOn: '2016-02-10',
      licenceExpiresOn: '2031-02-09',
      regulatoryBody: 'Insurance Regulatory Authority',
      operatingRegion: 'Nationwide',
      headOfficeAddress: 'Gongphel Square, Thimphu, Bhutan',
      contactPerson: 'Mr. Dorji Wangchuk',
      contactEmail: 'contact@bhutaninsurance.com.bt',
      contactPhone: '+975-2-325150',
      reportingCurrency: 'BTN',
      paidUpCapital: '60000000',
      declaredTurnover: '420000000',
      registrationStatus: 'Under Review',
      riskRating: 'High',
      reviewFrequency: 'Quarterly',
      narrative: 'Bhutan Insurance Ltd is a private insurance company offering life and general insurance products. Currently under regulatory review following audit findings regarding solvency and governance concerns.',
    },
    documents: [
      {
        id: 'DOC-BIL-001',
        documentType: 'RMA Licence',
        documentRef: 'IRA/LIC/003/2016',
        issuedOn: '2016-02-10',
        expiresOn: '2031-02-09',
        remarks: 'Composite insurance licence. Currently under review pending regulatory resolution.',
      },
      {
        id: 'DOC-BIL-002',
        documentType: 'Certificate of Incorporation',
        documentRef: 'BIL/COI/2016/001',
        issuedOn: '2016-01-20',
        expiresOn: '',
        remarks: 'Registered as private limited company with Ministry of Economic Affairs.',
      },
      {
        id: 'DOC-BIL-003',
        documentType: 'Audit Report',
        documentRef: 'BIL/AUDIT/2023/FY',
        issuedOn: '2023-12-05',
        expiresOn: '',
        remarks: 'FY2023 audit raised significant concerns regarding solvency margin and reserve adequacy.',
      },
      {
        id: 'DOC-BIL-004',
        documentType: 'Financial Statement',
        documentRef: 'BIL/FS/2023/12',
        issuedOn: '2023-12-31',
        expiresOn: '',
        remarks: 'FY2023 financials show solvency margin of 118%, below IRA minimum of 150%. Rectification required.',
      },
      {
        id: 'DOC-BIL-005',
        documentType: 'Board Resolution',
        documentRef: 'BIL/BR/2023/12',
        issuedOn: '2023-12-20',
        expiresOn: '',
        remarks: 'Board resolution acknowledging regulatory concerns and committing to capital restoration plan.',
      },
    ],
    services: [
      {
        id: 'SVC-BIL-001',
        serviceCategory: 'Insurance — Life',
        launchDate: '2016-03-01',
        targetSegment: 'Individual policyholders, corporate groups',
        remarks: 'Life insurance products including term and endowment. Service expansion temporarily suspended pending regulatory review.',
      },
      {
        id: 'SVC-BIL-002',
        serviceCategory: 'Insurance — General',
        launchDate: '2016-03-01',
        targetSegment: 'Motor, health, and property insurance customers',
        remarks: 'General insurance services currently under operational restrictions due to regulatory oversight.',
      },
    ],
    validationChecks: [
      {
        key: 'LICENCE_VALIDITY',
        label: 'Licence Validity Check',
        passed: false,
        message: 'IRA Composite Licence valid until 2031-02-09. However, institution under regulatory review pending solvency concerns resolution.',
      },
      {
        key: 'CAPITAL_ADEQUACY',
        label: 'Capital Adequacy Check',
        passed: false,
        message: 'Solvency margin of 118% is BELOW IRA minimum of 150%. Critical deficiency requiring immediate capital injection.',
      },
      {
        key: 'AML_CFT_COMPLIANCE',
        label: 'AML/CFT Compliance Check',
        passed: false,
        message: 'AML/CFT policy exists but compliance monitoring identified deficiencies in transaction reporting.',
      },
      {
        key: 'BOARD_COMPOSITION',
        label: 'Board Composition Check',
        passed: false,
        message: 'Board of 5 members lacks insurance expertise. Governance concerns noted in regulatory review.',
      },
      {
        key: 'AUDIT_RECENCY',
        label: 'Audit Report Recency Check',
        passed: false,
        message: 'Latest audit dated 2023-12-05 raised significant findings. Immediate remediation required.',
      },
    ],
    approvals: [
      {
        id: 'APR-BIL-001',
        level: 'RMA Reviewer',
        actor: 'Mr. Phuntsho Dorji',
        decidedAt: '2024-01-04T13:45:00Z',
        decision: 'Returned',
        remarks: 'RMA review identifies critical solvency deficiency. Institution must submit capital restoration plan within 30 days.',
      },
      {
        id: 'APR-BIL-002',
        level: 'DTA Reviewer',
        actor: 'Ms. Kinzang Choden',
        decidedAt: '2024-01-08T10:30:00Z',
        decision: 'Returned',
        remarks: 'DTA review confirms solvency concerns. Recommends regulatory action pending capital plan submission.',
      },
      {
        id: 'APR-BIL-003',
        level: 'DTA Approver',
        actor: 'Mr. Ugyen Dorji',
        decidedAt: '2024-01-10T14:00:00Z',
        decision: 'Returned',
        remarks: 'Status changed to Under Review pending capital restoration plan and governance improvements.',
      },
    ],
    monitoring: [
      {
        id: 'MON-BIL-001',
        reviewDate: '2024-01-08',
        monitoringStatus: 'Major Issues',
        reviewer: 'Mr. Phuntsho Dorji',
        observations: 'Critical solvency deficiency identified. Solvency margin at 118% vs required 150%. Premium income declining. Claims ratio elevated at 72%. Regulatory action in progress.',
        rectificationDue: '2024-03-31',
      },
      {
        id: 'MON-BIL-002',
        reviewDate: '2023-10-15',
        monitoringStatus: 'Major Issues',
        reviewer: 'Ms. Kinzang Choden',
        observations: 'Q3 2023 review identified deteriorating solvency position and governance weaknesses. Interim management oversight initiated. Capital injection planning required.',
        rectificationDue: '2024-01-31',
      },
    ],
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-10T14:00:00Z',
  },
];
