/* Default form state + row factories for ContractorFormModal */
import type { ContractorKind } from '../../../../../shared/types';
import type { BankAccountRow, ContactRow, FormState } from '../../stages/sharedTypes';
import { generateContactId } from '../../stages/sharedTypes';

export function defaultForm(kind: ContractorKind): FormState {
  return {
    contractorId: '',
    contractorType: kind === 'individual' ? 'Individual' : 'Business',
    contractualType: kind === 'business' ? 'Works Contractor' : '',
    category: kind === 'individual' ? 'Individual' : '',
    nationality: 'Bhutanese',
    entryMethod: 'Manual Entry',
    dataSource: 'Manual entry by the Agency',
    registrationDate: new Date().toLocaleString('en-GB'),
    contractorStatusPrimary: 'Active',
    contractorStatusSecondary: '-- Select --',
    statusReason: '',
    isPrimaryContractor: kind === 'individual' ? 'No' : 'Yes',
    salutation: '',
    displayName: '',
    firstName: '',
    middleName: '',
    lastName: '',
    gender: '',
    dateOfBirth: '',
    businessRegistrationDate: '',
    countryOfRegistration: '',
    secondaryName: '',
    registrationNumber: '',
    licenseNumber: '',
    gstNumber: '',
    taxNumber: '',
    email: '',
    phone: '',
    secondaryPhone: '',
    faxNumber: '',
    address: '',
    addressLine2: '',
    addressLine3: '',
    gewog: '',
    dungkhag: '',
    thromde: '',
    district: '',
    cityTown: '',
    stateProvince: '',
    region: '',
    postalCode: '',
    bankName: '',
    bankBranchCode: '',
    bankBranchName: '',
    accountType: '',
    currencyType: 'BTN',
    accountStatus: 'Active',
    accountCategory: '',
    ifscCode: '',
    swiftCode: '',
    bankAccountNumber: '',
    bankAccountName: '',
    contactPerson: '',
    contactRole: '',
    sanctionsCheck: 'Pending verification',
    sanctionCategory: 'Temporary Suspension',
    sanctionType: '',
    sanctionStartDate: '',
    sanctionEndDate: '',
    autoReactivation: 'Yes',
    sanctionReason: '',
    affectedAgency: '',
    sanctioningAgency: '',
    supportingDocuments: '',
    sanctionStatus: 'Active',
    remarks: '',
    workflowNote: '',
  };
}

export function createBankRow(index: number): BankAccountRow {
  return {
    id: `bank-row-${index}`,
    holderName: '',
    accountNumber: '',
    type: '',
    category: '',
    bank: '',
    branch: '',
    branchCode: '',
    currency: 'BTN',
    status: 'Active',
    primary: index === 1 ? 'Yes' : 'No',
    cbsVerified: false,
  };
}

export function createContactRow(kind: "individual" | "business", index: number, contractorId?: string): ContactRow {
  return {
    id: `contact-row-${index}`,
    contactId: generateContactId(kind, contractorId),
    salutation: '',
    firstName: '',
    middleName: '',
    lastName: '',
    nationalId: '',
    gender: '',
    email: '',
    mobileNumber: '',
    landlineNumber: '',
    jobTitle: '',
    isPrimaryContact: index === 1 ? 'Yes' : 'No',
    isIfmisDesignated: 'No',
    isActive: 'Yes',
  };
}
