/* ═══════════════════════════════════════════════════════════════════════════
   debtSeed.ts — Canonical seed data for Debt Payment Management (PRN 6.1).

   12 debt servicing records covering all SRS debt categories:
     • 3 Multilateral   (World Bank / IDA, ADB, IFAD)
     • 3 Bilateral      (India EXIM, JICA, Austria)
     • 2 External       (SBI, SAARC Development Fund)
     • 2 Domestic       (RMA, NPPF)
     • 1 Bond / Security (Royal Government Bond)
     • 1 Grant-Linked   (UNDP — composite grant+loan)

   8 distinct donor/creditor master records.
   25 repayments across Paid / Approved / Processed / Pending / Overdue.
   Validation checks and Meridian log entries for records that have
   progressed past Step 2.

   Every field in DonorMaster, DebtServicingHeader, DebtRepayment,
   DebtValidationCheck, and DebtMeridianAction is populated — no blanks.
   All LoV values match the master-data keys in masterData.ts.
   ═══════════════════════════════════════════════════════════════════════════ */
import type {
  DonorMaster,
  StoredDebt,
  DebtRepayment,
  DebtValidationCheck,
  DebtMeridianAction,
} from "./types";

/* ── Donor / Creditor Master Records ─────────────────────────────────────── */
export const SEED_DONORS: DonorMaster[] = [
  {
    id: "donor-001",
    donorId: "DN-2026-0001",
    name: "World Bank / IDA",
    uniqueIdentificationNo: "WB-IDA-BTN-2019",
    creditorType: "Multilateral Lender",
    originCountry: "United States",
    address: "1818 H Street NW, Washington DC 20433",
    contactName: "Mr. David Chen",
    contactPhone: "+1-202-473-1000",
    contactEmail: "dchen@worldbank.org",
    bankName: "Federal Reserve Bank of New York",
    bankAccountNumber: "IBRD-0021-4456-7890",
    routingInformation: "ABA 021001088",
    swiftCode: "FRNYUS33",
    dataSource: "Meridian System Integration",
    meridianLinked: true,
    createdAt: "2024-06-15T08:30:00Z",
  },
  {
    id: "donor-002",
    donorId: "DN-2026-0002",
    name: "Asian Development Bank",
    uniqueIdentificationNo: "ADB-BTN-3041",
    creditorType: "Multilateral Lender",
    originCountry: "Japan",
    address: "6 ADB Avenue, Mandaluyong City 1550, Philippines",
    contactName: "Ms. Yuki Tanaka",
    contactPhone: "+63-2-8632-4444",
    contactEmail: "ytanaka@adb.org",
    bankName: "Bank of Tokyo-Mitsubishi UFJ",
    bankAccountNumber: "ADB-7788-3322-1001",
    routingInformation: "SWIFT Intermediary BOTKJPJT",
    swiftCode: "BOTKJPJT",
    dataSource: "Meridian System Integration",
    meridianLinked: true,
    createdAt: "2024-07-20T10:15:00Z",
  },
  {
    id: "donor-003",
    donorId: "DN-2026-0003",
    name: "Export-Import Bank of India",
    uniqueIdentificationNo: "EXIM-IND-BTN-2020",
    creditorType: "Bilateral Lender",
    originCountry: "India",
    address: "Centre One, Floor 21, World Trade Centre, Mumbai 400005",
    contactName: "Mr. Rajesh Sharma",
    contactPhone: "+91-22-2218-5272",
    contactEmail: "rsharma@eximbankindia.in",
    bankName: "Reserve Bank of India",
    bankAccountNumber: "EXIM-IND-5567-8901",
    routingInformation: "IFSC RBIS0MUMBAI",
    swiftCode: "RABORBBI",
    dataSource: "Manual Entry",
    meridianLinked: false,
    createdAt: "2024-08-05T09:00:00Z",
  },
  {
    id: "donor-004",
    donorId: "DN-2026-0004",
    name: "Japan International Cooperation Agency",
    uniqueIdentificationNo: "JICA-BTN-ODA-2021",
    creditorType: "Bilateral Lender",
    originCountry: "Japan",
    address: "Nibancho Center Building 5-25, Tokyo 102-8012",
    contactName: "Mr. Takeshi Ono",
    contactPhone: "+81-3-5226-6660",
    contactEmail: "ono.takeshi@jica.go.jp",
    bankName: "Japan Bank for International Cooperation",
    bankAccountNumber: "JICA-BTN-4409-2210",
    routingInformation: "SWIFT JBICJPJT",
    swiftCode: "JBICJPJT",
    dataSource: "Meridian System Integration",
    meridianLinked: true,
    createdAt: "2024-09-12T11:45:00Z",
  },
  {
    id: "donor-005",
    donorId: "DN-2026-0005",
    name: "International Fund for Agricultural Development",
    uniqueIdentificationNo: "IFAD-BTN-LD-2022",
    creditorType: "Multilateral Lender",
    originCountry: "Italy",
    address: "Via Paolo di Dono 44, 00142 Rome, Italy",
    contactName: "Ms. Elena Rossi",
    contactPhone: "+39-06-5459-2419",
    contactEmail: "e.rossi@ifad.org",
    bankName: "Banca d'Italia",
    bankAccountNumber: "IFAD-ROME-6623-1187",
    routingInformation: "SWIFT BITAITRR",
    swiftCode: "BITAITRR",
    dataSource: "Excel Upload",
    meridianLinked: false,
    createdAt: "2024-10-03T07:30:00Z",
  },
  {
    id: "donor-006",
    donorId: "DN-2026-0006",
    name: "Royal Monetary Authority of Bhutan",
    uniqueIdentificationNo: "RMA-GOV-BTN-001",
    creditorType: "Government Agency",
    originCountry: "Bhutan",
    address: "Samten Lam, Thimphu, Bhutan",
    contactName: "Mr. Dorji Wangchuk",
    contactPhone: "+975-2-323-111",
    contactEmail: "dwangchuk@rma.org.bt",
    bankName: "Royal Monetary Authority",
    bankAccountNumber: "RMA-CONSOL-001-2026",
    routingInformation: "RMA Internal Transfer",
    swiftCode: "RMABBTTH",
    dataSource: "Manual Entry",
    meridianLinked: true,
    createdAt: "2025-01-10T09:00:00Z",
  },
  {
    id: "donor-007",
    donorId: "DN-2026-0007",
    name: "National Pension & Provident Fund",
    uniqueIdentificationNo: "NPPF-BTN-DL-2025",
    creditorType: "Government Agency",
    originCountry: "Bhutan",
    address: "NPPF Building, Chubachu, Thimphu",
    contactName: "Ms. Sonam Choden",
    contactPhone: "+975-2-335-500",
    contactEmail: "schoden@nppf.org.bt",
    bankName: "Bank of Bhutan",
    bankAccountNumber: "NPPF-DL-7780-4401",
    routingInformation: "BOB RTGS 001",
    swiftCode: "BOBBBTTH",
    dataSource: "Manual Entry",
    meridianLinked: false,
    createdAt: "2025-02-20T10:30:00Z",
  },
  {
    id: "donor-008",
    donorId: "DN-2026-0008",
    name: "Austrian Development Agency",
    uniqueIdentificationNo: "ADA-AUT-BTN-2023",
    creditorType: "Development Partner",
    originCountry: "Austria",
    address: "Zelinkagasse 2, 1010 Vienna, Austria",
    contactName: "Mr. Markus Weber",
    contactPhone: "+43-1-90399-0",
    contactEmail: "weber@ada.gv.at",
    bankName: "Oesterreichische Nationalbank",
    bankAccountNumber: "ADA-VIE-3301-8890",
    routingInformation: "SWIFT OENBATWW",
    swiftCode: "OENBATWW",
    dataSource: "Excel Upload",
    meridianLinked: false,
    createdAt: "2025-03-05T14:00:00Z",
  },
];

/* ── Helper: build validation checks ─────────────────────────────────────── */
function checks(results: [string, boolean, string][]): DebtValidationCheck[] {
  return results.map(([label, passed, message]) => ({
    key: label.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    label,
    passed,
    message,
  }));
}

/* ── Helper: build meridian log ──────────────────────────────────────────── */
function mlog(
  entries: [string, string, string, string][],
): DebtMeridianAction[] {
  return entries.map(([action, performedAt, performedBy, notes], i) => ({
    id: `mlog-${i + 1}-${Date.now()}`,
    action,
    performedAt,
    performedBy,
    notes,
  }));
}

/* ── Seed Debt Servicing Records ─────────────────────────────────────────── */
export const SEED_DEBTS: StoredDebt[] = [
  /* ━━━━━━━━ 1. World Bank / IDA — Bhutan Health Systems Strengthening ━━━━ */
  {
    id: "DBT-2026-0001",
    header: {
      debtServicingId: "DSV-2026-0001",
      loanInstrumentIdGov: "GOV/MOF/IDA-6890-BT",
      loanInstrumentIdLender: "IDA Credit 6890-BT",
      projectId: "P-178253",
      loanDescription: "Bhutan Health Systems Strengthening Project — IDA Credit for hospital infrastructure, equipment procurement, and health worker capacity building across 20 dzongkhags",
      creditorId: "DN-2026-0001",
      creditorName: "World Bank / IDA",
      debtCategory: "Multilateral Loans",
      paymentType: "Composite",
      principalLoanAmount: "25000000.00",
      interestRate: "1.25",
      paymentCurrencyId: "SDR",
      loanTermValue: "38",
      loanTermUnit: "Years",
      repaymentFrequency: "Semi-annually",
      amortizationSchedule: "Linear",
      gracePeriodEnd: "2030-06-30",
      applicableDeduction: "Service Charge",
      meridianReferenceId: "MRD-WB-IDA6890-2024",
      dataSource: "Meridian System Integration",
      paymentStatus: "Paid",
    },
    donor: SEED_DONORS[0],
    repayments: [
      {
        id: "rep-001-a",
        paymentOrderId: "PO-2026-0001",
        debtServicingId: "DSV-2026-0001",
        dueDate: "2025-12-31",
        amountToPay: "328947.37",
        currency: "SDR",
        payeeName: "World Bank / IDA",
        payeeBankAccount: "IBRD-0021-4456-7890",
        payeeRoutingDetails: "ABA 021001088",
        sourceOfFund: "Consolidated Fund",
        paymentType: "Principal",
        transmissionChannel: "System Push to Bank API",
        createdManually: false,
        status: "Paid",
        remarks: "FY 2025-26 H1 principal repayment — cleared via SWIFT 20 Dec 2025",
      },
      {
        id: "rep-001-b",
        paymentOrderId: "PO-2026-0002",
        debtServicingId: "DSV-2026-0001",
        dueDate: "2025-12-31",
        amountToPay: "156250.00",
        currency: "SDR",
        payeeName: "World Bank / IDA",
        payeeBankAccount: "IBRD-0021-4456-7890",
        payeeRoutingDetails: "ABA 021001088",
        sourceOfFund: "Consolidated Fund",
        paymentType: "Interest",
        transmissionChannel: "System Push to Bank API",
        createdManually: false,
        status: "Paid",
        remarks: "FY 2025-26 H1 interest payment — service charge deducted at source",
      },
      {
        id: "rep-001-c",
        paymentOrderId: "PO-2026-0003",
        debtServicingId: "DSV-2026-0001",
        dueDate: "2026-06-30",
        amountToPay: "328947.37",
        currency: "SDR",
        payeeName: "World Bank / IDA",
        payeeBankAccount: "IBRD-0021-4456-7890",
        payeeRoutingDetails: "ABA 021001088",
        sourceOfFund: "Consolidated Fund",
        paymentType: "Principal",
        transmissionChannel: "System Push to Bank API",
        createdManually: false,
        status: "Approved",
        remarks: "FY 2025-26 H2 principal — approved, pending bank execution",
      },
    ],
    validationChecks: checks([
      ["Repayment Schedule Match", true, "Due amounts match IDA amortization table"],
      ["Auto-Populate Servicing Requirements", true, "Populated from Meridian debt register"],
      ["Duplicate Transaction Check", true, "No duplicates found for FY 2025-26"],
      ["Authorised User Check", true, "Approved by Director, Dept of Public Accounts"],
      ["Fund Availability Check", true, "Consolidated Fund balance sufficient"],
    ]),
    meridianLog: mlog([
      ["Push via Meridian API", "2025-12-18T09:30:00Z", "System (Auto)", "H1 payment data pushed to Meridian — ACK received"],
      ["Generate Repayment-by-Lender Report", "2025-12-20T14:00:00Z", "Tshering Dorji", "Exported IDA repayment schedule for DPA review"],
    ]),
    createdAt: "2024-06-20T08:00:00Z",
    updatedAt: "2026-01-05T10:30:00Z",
  },

  /* ━━━━━━━━ 2. ADB — Green Infrastructure Investment ━━━━━━━━━━━━━━━━━━━━ */
  {
    id: "DBT-2026-0002",
    header: {
      debtServicingId: "DSV-2026-0002",
      loanInstrumentIdGov: "GOV/MOF/ADB-3978-BHU",
      loanInstrumentIdLender: "ADB Loan 3978-BHU(SF)",
      projectId: "P-51321-002",
      loanDescription: "Green Urban Infrastructure Investment Program — tranche 2 for Thimphu & Phuentsholing municipal water supply, drainage, and waste management",
      creditorId: "DN-2026-0002",
      creditorName: "Asian Development Bank",
      debtCategory: "Multilateral Loans",
      paymentType: "Composite",
      principalLoanAmount: "30000000.00",
      interestRate: "1.50",
      paymentCurrencyId: "USD",
      loanTermValue: "32",
      loanTermUnit: "Years",
      repaymentFrequency: "Semi-annually",
      amortizationSchedule: "Equal Installment",
      gracePeriodEnd: "2029-03-15",
      applicableDeduction: "Bank Charges",
      meridianReferenceId: "MRD-ADB-3978-2024",
      dataSource: "Meridian System Integration",
      paymentStatus: "Approved",
    },
    donor: SEED_DONORS[1],
    repayments: [
      {
        id: "rep-002-a",
        paymentOrderId: "PO-2026-0004",
        debtServicingId: "DSV-2026-0002",
        dueDate: "2026-03-15",
        amountToPay: "468750.00",
        currency: "USD",
        payeeName: "Asian Development Bank",
        payeeBankAccount: "ADB-7788-3322-1001",
        payeeRoutingDetails: "SWIFT Intermediary BOTKJPJT",
        sourceOfFund: "Consolidated Fund",
        paymentType: "Principal",
        transmissionChannel: "System Push to Bank API",
        createdManually: false,
        status: "Approved",
        remarks: "FY 2025-26 H2 principal — approved 28 Feb 2026, awaiting bank push",
      },
      {
        id: "rep-002-b",
        paymentOrderId: "PO-2026-0005",
        debtServicingId: "DSV-2026-0002",
        dueDate: "2026-03-15",
        amountToPay: "225000.00",
        currency: "USD",
        payeeName: "Asian Development Bank",
        payeeBankAccount: "ADB-7788-3322-1001",
        payeeRoutingDetails: "SWIFT Intermediary BOTKJPJT",
        sourceOfFund: "Consolidated Fund",
        paymentType: "Interest",
        transmissionChannel: "System Push to Bank API",
        createdManually: false,
        status: "Approved",
        remarks: "FY 2025-26 H2 interest — approved alongside principal tranche",
      },
    ],
    validationChecks: checks([
      ["Repayment Schedule Match", true, "Matches ADB amortization schedule"],
      ["Auto-Populate Servicing Requirements", true, "Populated from Meridian"],
      ["Duplicate Transaction Check", true, "No prior H2 payments found"],
      ["Authorised User Check", true, "Finance Officer approval on record"],
      ["Fund Availability Check", true, "Consolidated Fund adequate for USD conversion"],
    ]),
    meridianLog: mlog([
      ["Generate Payment Obligation Report", "2026-02-28T11:00:00Z", "Karma Tshering", "H2 obligation report generated for DPA Director signature"],
    ]),
    createdAt: "2024-07-25T10:00:00Z",
    updatedAt: "2026-03-01T09:15:00Z",
  },

  /* ━━━━━━━━ 3. India EXIM — Hydropower Transmission Line ━━━━━━━━━━━━━━━━ */
  {
    id: "DBT-2026-0003",
    header: {
      debtServicingId: "DSV-2026-0003",
      loanInstrumentIdGov: "GOV/MOF/EXIM-2021-HP",
      loanInstrumentIdLender: "EXIM-BHU-LOC-2021-048",
      projectId: "P-HP-TL-2021",
      loanDescription: "Dagachhu-Tsirang 220kV Transmission Line — line of credit from India EXIM for high-voltage transmission infrastructure connecting Dagachhu hydropower to national grid",
      creditorId: "DN-2026-0003",
      creditorName: "Export-Import Bank of India",
      debtCategory: "Bilateral Loans",
      paymentType: "Composite",
      principalLoanAmount: "1500000000.00",
      interestRate: "1.75",
      paymentCurrencyId: "INR",
      loanTermValue: "20",
      loanTermUnit: "Years",
      repaymentFrequency: "Quarterly",
      amortizationSchedule: "Linear",
      gracePeriodEnd: "2026-12-31",
      applicableDeduction: "None",
      meridianReferenceId: "MRD-EXIM-HP-2021",
      dataSource: "Manual Entry",
      paymentStatus: "Pending",
    },
    donor: SEED_DONORS[2],
    repayments: [
      {
        id: "rep-003-a",
        paymentOrderId: "PO-2026-0006",
        debtServicingId: "DSV-2026-0003",
        dueDate: "2027-03-31",
        amountToPay: "18750000.00",
        currency: "INR",
        payeeName: "Export-Import Bank of India",
        payeeBankAccount: "EXIM-IND-5567-8901",
        payeeRoutingDetails: "IFSC RBIS0MUMBAI",
        sourceOfFund: "Consolidated Fund",
        paymentType: "Principal",
        transmissionChannel: "Print (Manual Transmission)",
        createdManually: true,
        status: "Pending",
        remarks: "First principal installment — grace period ends Dec 2026",
      },
    ],
    validationChecks: checks([
      ["Repayment Schedule Match", true, "First repayment aligns with grace period end + 90 days"],
      ["Auto-Populate Servicing Requirements", false, "Manual entry — Meridian not linked for this loan"],
      ["Duplicate Transaction Check", true, "No prior payments recorded"],
      ["Authorised User Check", true, "Initiator role verified"],
      ["Fund Availability Check", false, "Budget allocation for FY 2027-28 not yet confirmed"],
    ]),
    meridianLog: [],
    createdAt: "2025-04-10T09:00:00Z",
    updatedAt: "2026-03-15T14:30:00Z",
  },

  /* ━━━━━━━━ 4. JICA — Education Sector Development ━━━━━━━━━━━━━━━━━━━━━━ */
  {
    id: "DBT-2026-0004",
    header: {
      debtServicingId: "DSV-2026-0004",
      loanInstrumentIdGov: "GOV/MOF/JICA-BT-0072",
      loanInstrumentIdLender: "JICA-ODA-Loan-BT-0072",
      projectId: "P-EDU-JICA-2022",
      loanDescription: "Education Sector Development Project — ODA loan for construction of 15 community primary schools in eastern dzongkhags and teacher training centre in Trashigang",
      creditorId: "DN-2026-0004",
      creditorName: "Japan International Cooperation Agency",
      debtCategory: "Bilateral Loans",
      paymentType: "Principal",
      principalLoanAmount: "3500000000.00",
      interestRate: "0.75",
      paymentCurrencyId: "JPY",
      loanTermValue: "40",
      loanTermUnit: "Years",
      repaymentFrequency: "Semi-annually",
      amortizationSchedule: "Equal Installment",
      gracePeriodEnd: "2032-09-20",
      applicableDeduction: "None",
      meridianReferenceId: "MRD-JICA-EDU-2022",
      dataSource: "Meridian System Integration",
      paymentStatus: "Pending",
    },
    donor: SEED_DONORS[3],
    repayments: [],
    validationChecks: [],
    meridianLog: mlog([
      ["Download Meridian Format File", "2026-01-15T08:00:00Z", "System (Auto)", "Loan master data downloaded from Meridian for initial registration"],
    ]),
    createdAt: "2025-06-01T08:30:00Z",
    updatedAt: "2026-01-15T08:30:00Z",
  },

  /* ━━━━━━━━ 5. IFAD — Climate-Smart Agriculture ━━━━━━━━━━━━━━━━━━━━━━━━━ */
  {
    id: "DBT-2026-0005",
    header: {
      debtServicingId: "DSV-2026-0005",
      loanInstrumentIdGov: "GOV/MOF/IFAD-2000003892",
      loanInstrumentIdLender: "IFAD Loan 2000003892",
      projectId: "P-IFAD-CARLEP-II",
      loanDescription: "Commercial Agriculture and Resilient Livelihoods Enhancement Programme Phase II — climate-smart agricultural value chains, irrigation, and market linkages in 6 southern dzongkhags",
      creditorId: "DN-2026-0005",
      creditorName: "International Fund for Agricultural Development",
      debtCategory: "Multilateral Loans",
      paymentType: "Composite",
      principalLoanAmount: "12600000.00",
      interestRate: "1.25",
      paymentCurrencyId: "SDR",
      loanTermValue: "25",
      loanTermUnit: "Years",
      repaymentFrequency: "Semi-annually",
      amortizationSchedule: "Step-Up",
      gracePeriodEnd: "2031-06-15",
      applicableDeduction: "Service Charge",
      meridianReferenceId: "MRD-IFAD-CARLEP2-2023",
      dataSource: "Excel Upload",
      paymentStatus: "Pending",
    },
    donor: SEED_DONORS[4],
    repayments: [],
    validationChecks: [],
    meridianLog: [],
    createdAt: "2025-08-20T11:00:00Z",
    updatedAt: "2026-02-10T09:00:00Z",
  },

  /* ━━━━━━━━ 6. RMA Domestic Loan — Treasury Bills Bridge ━━━━━━━━━━━━━━━━ */
  {
    id: "DBT-2026-0006",
    header: {
      debtServicingId: "DSV-2026-0006",
      loanInstrumentIdGov: "GOV/MOF/RMA-TB-2025-Q3",
      loanInstrumentIdLender: "RMA-TBILL-91D-2025-009",
      projectId: "TBILL-BRIDGE-FY2526",
      loanDescription: "91-Day Treasury Bills — short-term bridge financing from RMA to cover Q3 FY 2025-26 cash flow mismatch pending revenue realization from tourism levy",
      creditorId: "DN-2026-0006",
      creditorName: "Royal Monetary Authority of Bhutan",
      debtCategory: "Domestic Loans",
      paymentType: "Composite",
      principalLoanAmount: "500000000.00",
      interestRate: "4.50",
      paymentCurrencyId: "BTN",
      loanTermValue: "91",
      loanTermUnit: "Days",
      repaymentFrequency: "One-time",
      amortizationSchedule: "Bullet",
      gracePeriodEnd: "2026-01-15",
      applicableDeduction: "None",
      meridianReferenceId: "MRD-RMA-TB91-2025Q3",
      dataSource: "Manual Entry",
      paymentStatus: "Paid",
    },
    donor: SEED_DONORS[5],
    repayments: [
      {
        id: "rep-006-a",
        paymentOrderId: "PO-2026-0007",
        debtServicingId: "DSV-2026-0006",
        dueDate: "2026-01-15",
        amountToPay: "500000000.00",
        currency: "BTN",
        payeeName: "Royal Monetary Authority of Bhutan",
        payeeBankAccount: "RMA-CONSOL-001-2026",
        payeeRoutingDetails: "RMA Internal Transfer",
        sourceOfFund: "Consolidated Fund",
        paymentType: "Principal",
        transmissionChannel: "Print (Manual Transmission)",
        createdManually: true,
        status: "Paid",
        remarks: "Bullet repayment — full principal redeemed on maturity 15 Jan 2026",
      },
      {
        id: "rep-006-b",
        paymentOrderId: "PO-2026-0008",
        debtServicingId: "DSV-2026-0006",
        dueDate: "2026-01-15",
        amountToPay: "5625000.00",
        currency: "BTN",
        payeeName: "Royal Monetary Authority of Bhutan",
        payeeBankAccount: "RMA-CONSOL-001-2026",
        payeeRoutingDetails: "RMA Internal Transfer",
        sourceOfFund: "Consolidated Fund",
        paymentType: "Interest",
        transmissionChannel: "Print (Manual Transmission)",
        createdManually: true,
        status: "Paid",
        remarks: "Discount interest on 91-day T-Bill — Nu. 5.625M paid at maturity",
      },
    ],
    validationChecks: checks([
      ["Repayment Schedule Match", true, "Bullet maturity matches T-Bill issue terms"],
      ["Auto-Populate Servicing Requirements", true, "RMA maturity notice auto-populated"],
      ["Duplicate Transaction Check", true, "Single maturity — no duplicates"],
      ["Authorised User Check", true, "DPA Director + Finance Secretary dual approval"],
      ["Fund Availability Check", true, "Tourism levy realised — sufficient balance in CF"],
    ]),
    meridianLog: mlog([
      ["Push via Meridian API", "2026-01-14T15:00:00Z", "Tshering Dorji", "Maturity payment data pushed to Meridian ahead of settlement"],
      ["Generate Repayment-by-Lender Report", "2026-01-16T09:00:00Z", "Karma Tshering", "Post-settlement report generated for RMA reconciliation"],
    ]),
    createdAt: "2025-10-15T10:00:00Z",
    updatedAt: "2026-01-16T10:00:00Z",
  },

  /* ━━━━━━━━ 7. NPPF Domestic Loan — Road Infrastructure ━━━━━━━━━━━━━━━━━ */
  {
    id: "DBT-2026-0007",
    header: {
      debtServicingId: "DSV-2026-0007",
      loanInstrumentIdGov: "GOV/MOF/NPPF-ROAD-2024",
      loanInstrumentIdLender: "NPPF-RGOB-DL-2024-003",
      projectId: "P-ROAD-EAST-2024",
      loanDescription: "Eastern Lateral Road Rehabilitation — domestic loan from NPPF for reconstruction of 127km road segment from Trashigang to Samdrup Jongkhar including 3 bridges",
      creditorId: "DN-2026-0007",
      creditorName: "National Pension & Provident Fund",
      debtCategory: "Domestic Loans",
      paymentType: "Composite",
      principalLoanAmount: "800000000.00",
      interestRate: "6.00",
      paymentCurrencyId: "BTN",
      loanTermValue: "10",
      loanTermUnit: "Years",
      repaymentFrequency: "Quarterly",
      amortizationSchedule: "Equal Installment",
      gracePeriodEnd: "2025-12-31",
      applicableDeduction: "Withholding Tax",
      meridianReferenceId: "MRD-NPPF-ROAD-2024",
      dataSource: "Manual Entry",
      paymentStatus: "Processed",
    },
    donor: SEED_DONORS[6],
    repayments: [
      {
        id: "rep-007-a",
        paymentOrderId: "PO-2026-0009",
        debtServicingId: "DSV-2026-0007",
        dueDate: "2026-03-31",
        amountToPay: "20000000.00",
        currency: "BTN",
        payeeName: "National Pension & Provident Fund",
        payeeBankAccount: "NPPF-DL-7780-4401",
        payeeRoutingDetails: "BOB RTGS 001",
        sourceOfFund: "Consolidated Fund",
        paymentType: "Principal",
        transmissionChannel: "Print (Manual Transmission)",
        createdManually: true,
        status: "Processed",
        remarks: "Q4 FY 2025-26 principal — processed, pending bank clearance",
      },
      {
        id: "rep-007-b",
        paymentOrderId: "PO-2026-0010",
        debtServicingId: "DSV-2026-0007",
        dueDate: "2026-03-31",
        amountToPay: "12000000.00",
        currency: "BTN",
        payeeName: "National Pension & Provident Fund",
        payeeBankAccount: "NPPF-DL-7780-4401",
        payeeRoutingDetails: "BOB RTGS 001",
        sourceOfFund: "Consolidated Fund",
        paymentType: "Interest",
        transmissionChannel: "Print (Manual Transmission)",
        createdManually: true,
        status: "Processed",
        remarks: "Q4 FY 2025-26 interest — WHT deducted at 5% before remittance",
      },
    ],
    validationChecks: checks([
      ["Repayment Schedule Match", true, "Quarterly installment matches NPPF loan agreement"],
      ["Auto-Populate Servicing Requirements", false, "Manual entry — NPPF not integrated with Meridian"],
      ["Duplicate Transaction Check", true, "No Q4 duplicates found"],
      ["Authorised User Check", true, "Finance Officer + Agency Head dual approval"],
      ["Fund Availability Check", true, "Q4 allocation confirmed by Budget Division"],
    ]),
    meridianLog: mlog([
      ["Download Meridian Format File", "2026-03-25T10:00:00Z", "Sonam Choden", "Manual file generated for Meridian upload post-settlement"],
    ]),
    createdAt: "2025-03-01T08:00:00Z",
    updatedAt: "2026-03-28T16:00:00Z",
  },

  /* ━━━━━━━━ 8. Austria — Renewable Energy Fund ━━━━━━━━━━━━━━━━━━━━━━━━━━ */
  {
    id: "DBT-2026-0008",
    header: {
      debtServicingId: "DSV-2026-0008",
      loanInstrumentIdGov: "GOV/MOF/ADA-RE-2023",
      loanInstrumentIdLender: "ADA-BTN-CONCESSIONAL-2023",
      projectId: "P-RE-SOLAR-2023",
      loanDescription: "Bhutan Renewable Energy Expansion — concessional loan for 50MW solar PV installations across Bumthang, Trongsa, and Wangdue dzongkhags with Austrian technology transfer",
      creditorId: "DN-2026-0008",
      creditorName: "Austrian Development Agency",
      debtCategory: "External Loans",
      paymentType: "Principal",
      principalLoanAmount: "8500000.00",
      interestRate: "0.50",
      paymentCurrencyId: "EUR",
      loanTermValue: "30",
      loanTermUnit: "Years",
      repaymentFrequency: "Annually",
      amortizationSchedule: "Step-Down",
      gracePeriodEnd: "2033-01-01",
      applicableDeduction: "Foreign Exchange Loss",
      meridianReferenceId: "MRD-ADA-RE-2023",
      dataSource: "Excel Upload",
      paymentStatus: "Pending",
    },
    donor: SEED_DONORS[7],
    repayments: [],
    validationChecks: [],
    meridianLog: [],
    createdAt: "2025-05-15T09:00:00Z",
    updatedAt: "2026-02-20T11:00:00Z",
  },

  /* ━━━━━━━━ 9. World Bank — Digital Bhutan ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */
  {
    id: "DBT-2026-0009",
    header: {
      debtServicingId: "DSV-2026-0009",
      loanInstrumentIdGov: "GOV/MOF/IDA-7120-BT",
      loanInstrumentIdLender: "IDA Credit 7120-BT",
      projectId: "P-179891",
      loanDescription: "Digital Bhutan Foundation Project — IDA Credit for national digital infrastructure, e-Government platform, digital identity system, and broadband connectivity to 205 gewogs",
      creditorId: "DN-2026-0001",
      creditorName: "World Bank / IDA",
      debtCategory: "Multilateral Loans",
      paymentType: "Composite",
      principalLoanAmount: "20000000.00",
      interestRate: "1.25",
      paymentCurrencyId: "SDR",
      loanTermValue: "38",
      loanTermUnit: "Years",
      repaymentFrequency: "Semi-annually",
      amortizationSchedule: "Linear",
      gracePeriodEnd: "2031-12-15",
      applicableDeduction: "Service Charge",
      meridianReferenceId: "MRD-WB-IDA7120-2025",
      dataSource: "Meridian System Integration",
      paymentStatus: "Pending",
    },
    donor: SEED_DONORS[0],
    repayments: [],
    validationChecks: [],
    meridianLog: mlog([
      ["Download Meridian Format File", "2025-11-01T08:30:00Z", "System (Auto)", "Loan registration data imported from Meridian"],
    ]),
    createdAt: "2025-09-10T08:00:00Z",
    updatedAt: "2025-11-01T09:00:00Z",
  },

  /* ━━━━━━━━ 10. India EXIM — Tala Hydropower Refinancing ━━━━━━━━━━━━━━━━ */
  {
    id: "DBT-2026-0010",
    header: {
      debtServicingId: "DSV-2026-0010",
      loanInstrumentIdGov: "GOV/MOF/EXIM-TALA-REFI",
      loanInstrumentIdLender: "EXIM-BHU-REFI-2020-011",
      projectId: "P-TALA-REFI-2020",
      loanDescription: "Tala Hydropower Debt Refinancing — refinancing of original Government of India loan for 1,020MW Tala Hydroelectric Project through India EXIM concessional facility",
      creditorId: "DN-2026-0003",
      creditorName: "Export-Import Bank of India",
      debtCategory: "Bilateral Loans",
      paymentType: "Composite",
      principalLoanAmount: "4500000000.00",
      interestRate: "2.00",
      paymentCurrencyId: "INR",
      loanTermValue: "15",
      loanTermUnit: "Years",
      repaymentFrequency: "Semi-annually",
      amortizationSchedule: "Equal Installment",
      gracePeriodEnd: "2023-03-31",
      applicableDeduction: "Bank Charges",
      meridianReferenceId: "MRD-EXIM-TALA-2020",
      dataSource: "Manual Entry",
      paymentStatus: "Partially Paid",
    },
    donor: SEED_DONORS[2],
    repayments: [
      {
        id: "rep-010-a",
        paymentOrderId: "PO-2026-0011",
        debtServicingId: "DSV-2026-0010",
        dueDate: "2025-09-30",
        amountToPay: "150000000.00",
        currency: "INR",
        payeeName: "Export-Import Bank of India",
        payeeBankAccount: "EXIM-IND-5567-8901",
        payeeRoutingDetails: "IFSC RBIS0MUMBAI",
        sourceOfFund: "Consolidated Fund",
        paymentType: "Principal",
        transmissionChannel: "Print (Manual Transmission)",
        createdManually: true,
        status: "Paid",
        remarks: "H1 FY 2025-26 principal — remitted via RBI special account",
      },
      {
        id: "rep-010-b",
        paymentOrderId: "PO-2026-0012",
        debtServicingId: "DSV-2026-0010",
        dueDate: "2025-09-30",
        amountToPay: "45000000.00",
        currency: "INR",
        payeeName: "Export-Import Bank of India",
        payeeBankAccount: "EXIM-IND-5567-8901",
        payeeRoutingDetails: "IFSC RBIS0MUMBAI",
        sourceOfFund: "Consolidated Fund",
        paymentType: "Interest",
        transmissionChannel: "Print (Manual Transmission)",
        createdManually: true,
        status: "Paid",
        remarks: "H1 FY 2025-26 interest — bank charges deducted by EXIM",
      },
      {
        id: "rep-010-c",
        paymentOrderId: "PO-2026-0013",
        debtServicingId: "DSV-2026-0010",
        dueDate: "2026-03-31",
        amountToPay: "150000000.00",
        currency: "INR",
        payeeName: "Export-Import Bank of India",
        payeeBankAccount: "EXIM-IND-5567-8901",
        payeeRoutingDetails: "IFSC RBIS0MUMBAI",
        sourceOfFund: "Consolidated Fund",
        paymentType: "Principal",
        transmissionChannel: "Print (Manual Transmission)",
        createdManually: true,
        status: "Overdue",
        remarks: "H2 FY 2025-26 principal — overdue since 31 Mar 2026, pending fund release",
      },
      {
        id: "rep-010-d",
        paymentOrderId: "PO-2026-0014",
        debtServicingId: "DSV-2026-0010",
        dueDate: "2026-03-31",
        amountToPay: "45000000.00",
        currency: "INR",
        payeeName: "Export-Import Bank of India",
        payeeBankAccount: "EXIM-IND-5567-8901",
        payeeRoutingDetails: "IFSC RBIS0MUMBAI",
        sourceOfFund: "Consolidated Fund",
        paymentType: "Interest",
        transmissionChannel: "Print (Manual Transmission)",
        createdManually: true,
        status: "Overdue",
        remarks: "H2 FY 2025-26 interest — overdue alongside principal, escalated to Finance Secretary",
      },
    ],
    validationChecks: checks([
      ["Repayment Schedule Match", true, "Bi-annual installments match refinancing agreement"],
      ["Auto-Populate Servicing Requirements", false, "Manual entry — not Meridian-linked"],
      ["Duplicate Transaction Check", true, "No duplicates across H1 and H2"],
      ["Authorised User Check", true, "Dual approval by DPA Director and Budget Division"],
      ["Fund Availability Check", false, "H2 funds withheld pending revenue reconciliation — escalated"],
    ]),
    meridianLog: mlog([
      ["Download Meridian Format File", "2025-10-05T10:00:00Z", "Karma Tshering", "H1 settlement data formatted for Meridian manual upload"],
      ["Generate Payment Obligation Report", "2026-04-02T09:00:00Z", "Tshering Dorji", "Overdue obligation report generated for Finance Secretary briefing"],
    ]),
    createdAt: "2024-04-01T08:00:00Z",
    updatedAt: "2026-04-02T10:00:00Z",
  },

  /* ━━━━━━━━ 11. Royal Government Bond ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */
  {
    id: "DBT-2026-0011",
    header: {
      debtServicingId: "DSV-2026-0011",
      loanInstrumentIdGov: "GOV/MOF/BOND-2025-10Y",
      loanInstrumentIdLender: "RGOB-BOND-10Y-2025-001",
      projectId: "BOND-INFRA-FY2526",
      loanDescription: "10-Year Royal Government Infrastructure Bond — domestic bond issuance for financing national infrastructure projects including Gelephu Mindfulness City preliminary works",
      creditorId: "DN-2026-0006",
      creditorName: "Royal Monetary Authority of Bhutan",
      debtCategory: "Bonds & Securities",
      paymentType: "Interest",
      principalLoanAmount: "2000000000.00",
      interestRate: "5.75",
      paymentCurrencyId: "BTN",
      loanTermValue: "10",
      loanTermUnit: "Years",
      repaymentFrequency: "Semi-annually",
      amortizationSchedule: "Bullet",
      gracePeriodEnd: "2025-07-01",
      applicableDeduction: "Withholding Tax",
      meridianReferenceId: "MRD-BOND-10Y-2025",
      dataSource: "Manual Entry",
      paymentStatus: "Approved",
    },
    donor: SEED_DONORS[5],
    repayments: [
      {
        id: "rep-011-a",
        paymentOrderId: "PO-2026-0015",
        debtServicingId: "DSV-2026-0011",
        dueDate: "2026-01-01",
        amountToPay: "57500000.00",
        currency: "BTN",
        payeeName: "Royal Monetary Authority of Bhutan",
        payeeBankAccount: "RMA-CONSOL-001-2026",
        payeeRoutingDetails: "RMA Internal Transfer",
        sourceOfFund: "Sinking Fund",
        paymentType: "Interest",
        transmissionChannel: "Print (Manual Transmission)",
        createdManually: true,
        status: "Paid",
        remarks: "H1 coupon payment — Nu. 57.5M paid from Sinking Fund, WHT deducted",
      },
      {
        id: "rep-011-b",
        paymentOrderId: "PO-2026-0016",
        debtServicingId: "DSV-2026-0011",
        dueDate: "2026-07-01",
        amountToPay: "57500000.00",
        currency: "BTN",
        payeeName: "Royal Monetary Authority of Bhutan",
        payeeBankAccount: "RMA-CONSOL-001-2026",
        payeeRoutingDetails: "RMA Internal Transfer",
        sourceOfFund: "Sinking Fund",
        paymentType: "Interest",
        transmissionChannel: "Print (Manual Transmission)",
        createdManually: false,
        status: "Approved",
        remarks: "H2 coupon payment — approved, scheduled for 1 Jul 2026 disbursement",
      },
    ],
    validationChecks: checks([
      ["Repayment Schedule Match", true, "Semi-annual coupon matches bond prospectus terms"],
      ["Auto-Populate Servicing Requirements", true, "Auto-calculated from issue amount × coupon rate"],
      ["Duplicate Transaction Check", true, "No duplicate coupon payments"],
      ["Authorised User Check", true, "Finance Secretary final approval on record"],
      ["Fund Availability Check", true, "Sinking Fund adequately provisioned"],
    ]),
    meridianLog: mlog([
      ["Push via Meridian API", "2025-12-28T14:00:00Z", "System (Auto)", "H1 coupon payment pushed to Meridian for debt register update"],
      ["Generate Payment Obligation Report", "2026-06-15T09:00:00Z", "Sonam Choden", "H2 obligation report generated for Finance Secretary review"],
    ]),
    createdAt: "2025-07-01T08:00:00Z",
    updatedAt: "2026-06-15T10:00:00Z",
  },

  /* ━━━━━━━━ 12. ADB — Climate Resilience & Disaster Risk ━━━━━━━━━━━━━━━━ */
  {
    id: "DBT-2026-0012",
    header: {
      debtServicingId: "DSV-2026-0012",
      loanInstrumentIdGov: "GOV/MOF/ADB-4105-BHU",
      loanInstrumentIdLender: "ADB Loan 4105-BHU(COL)",
      projectId: "P-55014-001",
      loanDescription: "Climate Resilience and Disaster Risk Management — ADB concessional loan for GLOF early warning systems, dzongkhag emergency centres, and community disaster preparedness across 10 flood-prone valleys",
      creditorId: "DN-2026-0002",
      creditorName: "Asian Development Bank",
      debtCategory: "Multilateral Loans",
      paymentType: "Composite",
      principalLoanAmount: "15000000.00",
      interestRate: "1.00",
      paymentCurrencyId: "USD",
      loanTermValue: "35",
      loanTermUnit: "Years",
      repaymentFrequency: "Semi-annually",
      amortizationSchedule: "Linear",
      gracePeriodEnd: "2033-06-15",
      applicableDeduction: "Bank Charges",
      meridianReferenceId: "MRD-ADB-4105-2025",
      dataSource: "Meridian System Integration",
      paymentStatus: "Pending",
    },
    donor: SEED_DONORS[1],
    repayments: [],
    validationChecks: [],
    meridianLog: mlog([
      ["Push via Meridian API", "2025-12-01T11:00:00Z", "System (Auto)", "Initial loan data synchronised from ADB via Meridian integration"],
    ]),
    createdAt: "2025-10-20T09:30:00Z",
    updatedAt: "2025-12-01T12:00:00Z",
  },
];
