import { StoredSc, ScEntityHeader, ScDocument, ScPaymentTransaction, ScValidationCheck, ScApprovalEntry, ScLifecycleEvent } from './types';

export const SEED_SC_RECORDS: StoredSc[] = [
  {
    id: 'SC-2024-UN-001',
    header: {
      scId: 'SC-2024-UN-001',
      txnType: 'Contribution',
      scope: 'International',
      beneficiaryType: 'International Organisation',
      organisationType: 'UN Agency',
      entityName: 'United Nations Organization',
      shortName: 'UN',
      registryVendorId: 'VND-UN-1945',
      contactPerson: 'Dr. Tenzin Wangmo',
      contactNo: '+975-2-337955',
      email: 'unwang@mofa.gov.bt',
      addressBhutan: 'Ministry of Foreign Affairs, Thimphu 11001, Bhutan',
      addressOutside: 'United Nations, New York, NY 10017, USA',
      bankName: 'Royal Bank of Bhutan',
      bankBranchName: 'Thimphu Main Branch',
      bankAccountNo: 'RBB-0011-2847-5932',
      swiftRoutingCode: 'RBBTBTTT',
      currency: 'USD',
      budgetCode: 'BDG-10-002-001',
      paymentFrequency: 'Annually',
      membershipAmount: '175000',
      membershipPeriodFrom: '2024-01-01',
      membershipPeriodTo: '2024-12-31',
      entityStatus: 'Active',
      notes: 'Core UN membership dues paid annually. Essential for diplomatic representation and participation in global affairs.',
    },
    documents: [
      {
        id: 'DOC-UN-001-CERT',
        documentType: 'Membership Certificate',
        reference: 'UN-CERT-2024-1945',
        receivedDate: '2024-01-15',
        remarks: 'Official membership certificate from UN Secretariat confirming Bhutan\'s status as member state.',
      },
      {
        id: 'DOC-UN-001-INV',
        documentType: 'Invoice / Demand Note',
        reference: 'UN-INV-2024-003847',
        receivedDate: '2024-01-10',
        remarks: 'Annual assessed contribution demand note from UN Controller.',
      },
      {
        id: 'DOC-UN-001-CABINET',
        documentType: 'Board / Cabinet Approval',
        reference: 'CAB-2023-11-28',
        receivedDate: '2023-11-28',
        remarks: 'Cabinet approval for UN contribution payment in FY 2024.',
      },
    ],
    transactions: [
      {
        id: 'TXN-UN-001-2024',
        invoiceRef: 'UN-INV-2024-003847',
        period: '2024-01-01 to 2024-12-31',
        grossAmount: '175000',
        fxRate: '1.0000',
        btnEquivalent: '12950000',
        paymentOrderId: 'PO-2024-00847',
        txnStatus: 'Paid',
        remarks: 'Annual contribution paid via bank transfer on 2024-02-05.',
      },
    ],
    validationChecks: [
      {
        key: 'BUDGET-VER-UN-001',
        label: 'Budget Code Verification',
        passed: true,
        message: 'Budget code BDG-10-002-001 verified and allocated for FY 2024.',
      },
      {
        key: 'DUP-CHK-UN-001',
        label: 'Duplicate Payment Check',
        passed: true,
        message: 'No duplicate payments found for this invoice reference.',
      },
      {
        key: 'MEMBER-VAL-UN-001',
        label: 'Membership Validity Check',
        passed: true,
        message: 'Membership valid and in good standing with UN.',
      },
      {
        key: 'FX-VER-UN-001',
        label: 'Exchange Rate Verification',
        passed: true,
        message: 'Fixed rate maintained for USD. No conversion applied.',
      },
      {
        key: 'APP-AUTH-UN-001',
        label: 'Approval Authority Check',
        passed: true,
        message: 'Approval authority verified. Payment authorized by Finance Secretary.',
      },
    ],
    approvals: [
      {
        id: 'APR-UN-001-FO',
        level: 'Finance Officer',
        actor: 'Kinley Dorji',
        decidedAt: '2024-01-20',
        decision: 'Approved',
        remarks: 'Budget allocation confirmed. Documents complete.',
      },
      {
        id: 'APR-UN-001-BD',
        level: 'Budget Division',
        actor: 'Pema Tshering',
        decidedAt: '2024-01-25',
        decision: 'Approved',
        remarks: 'Budget division approval granted for fund transfer.',
      },
      {
        id: 'APR-UN-001-DPA',
        level: 'DPA Director',
        actor: 'Sonam Tobgay',
        decidedAt: '2024-02-01',
        decision: 'Approved',
        remarks: 'Final approval for payment processing.',
      },
    ],
    lifecycle: [
      {
        id: 'LCE-UN-001-001',
        occurredAt: '2023-11-28',
        fromStatus: 'Pending Renewal',
        toStatus: 'Active',
        actor: 'Cabinet Secretary',
        reason: 'Cabinet approved continuation of UN membership for FY 2024.',
      },
      {
        id: 'LCE-UN-001-002',
        occurredAt: '2024-01-20',
        fromStatus: 'Active',
        toStatus: 'Active',
        actor: 'Kinley Dorji',
        reason: 'Payment processed and confirmed.',
      },
    ],
    createdAt: '2023-11-28T10:15:00Z',
    updatedAt: '2024-02-05T14:32:00Z',
  },
  {
    id: 'SC-2024-SAARC-001',
    header: {
      scId: 'SC-2024-SAARC-001',
      txnType: 'Subscription',
      scope: 'International',
      beneficiaryType: 'Regional Body',
      organisationType: 'Regional Economic Body',
      entityName: 'SAARC Secretariat',
      shortName: 'SAARC',
      registryVendorId: 'VND-SAARC-1985',
      contactPerson: 'Mr. Sonam Norbu',
      contactNo: '+975-2-323046',
      email: 'saarc.coord@mofa.gov.bt',
      addressBhutan: 'Department of Multilateral Affairs, Ministry of Foreign Affairs, Thimphu 11001',
      addressOutside: 'SAARC Secretariat, Kathmandu, Nepal',
      bankName: 'Bhutan Kuen Nyam Bank',
      bankBranchName: 'Norzin Lam Branch, Thimphu',
      bankAccountNo: 'BKB-0045-8923-2104',
      swiftRoutingCode: 'BKBLBTTT',
      currency: 'USD',
      budgetCode: 'BDG-10-002-015',
      paymentFrequency: 'Annually',
      membershipAmount: '50000',
      membershipPeriodFrom: '2024-01-01',
      membershipPeriodTo: '2024-12-31',
      entityStatus: 'Active',
      notes: 'Annual subscription to SAARC Secretariat for regional economic cooperation and development initiatives.',
    },
    documents: [
      {
        id: 'DOC-SAARC-001-CERT',
        documentType: 'Membership Certificate',
        reference: 'SAARC-MEM-2024-BHU',
        receivedDate: '2023-12-20',
        remarks: 'Membership confirmation from SAARC Secretariat for FY 2024.',
      },
      {
        id: 'DOC-SAARC-001-INV',
        documentType: 'Invoice / Demand Note',
        reference: 'SAARC-INV-2024-0256',
        receivedDate: '2023-12-15',
        remarks: 'Annual subscription invoice for 2024.',
      },
      {
        id: 'DOC-SAARC-001-MOU',
        documentType: 'MoU / Agreement',
        reference: 'SAARC-MOU-2023-001',
        receivedDate: '2023-06-10',
        remarks: 'Renewed MoU for SAARC cooperation covering 2023-2025.',
      },
    ],
    transactions: [
      {
        id: 'TXN-SAARC-001-2024',
        invoiceRef: 'SAARC-INV-2024-0256',
        period: '2024-01-01 to 2024-12-31',
        grossAmount: '50000',
        fxRate: '1.0000',
        btnEquivalent: '3700000',
        paymentOrderId: 'PO-2024-00923',
        txnStatus: 'Paid',
        remarks: 'Subscription paid via international wire transfer on 2024-01-30.',
      },
    ],
    validationChecks: [
      {
        key: 'BUDGET-VER-SAARC-001',
        label: 'Budget Code Verification',
        passed: true,
        message: 'Budget code BDG-10-002-015 verified and allocated.',
      },
      {
        key: 'DUP-CHK-SAARC-001',
        label: 'Duplicate Payment Check',
        passed: true,
        message: 'No duplicate payments detected for SAARC-INV-2024-0256.',
      },
      {
        key: 'MEMBER-VAL-SAARC-001',
        label: 'Membership Validity Check',
        passed: true,
        message: 'SAARC membership valid and current.',
      },
      {
        key: 'FX-VER-SAARC-001',
        label: 'Exchange Rate Verification',
        passed: true,
        message: 'Exchange rate applied at market rate 74 BTN/USD on payment date.',
      },
      {
        key: 'APP-AUTH-SAARC-001',
        label: 'Approval Authority Check',
        passed: true,
        message: 'Approval authority confirmed and verified.',
      },
    ],
    approvals: [
      {
        id: 'APR-SAARC-001-FO',
        level: 'Finance Officer',
        actor: 'Kinley Dorji',
        decidedAt: '2024-01-15',
        decision: 'Approved',
        remarks: 'All documents verified and in order.',
      },
      {
        id: 'APR-SAARC-001-BD',
        level: 'Budget Division',
        actor: 'Pema Tshering',
        decidedAt: '2024-01-22',
        decision: 'Approved',
        remarks: 'Fund allocation confirmed.',
      },
    ],
    lifecycle: [
      {
        id: 'LCE-SAARC-001-001',
        occurredAt: '2023-12-01',
        fromStatus: 'Pending Renewal',
        toStatus: 'Active',
        actor: 'Sonam Norbu',
        reason: 'Renewal documents received and verified for FY 2024.',
      },
      {
        id: 'LCE-SAARC-001-002',
        occurredAt: '2024-01-30',
        fromStatus: 'Active',
        toStatus: 'Active',
        actor: 'Kinley Dorji',
        reason: 'Annual subscription payment processed successfully.',
      },
    ],
    createdAt: '2023-12-01T09:45:00Z',
    updatedAt: '2024-01-30T11:20:00Z',
  },
  {
    id: 'SC-2024-ADB-001',
    header: {
      scId: 'SC-2024-ADB-001',
      txnType: 'Contribution',
      scope: 'International',
      beneficiaryType: 'International Organisation',
      organisationType: 'Multilateral Development Bank',
      entityName: 'Asian Development Bank',
      shortName: 'ADB',
      registryVendorId: 'VND-ADB-1966',
      contactPerson: 'Ms. Tshering Dema',
      contactNo: '+975-2-321381',
      email: 'adb.country@mof.gov.bt',
      addressBhutan: 'Ministry of Finance, Thimphu 11001, Bhutan',
      addressOutside: 'Asian Development Bank, 6 ADB Avenue, Mandaluyong City, Metro Manila 1550, Philippines',
      bankName: 'Royal Bank of Bhutan',
      bankBranchName: 'Downtown Thimphu Branch',
      bankAccountNo: 'RBB-0012-5647-3891',
      swiftRoutingCode: 'RBBTBTTT',
      currency: 'USD',
      budgetCode: 'BDG-10-002-008',
      paymentFrequency: 'Annually',
      membershipAmount: '450000',
      membershipPeriodFrom: '2024-01-01',
      membershipPeriodTo: '2024-12-31',
      entityStatus: 'Active',
      notes: 'ADB capital subscription and annual membership contribution. Key multilateral development partner for Bhutan.',
    },
    documents: [
      {
        id: 'DOC-ADB-001-CERT',
        documentType: 'Membership Certificate',
        reference: 'ADB-CERT-2024-BHUTAN',
        receivedDate: '2024-01-05',
        remarks: 'Annual membership certificate from ADB confirming capital subscription and voting rights.',
      },
      {
        id: 'DOC-ADB-001-INV',
        documentType: 'Invoice / Demand Note',
        reference: 'ADB-INV-2024-BTN-0847',
        receivedDate: '2023-12-28',
        remarks: 'Contribution demand note for capital subscription payment.',
      },
      {
        id: 'DOC-ADB-001-CABINET',
        documentType: 'Board / Cabinet Approval',
        reference: 'CAB-2023-10-19',
        receivedDate: '2023-10-19',
        remarks: 'Cabinet approval for ADB contribution for FY 2024.',
      },
      {
        id: 'DOC-ADB-001-AGREEMENT',
        documentType: 'MoU / Agreement',
        reference: 'ADB-AGREEMENT-2023-001',
        receivedDate: '2023-05-15',
        remarks: 'Membership agreement and capital subscription terms.',
      },
    ],
    transactions: [
      {
        id: 'TXN-ADB-001-2024',
        invoiceRef: 'ADB-INV-2024-BTN-0847',
        period: '2024-01-01 to 2024-12-31',
        grossAmount: '450000',
        fxRate: '1.0000',
        btnEquivalent: '33300000',
        paymentOrderId: 'PO-2024-01204',
        txnStatus: 'Paid',
        remarks: 'Capital subscription paid via direct bank transfer on 2024-02-10.',
      },
    ],
    validationChecks: [
      {
        key: 'BUDGET-VER-ADB-001',
        label: 'Budget Code Verification',
        passed: true,
        message: 'Budget allocation verified for BDG-10-002-008.',
      },
      {
        key: 'DUP-CHK-ADB-001',
        label: 'Duplicate Payment Check',
        passed: true,
        message: 'No duplicate payments found for ADB-INV-2024-BTN-0847.',
      },
      {
        key: 'MEMBER-VAL-ADB-001',
        label: 'Membership Validity Check',
        passed: true,
        message: 'Membership and capital subscription status verified as current.',
      },
      {
        key: 'FX-VER-ADB-001',
        label: 'Exchange Rate Verification',
        passed: true,
        message: 'No exchange rate conversion required (USD to USD).',
      },
      {
        key: 'APP-AUTH-ADB-001',
        label: 'Approval Authority Check',
        passed: true,
        message: 'Appropriate approval authority confirmed.',
      },
    ],
    approvals: [
      {
        id: 'APR-ADB-001-FO',
        level: 'Finance Officer',
        actor: 'Jamyang Tobgay',
        decidedAt: '2024-01-25',
        decision: 'Approved',
        remarks: 'Large capital contribution approved with supporting documentation.',
      },
      {
        id: 'APR-ADB-001-BD',
        level: 'Budget Division',
        actor: 'Pema Tshering',
        decidedAt: '2024-02-01',
        decision: 'Approved',
        remarks: 'Budget verification completed.',
      },
      {
        id: 'APR-ADB-001-DPA',
        level: 'DPA Director',
        actor: 'Sonam Tobgay',
        decidedAt: '2024-02-05',
        decision: 'Approved',
        remarks: 'Final approval for major capital contribution.',
      },
      {
        id: 'APR-ADB-001-SEC',
        level: 'Finance Secretary',
        actor: 'Dr. Thinley Dorji',
        decidedAt: '2024-02-08',
        decision: 'Approved',
        remarks: 'Finance Secretary approval granted for payment execution.',
      },
    ],
    lifecycle: [
      {
        id: 'LCE-ADB-001-001',
        occurredAt: '2023-10-19',
        fromStatus: 'Pending Renewal',
        toStatus: 'Active',
        actor: 'Cabinet Secretary',
        reason: 'Cabinet approved ADB contribution commitment for FY 2024.',
      },
      {
        id: 'LCE-ADB-001-002',
        occurredAt: '2024-02-10',
        fromStatus: 'Active',
        toStatus: 'Active',
        actor: 'Jamyang Tobgay',
        reason: 'Large capital subscription payment successfully processed.',
      },
    ],
    createdAt: '2023-10-19T14:30:00Z',
    updatedAt: '2024-02-10T16:45:00Z',
  },
  {
    id: 'SC-2024-WB-001',
    header: {
      scId: 'SC-2024-WB-001',
      txnType: 'Contribution',
      scope: 'International',
      beneficiaryType: 'International Organisation',
      organisationType: 'Multilateral Development Bank',
      entityName: 'International Bank for Reconstruction and Development',
      shortName: 'World Bank / IBRD',
      registryVendorId: 'VND-WB-1944',
      contactPerson: 'Mr. Dorji Wangchuk',
      contactNo: '+975-2-322391',
      email: 'wb.country@mof.gov.bt',
      addressBhutan: 'Ministry of Finance, Thimphu 11001, Bhutan',
      addressOutside: 'The World Bank, 1818 H Street NW, Washington, DC 20433, USA',
      bankName: 'Bhutan Kuen Nyam Bank',
      bankBranchName: 'Norzin Lam Branch, Thimphu',
      bankAccountNo: 'BKB-0078-4562-1847',
      swiftRoutingCode: 'BKBLBTTT',
      currency: 'USD',
      budgetCode: 'BDG-10-002-009',
      paymentFrequency: 'Annually',
      membershipAmount: '320000',
      membershipPeriodFrom: '2024-01-01',
      membershipPeriodTo: '2024-12-31',
      entityStatus: 'Active',
      notes: 'IBRD capital share subscription and membership. Critical development financing partner for Bhutan.',
    },
    documents: [
      {
        id: 'DOC-WB-001-CERT',
        documentType: 'Membership Certificate',
        reference: 'WB-CERT-2024-BTN-001',
        receivedDate: '2024-01-08',
        remarks: 'IBRD membership certificate and capital share confirmation.',
      },
      {
        id: 'DOC-WB-001-INV',
        documentType: 'Invoice / Demand Note',
        reference: 'WB-INV-2024-000934',
        receivedDate: '2023-12-30',
        remarks: 'Annual capital subscription demand from World Bank.',
      },
      {
        id: 'DOC-WB-001-CABINET',
        documentType: 'Board / Cabinet Approval',
        reference: 'CAB-2023-11-15',
        receivedAt: '2023-11-15',
        remarks: 'Cabinet approval for World Bank contribution commitment.',
      },
    ],
    transactions: [
      {
        id: 'TXN-WB-001-2024',
        invoiceRef: 'WB-INV-2024-000934',
        period: '2024-01-01 to 2024-12-31',
        grossAmount: '320000',
        fxRate: '1.0000',
        btnEquivalent: '23680000',
        paymentOrderId: 'PO-2024-01089',
        txnStatus: 'Paid',
        remarks: 'Capital share subscription payment processed on 2024-02-12.',
      },
    ],
    validationChecks: [
      {
        key: 'BUDGET-VER-WB-001',
        label: 'Budget Code Verification',
        passed: true,
        message: 'Budget code BDG-10-002-009 verified.',
      },
      {
        key: 'DUP-CHK-WB-001',
        label: 'Duplicate Payment Check',
        passed: true,
        message: 'No duplicate payments found.',
      },
      {
        key: 'MEMBER-VAL-WB-001',
        label: 'Membership Validity Check',
        passed: true,
        message: 'World Bank membership and capital share status confirmed.',
      },
      {
        key: 'FX-VER-WB-001',
        label: 'Exchange Rate Verification',
        passed: true,
        message: 'No currency conversion required.',
      },
      {
        key: 'APP-AUTH-WB-001',
        label: 'Approval Authority Check',
        passed: true,
        message: 'Approval authority verified.',
      },
    ],
    approvals: [
      {
        id: 'APR-WB-001-FO',
        level: 'Finance Officer',
        actor: 'Jamyang Tobgay',
        decidedAt: '2024-01-28',
        decision: 'Approved',
        remarks: 'World Bank contribution approved.',
      },
      {
        id: 'APR-WB-001-BD',
        level: 'Budget Division',
        actor: 'Pema Tshering',
        decidedAt: '2024-02-03',
        decision: 'Approved',
        remarks: 'Budget allocation confirmed.',
      },
      {
        id: 'APR-WB-001-DPA',
        level: 'DPA Director',
        actor: 'Sonam Tobgay',
        decidedAt: '2024-02-08',
        decision: 'Approved',
        remarks: 'Approved for payment processing.',
      },
    ],
    lifecycle: [
      {
        id: 'LCE-WB-001-001',
        occurredAt: '2023-11-15',
        fromStatus: 'Pending Renewal',
        toStatus: 'Active',
        actor: 'Cabinet Secretary',
        reason: 'Cabinet approved World Bank membership renewal for FY 2024.',
      },
      {
        id: 'LCE-WB-001-002',
        occurredAt: '2024-02-12',
        fromStatus: 'Active',
        toStatus: 'Active',
        actor: 'Jamyang Tobgay',
        reason: 'Capital subscription payment successfully completed.',
      },
    ],
    createdAt: '2023-11-15T11:00:00Z',
    updatedAt: '2024-02-12T13:55:00Z',
  },
  {
    id: 'SC-2024-SAU-001',
    header: {
      scId: 'SC-2024-SAU-001',
      txnType: 'Subscription',
      scope: 'International',
      beneficiaryType: 'Regional Body',
      organisationType: 'Think Tank / Research',
      entityName: 'South Asian University',
      shortName: 'SAU',
      registryVendorId: 'VND-SAU-2010',
      contactPerson: 'Dr. Karmay Dorji',
      contactNo: '+975-2-325487',
      email: 'sau.liaison@education.gov.bt',
      addressBhutan: 'Ministry of Education, Thimphu 11001, Bhutan',
      addressOutside: 'South Asian University, New Delhi 110016, India',
      bankName: 'Royal Bank of Bhutan',
      bankBranchName: 'Norzin Lam Branch, Thimphu',
      bankAccountNo: 'RBB-0056-3218-7642',
      swiftRoutingCode: 'RBBTBTTT',
      currency: 'INR',
      budgetCode: 'BDG-10-003-012',
      paymentFrequency: 'Annually',
      membershipAmount: '800000',
      membershipPeriodFrom: '2024-01-01',
      membershipPeriodTo: '2024-12-31',
      entityStatus: 'Active',
      notes: 'Annual subscription fee for South Asian University membership. Supports regional higher education collaboration.',
    },
    documents: [
      {
        id: 'DOC-SAU-001-CERT',
        documentType: 'Membership Certificate',
        reference: 'SAU-MEM-2024-BTN',
        receivedDate: '2024-01-10',
        remarks: 'Membership certificate from South Asian University confirming institutional membership.',
      },
      {
        id: 'DOC-SAU-001-INV',
        documentType: 'Invoice / Demand Note',
        reference: 'SAU-INV-2024-I897',
        receivedDate: '2024-01-05',
        remarks: 'Annual subscription fee invoice in Indian Rupees.',
      },
    ],
    transactions: [
      {
        id: 'TXN-SAU-001-2024',
        invoiceRef: 'SAU-INV-2024-I897',
        period: '2024-01-01 to 2024-12-31',
        grossAmount: '800000',
        fxRate: '0.6850',
        btnEquivalent: '1169620',
        paymentOrderId: 'PO-2024-01345',
        txnStatus: 'Paid',
        remarks: 'Annual subscription paid via wire transfer on 2024-02-15.',
      },
    ],
    validationChecks: [
      {
        key: 'BUDGET-VER-SAU-001',
        label: 'Budget Code Verification',
        passed: true,
        message: 'Budget code BDG-10-003-012 verified.',
      },
      {
        key: 'DUP-CHK-SAU-001',
        label: 'Duplicate Payment Check',
        passed: true,
        message: 'No duplicate payments detected.',
      },
      {
        key: 'MEMBER-VAL-SAU-001',
        label: 'Membership Validity Check',
        passed: true,
        message: 'SAU membership status confirmed as current and active.',
      },
      {
        key: 'FX-VER-SAU-001',
        label: 'Exchange Rate Verification',
        passed: true,
        message: 'INR to BTN exchange rate applied at 1.4609 on 2024-02-15.',
      },
      {
        key: 'APP-AUTH-SAU-001',
        label: 'Approval Authority Check',
        passed: true,
        message: 'Approval authority confirmed.',
      },
    ],
    approvals: [
      {
        id: 'APR-SAU-001-FO',
        level: 'Finance Officer',
        actor: 'Kinley Dorji',
        decidedAt: '2024-01-18',
        decision: 'Approved',
        remarks: 'Educational institution subscription approved.',
      },
      {
        id: 'APR-SAU-001-BD',
        level: 'Budget Division',
        actor: 'Pema Tshering',
        decidedAt: '2024-02-01',
        decision: 'Approved',
        remarks: 'Budget allocation confirmed for education sector.',
      },
    ],
    lifecycle: [
      {
        id: 'LCE-SAU-001-001',
        occurredAt: '2024-01-05',
        fromStatus: 'Pending Renewal',
        toStatus: 'Active',
        actor: 'Dr. Karmay Dorji',
        reason: 'Annual subscription renewal invoice received from SAU.',
      },
      {
        id: 'LCE-SAU-001-002',
        occurredAt: '2024-02-15',
        fromStatus: 'Active',
        toStatus: 'Active',
        actor: 'Kinley Dorji',
        reason: 'Annual subscription payment successfully processed.',
      },
    ],
    createdAt: '2024-01-05T08:30:00Z',
    updatedAt: '2024-02-15T10:15:00Z',
  },
  {
    id: 'SC-2024-ITU-001',
    header: {
      scId: 'SC-2024-ITU-001',
      txnType: 'Subscription',
      scope: 'International',
      beneficiaryType: 'International Organisation',
      organisationType: 'Technical Standards Body',
      entityName: 'International Telecommunications Union',
      shortName: 'ITU',
      registryVendorId: 'VND-ITU-1865',
      contactPerson: 'Mr. Ugyen Phuntsho',
      contactNo: '+975-2-336211',
      email: 'itu.member@moic.gov.bt',
      addressBhutan: 'Ministry of Information and Communications, Thimphu 11001, Bhutan',
      addressOutside: 'International Telecommunications Union, Place des Nations, 1211 Geneva 20, Switzerland',
      bankName: 'Bhutan Kuen Nyam Bank',
      bankBranchName: 'Parkling Branch, Thimphu',
      bankAccountNo: 'BKB-0089-7734-5621',
      swiftRoutingCode: 'BKBLBTTT',
      currency: 'CHF',
      budgetCode: 'BDG-10-002-018',
      paymentFrequency: 'Annually',
      membershipAmount: '45000',
      membershipPeriodFrom: '2024-01-01',
      membershipPeriodTo: '2024-12-31',
      entityStatus: 'Active',
      notes: 'Annual ITU membership subscription for telecommunications standards and international regulations compliance.',
    },
    documents: [
      {
        id: 'DOC-ITU-001-CERT',
        documentType: 'Membership Certificate',
        reference: 'ITU-CERT-2024-BHU',
        receivedDate: '2024-01-12',
        remarks: 'ITU membership certificate confirming Bhutan\'s member state status.',
      },
      {
        id: 'DOC-ITU-001-INV',
        documentType: 'Invoice / Demand Note',
        reference: 'ITU-INV-2024-CHF-0456',
        receivedDate: '2023-12-27',
        remarks: 'Annual membership contribution in Swiss Francs.',
      },
      {
        id: 'DOC-ITU-001-AGREEMENT',
        documentType: 'MoU / Agreement',
        reference: 'ITU-AGREEMENT-2023',
        receivedDate: '2023-06-20',
        remarks: 'ITU membership terms and conditions document.',
      },
    ],
    transactions: [
      {
        id: 'TXN-ITU-001-2024',
        invoiceRef: 'ITU-INV-2024-CHF-0456',
        period: '2024-01-01 to 2024-12-31',
        grossAmount: '45000',
        fxRate: '0.8976',
        btnEquivalent: '4039200',
        paymentOrderId: 'PO-2024-01467',
        txnStatus: 'Paid',
        remarks: 'Membership subscription paid via bank transfer on 2024-02-18.',
      },
    ],
    validationChecks: [
      {
        key: 'BUDGET-VER-ITU-001',
        label: 'Budget Code Verification',
        passed: true,
        message: 'Budget code BDG-10-002-018 verified and allocated.',
      },
      {
        key: 'DUP-CHK-ITU-001',
        label: 'Duplicate Payment Check',
        passed: true,
        message: 'No duplicate payments found for ITU-INV-2024-CHF-0456.',
      },
      {
        key: 'MEMBER-VAL-ITU-001',
        label: 'Membership Validity Check',
        passed: true,
        message: 'ITU membership valid and in good standing.',
      },
      {
        key: 'FX-VER-ITU-001',
        label: 'Exchange Rate Verification',
        passed: true,
        message: 'CHF to BTN exchange rate applied at 89.76 on 2024-02-18.',
      },
      {
        key: 'APP-AUTH-ITU-001',
        label: 'Approval Authority Check',
        passed: true,
        message: 'Approval authority confirmed.',
      },
    ],
    approvals: [
      {
        id: 'APR-ITU-001-FO',
        level: 'Finance Officer',
        actor: 'Kinley Dorji',
        decidedAt: '2024-01-20',
        decision: 'Approved',
        remarks: 'Technical standards body subscription approved.',
      },
      {
        id: 'APR-ITU-001-BD',
        level: 'Budget Division',
        actor: 'Pema Tshering',
        decidedAt: '2024-02-05',
        decision: 'Approved',
        remarks: 'Budget allocation confirmed for ICT standards compliance.',
      },
    ],
    lifecycle: [
      {
        id: 'LCE-ITU-001-001',
        occurredAt: '2023-12-27',
        fromStatus: 'Pending Renewal',
        toStatus: 'Active',
        actor: 'Mr. Ugyen Phuntsho',
        reason: 'Annual membership invoice received from ITU.',
      },
      {
        id: 'LCE-ITU-001-002',
        occurredAt: '2024-02-18',
        fromStatus: 'Active',
        toStatus: 'Active',
        actor: 'Kinley Dorji',
        reason: 'Membership subscription payment successfully processed.',
      },
    ],
    createdAt: '2023-12-27T13:20:00Z',
    updatedAt: '2024-02-18T15:40:00Z',
  },
  {
    id: 'SC-2024-BCCI-001',
    header: {
      scId: 'SC-2024-BCCI-001',
      txnType: 'Subscription',
      scope: 'Domestic',
      beneficiaryType: 'Professional Body',
      organisationType: 'Professional Association',
      entityName: 'Bhutan Chamber of Commerce and Industry',
      shortName: 'BCCI',
      registryVendorId: 'VND-BCCI-2012',
      contactPerson: 'Ms. Tshering Yangkyi',
      contactNo: '+975-2-330446',
      email: 'membership@bcci.org.bt',
      addressBhutan: 'Norzin Lam, Thimphu 11001, Bhutan',
      addressOutside: 'Same as Bhutan address',
      bankName: 'Royal Bank of Bhutan',
      bankBranchName: 'BCCI Branch, Thimphu',
      bankAccountNo: 'RBB-0067-8845-2134',
      swiftRoutingCode: 'RBBTBTTT',
      currency: 'BTN',
      budgetCode: 'BDG-10-004-005',
      paymentFrequency: 'Annually',
      membershipAmount: '250000',
      membershipPeriodFrom: '2024-01-01',
      membershipPeriodTo: '2024-12-31',
      entityStatus: 'Active',
      notes: 'Domestic subscription to Bhutan Chamber of Commerce and Industry. Government supporting private sector engagement.',
    },
    documents: [
      {
        id: 'DOC-BCCI-001-CERT',
        documentType: 'Membership Certificate',
        reference: 'BCCI-MEM-2024-GOV',
        receivedDate: '2024-01-08',
        remarks: 'Government membership certificate from BCCI.',
      },
      {
        id: 'DOC-BCCI-001-INV',
        documentType: 'Invoice / Demand Note',
        reference: 'BCCI-INV-2024-0135',
        receivedDate: '2024-01-02',
        remarks: 'Annual government membership dues invoice.',
      },
    ],
    transactions: [
      {
        id: 'TXN-BCCI-001-2024',
        invoiceRef: 'BCCI-INV-2024-0135',
        period: '2024-01-01 to 2024-12-31',
        grossAmount: '250000',
        fxRate: '1.0000',
        btnEquivalent: '250000',
        paymentOrderId: 'PO-2024-00512',
        txnStatus: 'Paid',
        remarks: 'Domestic membership dues paid via local bank transfer on 2024-01-20.',
      },
    ],
    validationChecks: [
      {
        key: 'BUDGET-VER-BCCI-001',
        label: 'Budget Code Verification',
        passed: true,
        message: 'Budget code BDG-10-004-005 verified.',
      },
      {
        key: 'DUP-CHK-BCCI-001',
        label: 'Duplicate Payment Check',
        passed: true,
        message: 'No duplicate payments found.',
      },
      {
        key: 'MEMBER-VAL-BCCI-001',
        label: 'Membership Validity Check',
        passed: true,
        message: 'BCCI membership status verified.',
      },
      {
        key: 'FX-VER-BCCI-001',
        label: 'Exchange Rate Verification',
        passed: true,
        message: 'Domestic currency. No exchange conversion required.',
      },
      {
        key: 'APP-AUTH-BCCI-001',
        label: 'Approval Authority Check',
        passed: true,
        message: 'Approval authority confirmed.',
      },
    ],
    approvals: [
      {
        id: 'APR-BCCI-001-FO',
        level: 'Finance Officer',
        actor: 'Kinley Dorji',
        decidedAt: '2024-01-10',
        decision: 'Approved',
        remarks: 'Domestic association subscription approved.',
      },
      {
        id: 'APR-BCCI-001-BD',
        level: 'Budget Division',
        actor: 'Pema Tshering',
        decidedAt: '2024-01-15',
        decision: 'Approved',
        remarks: 'Domestic budget allocation confirmed.',
      },
    ],
    lifecycle: [
      {
        id: 'LCE-BCCI-001-001',
        occurredAt: '2024-01-02',
        fromStatus: 'Pending Renewal',
        toStatus: 'Active',
        actor: 'Ms. Tshering Yangkyi',
        reason: 'Annual membership invoice received from BCCI.',
      },
      {
        id: 'LCE-BCCI-001-002',
        occurredAt: '2024-01-20',
        fromStatus: 'Active',
        toStatus: 'Active',
        actor: 'Kinley Dorji',
        reason: 'Membership payment successfully processed.',
      },
    ],
    createdAt: '2024-01-02T09:00:00Z',
    updatedAt: '2024-01-20T11:30:00Z',
  },
  {
    id: 'SC-2024-BIMSTEC-001',
    header: {
      scId: 'SC-2024-BIMSTEC-001',
      txnType: 'Contribution',
      scope: 'International',
      beneficiaryType: 'Regional Body',
      organisationType: 'Regional Economic Body',
      entityName: 'BIMSTEC Secretariat',
      shortName: 'BIMSTEC',
      registryVendorId: 'VND-BIMSTEC-1997',
      contactPerson: 'Mr. Sonam Tshering',
      contactNo: '+975-2-338892',
      email: 'bimstec@mofa.gov.bt',
      addressBhutan: 'Ministry of Foreign Affairs, Thimphu 11001, Bhutan',
      addressOutside: 'BIMSTEC Secretariat, Dhaka, Bangladesh',
      bankName: 'Royal Bank of Bhutan',
      bankBranchName: 'Downtown Thimphu Branch',
      bankAccountNo: 'RBB-0043-6721-8945',
      swiftRoutingCode: 'RBBTBTTT',
      currency: 'USD',
      budgetCode: 'BDG-10-002-016',
      paymentFrequency: 'Annually',
      membershipAmount: '75000',
      membershipPeriodFrom: '2024-01-01',
      membershipPeriodTo: '2024-12-31',
      entityStatus: 'Active',
      notes: 'BIMSTEC contribution for regional trade and development initiatives. Bay of Bengal region cooperation mechanism.',
    },
    documents: [
      {
        id: 'DOC-BIMSTEC-001-CERT',
        documentType: 'Membership Certificate',
        reference: 'BIMSTEC-MEM-2024-BTN',
        receivedDate: '2024-01-14',
        remarks: 'BIMSTEC membership certificate confirming participation status.',
      },
      {
        id: 'DOC-BIMSTEC-001-INV',
        documentType: 'Invoice / Demand Note',
        reference: 'BIMSTEC-INV-2024-0789',
        receivedDate: '2024-01-08',
        remarks: 'Annual contribution invoice from BIMSTEC Secretariat.',
      },
      {
        id: 'DOC-BIMSTEC-001-MOU',
        documentType: 'MoU / Agreement',
        reference: 'BIMSTEC-MOU-2024-RENEW',
        receivedDate: '2024-01-05',
        remarks: 'Renewed BIMSTEC membership agreement for 2024.',
      },
    ],
    transactions: [
      {
        id: 'TXN-BIMSTEC-001-2024',
        invoiceRef: 'BIMSTEC-INV-2024-0789',
        period: '2024-01-01 to 2024-12-31',
        grossAmount: '75000',
        fxRate: '1.0000',
        btnEquivalent: '5550000',
        paymentOrderId: 'PO-2024-01156',
        txnStatus: 'Paid',
        remarks: 'Annual BIMSTEC contribution paid on 2024-02-20.',
      },
    ],
    validationChecks: [
      {
        key: 'BUDGET-VER-BIMSTEC-001',
        label: 'Budget Code Verification',
        passed: true,
        message: 'Budget code BDG-10-002-016 verified.',
      },
      {
        key: 'DUP-CHK-BIMSTEC-001',
        label: 'Duplicate Payment Check',
        passed: true,
        message: 'No duplicate payments detected for BIMSTEC-INV-2024-0789.',
      },
      {
        key: 'MEMBER-VAL-BIMSTEC-001',
        label: 'Membership Validity Check',
        passed: true,
        message: 'BIMSTEC membership and contribution status verified.',
      },
      {
        key: 'FX-VER-BIMSTEC-001',
        label: 'Exchange Rate Verification',
        passed: true,
        message: 'No currency conversion required (USD).',
      },
      {
        key: 'APP-AUTH-BIMSTEC-001',
        label: 'Approval Authority Check',
        passed: true,
        message: 'Approval authority confirmed.',
      },
    ],
    approvals: [
      {
        id: 'APR-BIMSTEC-001-FO',
        level: 'Finance Officer',
        actor: 'Jamyang Tobgay',
        decidedAt: '2024-01-25',
        decision: 'Approved',
        remarks: 'Regional body contribution approved.',
      },
      {
        id: 'APR-BIMSTEC-001-BD',
        level: 'Budget Division',
        actor: 'Pema Tshering',
        decidedAt: '2024-02-05',
        decision: 'Approved',
        remarks: 'Budget allocation confirmed.',
      },
    ],
    lifecycle: [
      {
        id: 'LCE-BIMSTEC-001-001',
        occurredAt: '2024-01-05',
        fromStatus: 'Pending Renewal',
        toStatus: 'Active',
        actor: 'Mr. Sonam Tshering',
        reason: 'BIMSTEC membership renewal documents received.',
      },
      {
        id: 'LCE-BIMSTEC-001-002',
        occurredAt: '2024-02-20',
        fromStatus: 'Active',
        toStatus: 'Active',
        actor: 'Jamyang Tobgay',
        reason: 'Annual contribution payment successfully processed.',
      },
    ],
    createdAt: '2024-01-05T10:45:00Z',
    updatedAt: '2024-02-20T14:20:00Z',
  },
  {
    id: 'SC-2024-IOC-001',
    header: {
      scId: 'SC-2024-IOC-001',
      txnType: 'Subscription',
      scope: 'International',
      beneficiaryType: 'International Organisation',
      organisationType: 'Sports Federation',
      entityName: 'International Olympic Committee',
      shortName: 'IOC',
      registryVendorId: 'VND-IOC-1894',
      contactPerson: 'Mr. Pema Dorji',
      contactNo: '+975-2-322146',
      email: 'ioc.bhutan@boc.org.bt',
      addressBhutan: 'Ministry of Health, Thimphu 11001, Bhutan',
      addressOutside: 'International Olympic Committee, Lausanne, Switzerland',
      bankName: 'Bhutan Kuen Nyam Bank',
      bankBranchName: 'Norzin Lam Branch, Thimphu',
      bankAccountNo: 'BKB-0091-5523-4876',
      swiftRoutingCode: 'BKBLBTTT',
      currency: 'CHF',
      budgetCode: 'BDG-10-005-003',
      paymentFrequency: 'Annually',
      membershipAmount: '52000',
      membershipPeriodFrom: '2024-01-01',
      membershipPeriodTo: '2024-12-31',
      entityStatus: 'Active',
      notes: 'IOC membership subscription for international sporting events and Olympic Games participation.',
    },
    documents: [
      {
        id: 'DOC-IOC-001-CERT',
        documentType: 'Membership Certificate',
        reference: 'IOC-CERT-2024-BHUTAN',
        receivedDate: '2024-01-11',
        remarks: 'IOC membership certificate and Olympic recognition document.',
      },
      {
        id: 'DOC-IOC-001-INV',
        documentType: 'Invoice / Demand Note',
        reference: 'IOC-INV-2024-CHF-0234',
        receivedDate: '2023-12-29',
        remarks: 'Annual IOC membership fee in Swiss Francs.',
      },
      {
        id: 'DOC-IOC-001-RECEIPT',
        documentType: 'Payment Receipt',
        reference: 'IOC-RECEIPT-2024-001',
        receivedDate: '2024-02-25',
        remarks: 'Payment confirmation receipt from IOC.',
      },
    ],
    transactions: [
      {
        id: 'TXN-IOC-001-2024',
        invoiceRef: 'IOC-INV-2024-CHF-0234',
        period: '2024-01-01 to 2024-12-31',
        grossAmount: '52000',
        fxRate: '0.8976',
        btnEquivalent: '4667520',
        paymentOrderId: 'PO-2024-01523',
        txnStatus: 'Paid',
        remarks: 'Olympic Committee membership paid on 2024-02-22.',
      },
    ],
    validationChecks: [
      {
        key: 'BUDGET-VER-IOC-001',
        label: 'Budget Code Verification',
        passed: true,
        message: 'Budget code BDG-10-005-003 verified.',
      },
      {
        key: 'DUP-CHK-IOC-001',
        label: 'Duplicate Payment Check',
        passed: true,
        message: 'No duplicate payments found.',
      },
      {
        key: 'MEMBER-VAL-IOC-001',
        label: 'Membership Validity Check',
        passed: true,
        message: 'IOC membership status confirmed as active.',
      },
      {
        key: 'FX-VER-IOC-001',
        label: 'Exchange Rate Verification',
        passed: true,
        message: 'CHF to BTN exchange rate applied at 89.76 on payment date.',
      },
      {
        key: 'APP-AUTH-IOC-001',
        label: 'Approval Authority Check',
        passed: true,
        message: 'Approval authority verified.',
      },
    ],
    approvals: [
      {
        id: 'APR-IOC-001-FO',
        level: 'Finance Officer',
        actor: 'Kinley Dorji',
        decidedAt: '2024-01-22',
        decision: 'Approved',
        remarks: 'Sports federation subscription approved.',
      },
      {
        id: 'APR-IOC-001-BD',
        level: 'Budget Division',
        actor: 'Pema Tshering',
        decidedAt: '2024-02-08',
        decision: 'Approved',
        remarks: 'Budget allocation for sports ministry confirmed.',
      },
    ],
    lifecycle: [
      {
        id: 'LCE-IOC-001-001',
        occurredAt: '2023-12-29',
        fromStatus: 'Pending Renewal',
        toStatus: 'Active',
        actor: 'Mr. Pema Dorji',
        reason: 'IOC membership renewal invoice received.',
      },
      {
        id: 'LCE-IOC-001-002',
        occurredAt: '2024-02-22',
        fromStatus: 'Active',
        toStatus: 'Active',
        actor: 'Kinley Dorji',
        reason: 'IOC membership payment successfully processed.',
      },
    ],
    createdAt: '2023-12-29T12:30:00Z',
    updatedAt: '2024-02-22T16:10:00Z',
  },
  {
    id: 'SC-2024-CPC-001',
    header: {
      scId: 'SC-2024-CPC-001',
      txnType: 'Subscription',
      scope: 'International',
      beneficiaryType: 'Regional Body',
      organisationType: 'Regional Economic Body',
      entityName: 'Colombo Plan Council',
      shortName: 'CPC',
      registryVendorId: 'VND-CPC-1950',
      contactPerson: 'Mr. Tenzin Norbu',
      contactNo: '+975-2-325612',
      email: 'colomboplan@mofa.gov.bt',
      addressBhutan: 'Ministry of Foreign Affairs, Thimphu 11001, Bhutan',
      addressOutside: 'Colombo Plan Council, Colombo, Sri Lanka',
      bankName: 'Royal Bank of Bhutan',
      bankBranchName: 'Norzin Lam Branch, Thimphu',
      bankAccountNo: 'RBB-0054-9876-3210',
      swiftRoutingCode: 'RBBTBTTT',
      currency: 'USD',
      budgetCode: 'BDG-10-002-020',
      paymentFrequency: 'Annually',
      membershipAmount: '60000',
      membershipPeriodFrom: '2024-01-01',
      membershipPeriodTo: '2024-12-31',
      entityStatus: 'Active',
      notes: 'Colombo Plan Council subscription for regional development and technical cooperation in South Asia.',
    },
    documents: [
      {
        id: 'DOC-CPC-001-CERT',
        documentType: 'Membership Certificate',
        reference: 'CPC-MEM-2024-BTN',
        receivedDate: '2024-01-09',
        remarks: 'Colombo Plan membership certificate confirming member country status.',
      },
      {
        id: 'DOC-CPC-001-INV',
        documentType: 'Invoice / Demand Note',
        reference: 'CPC-INV-2024-0567',
        receivedDate: '2024-01-03',
        remarks: 'Annual membership contribution invoice.',
      },
      {
        id: 'DOC-CPC-001-AGREEMENT',
        documentType: 'MoU / Agreement',
        reference: 'CPC-FRAMEWORK-2024',
        receivedDate: '2023-12-15',
        remarks: 'Colombo Plan framework agreement for technical cooperation.',
      },
    ],
    transactions: [
      {
        id: 'TXN-CPC-001-2024',
        invoiceRef: 'CPC-INV-2024-0567',
        period: '2024-01-01 to 2024-12-31',
        grossAmount: '60000',
        fxRate: '1.0000',
        btnEquivalent: '4440000',
        paymentOrderId: 'PO-2024-00678',
        txnStatus: 'Paid',
        remarks: 'Colombo Plan annual subscription paid on 2024-02-28.',
      },
    ],
    validationChecks: [
      {
        key: 'BUDGET-VER-CPC-001',
        label: 'Budget Code Verification',
        passed: true,
        message: 'Budget code BDG-10-002-020 verified.',
      },
      {
        key: 'DUP-CHK-CPC-001',
        label: 'Duplicate Payment Check',
        passed: true,
        message: 'No duplicate payments found for CPC-INV-2024-0567.',
      },
      {
        key: 'MEMBER-VAL-CPC-001',
        label: 'Membership Validity Check',
        passed: true,
        message: 'Colombo Plan membership valid and in good standing.',
      },
      {
        key: 'FX-VER-CPC-001',
        label: 'Exchange Rate Verification',
        passed: true,
        message: 'No currency conversion required (USD).',
      },
      {
        key: 'APP-AUTH-CPC-001',
        label: 'Approval Authority Check',
        passed: true,
        message: 'Approval authority confirmed.',
      },
    ],
    approvals: [
      {
        id: 'APR-CPC-001-FO',
        level: 'Finance Officer',
        actor: 'Jamyang Tobgay',
        decidedAt: '2024-01-28',
        decision: 'Approved',
        remarks: 'Regional development body subscription approved.',
      },
      {
        id: 'APR-CPC-001-BD',
        level: 'Budget Division',
        actor: 'Pema Tshering',
        decidedAt: '2024-02-12',
        decision: 'Approved',
        remarks: 'Budget allocation confirmed for multilateral affairs.',
      },
    ],
    lifecycle: [
      {
        id: 'LCE-CPC-001-001',
        occurredAt: '2024-01-03',
        fromStatus: 'Pending Renewal',
        toStatus: 'Active',
        actor: 'Mr. Tenzin Norbu',
        reason: 'Colombo Plan membership renewal invoice received.',
      },
      {
        id: 'LCE-CPC-001-002',
        occurredAt: '2024-02-28',
        fromStatus: 'Active',
        toStatus: 'Active',
        actor: 'Jamyang Tobgay',
        reason: 'Annual subscription payment successfully processed.',
      },
    ],
    createdAt: '2024-01-03T11:15:00Z',
    updatedAt: '2024-02-28T17:25:00Z',
  },
];
