/* Dashboard tile catalog (single source of truth) */
import type { DashboardTileDef } from "../types";

export const DASHBOARD_TILES: DashboardTileDef[] = [
  {
    key: "submission",
    view: "submission",
    icon: "⚡",
    title: "Invoice Submission",
    cta: "Start →",
    accent: "text-sky-600",
    border: "border-sky-200",
    bg: "from-sky-50 via-white to-sky-50/60",
    iconBg: "from-sky-500 to-sky-600",
  },
  {
    key: "processing",
    view: "processing",
    icon: "📥",
    title: "Invoice Processing",
    cta: "Open →",
    accent: "text-violet-600",
    border: "border-violet-200",
    bg: "from-violet-50 via-white to-violet-50/60",
    iconBg: "from-violet-500 to-violet-600",
  },
  {
    key: "approval",
    view: "approval",
    icon: "💳",
    title: "Invoice Approval",
    cta: "Open →",
    accent: "text-amber-600",
    border: "border-amber-200",
    bg: "from-amber-50 via-white to-amber-50/60",
    iconBg: "from-amber-500 to-amber-600",
  },
  {
    key: "paymentOrder",
    view: "paymentOrder",
    icon: "💰",
    title: "Payment Order & Release",
    cta: "Open →",
    accent: "text-emerald-700",
    border: "border-emerald-200",
    bg: "from-emerald-50 via-white to-emerald-50/60",
    iconBg: "from-emerald-500 to-emerald-600",
  },
  {
    key: "reversal",
    view: "reversal",
    icon: "↩",
    title: "Reversal Authorisation",
    cta: "Open →",
    accent: "text-rose-700",
    border: "border-rose-200",
    bg: "from-rose-50 via-white to-rose-50/60",
    iconBg: "from-rose-500 to-rose-600",
  },
];
