import {
  StoredSoe,
  SoeTransferHeader,
  SoeLine,
  SoeValidationCheck,
  SoeApprovalEntry,
  SoeReleaseEntry,
  SoeReconciliationEntry,
} from './types';

export const SEED_SOE_RECORDS: StoredSoe[] = [
  // 1. Budget Release - Ministry of Health (Draft)
  {
    id: 'SOE-2026-001',
    header: {
      transferId: 'TXN-MH-2026-0501',
      transferType: 'Budget Release',
      direction: 'Outward',
      sourceOfFund: 'Consolidated Fund',
      destinationAccountType: 'Operating Account',
      originatingAgency: 'Ministry of Finance',
      receivingAgency: 'Ministry of Health',
      parliamentSanctionRef: 'PS/2025-2026/MH-03',
      budgetHeadCode: 'BH-2100-04-01',
      currency: 'BTN',
      exchangeRate: '1.00',
      totalAmount: '125000000.00',
      valueDate: '2026-04-10',
      reportingFrequency: 'Monthly',
      expenditureCategory: 'Current Expenditure',
      transferStatus: 'Draft',
      narrative: 'Q2 budget release for healthcare operations and staff remuneration',
    },
    soeLines: [
      {
        id: 'SOL-001-001',
        expenditureCategory: 'Current Expenditure',
        ucoaCode: '5000-01',
        description: 'Staff salaries and allowances - Healthcare workers',
        amount: '75000000.00',
        currency: 'BTN',
        documentType: 'Utility Bill',
        documentRef: 'SALARY-ROSTER-2026-Q2',
        remarks: 'Approved by HR and Finance divisions',
      },
      {
        id: 'SOL-001-002',
        expenditureCategory: 'Current Expenditure',
        ucoaCode: '5100-02',
        description: 'Medical supplies and equipment maintenance',
        amount: '35000000.00',
        currency: 'BTN',
        documentType: 'Invoice',
        documentRef: 'INV-MED-2026-04-156',
        remarks: 'Procured through competitive bidding process',
      },
      {
        id: 'SOL-001-003',
        expenditureCategory: 'Current Expenditure',
        ucoaCode: '5200-03',
        description: 'Utility charges for healthcare facilities',
        amount: '15000000.00',
        currency: 'BTN',
        documentType: 'Utility Bill',
        documentRef: 'UTIL-2026-Q2-MH',
        remarks: 'Electricity and water for all health centers nationwide',
      },
    ],
    validationChecks: [
      {
        key: 'budget-check',
        label: 'Budget Availability Check',
        passed: true,
        message: 'Budget available in BH-2100-04-01',
        status: 'Passed',
      },
      {
        key: 'duplicate-check',
        label: 'Duplicate Transfer Check',
        passed: true,
        message: 'No duplicate transfers detected',
        status: 'Passed',
      },
      {
        key: 'ceiling-check',
        label: 'Expenditure Ceiling Check',
        passed: true,
        message: 'Within quarterly expenditure ceiling',
        status: 'Passed',
      },
      {
        key: 'signatory-check',
        label: 'Authorised Signatory Check',
        passed: false,
        message: 'Awaiting Finance Secretary approval',
        status: 'Pending',
      },
      {
        key: 'document-check',
        label: 'Supporting Document Completeness',
        passed: true,
        message: 'All required documents attached',
        status: 'Passed',
      },
    ],
    approvals: [],
    releases: [],
    reconciliation: [],
    createdAt: '2026-04-08T09:30:00Z',
    updatedAt: '2026-04-08T09:30:00Z',
  },

  // 2. Inter-Agency Transfer - Ministry of Education to Paro Dzongkhag (Submitted)
  {
    id: 'SOE-2026-002',
    header: {
      transferId: 'TXN-ED-2026-0502',
      transferType: 'Inter-Agency Transfer',
      direction: 'Outward',
      sourceOfFund: 'Current Deposit Account',
      destinationAccountType: 'Project Account',
      originatingAgency: 'Ministry of Education',
      receivingAgency: 'Paro Dzongkhag Administration',
      parliamentSanctionRef: 'PS/2025-2026/ED-05',
      budgetHeadCode: 'BH-2600-02-03',
      currency: 'BTN',
      exchangeRate: '1.00',
      totalAmount: '45000000.00',
      valueDate: '2026-04-15',
      reportingFrequency: 'Quarterly',
      expenditureCategory: 'Capital Expenditure',
      transferStatus: 'Submitted',
      narrative: 'Fund transfer for school infrastructure development in Paro district',
    },
    soeLines: [
      {
        id: 'SOL-002-001',
        expenditureCategory: 'Capital Expenditure',
        ucoaCode: '6000-01',
        description: 'Construction of new school building - Paro Higher Secondary',
        amount: '28000000.00',
        currency: 'BTN',
        documentType: 'Contract Payment Cert',
        documentRef: 'CONTR-PARO-HSS-2026',
        remarks: 'Certified by supervising engineer, Stage 2 completion',
      },
      {
        id: 'SOL-002-002',
        expenditureCategory: 'Capital Expenditure',
        ucoaCode: '6100-02',
        description: 'Computer lab equipment and furniture',
        amount: '12000000.00',
        currency: 'BTN',
        documentType: 'Invoice',
        documentRef: 'INV-IT-PARO-2026-03',
        remarks: 'Supply and installation of lab equipment',
      },
      {
        id: 'SOL-002-003',
        expenditureCategory: 'Capital Expenditure',
        ucoaCode: '6200-03',
        description: 'Sports facilities and playground development',
        amount: '5000000.00',
        currency: 'BTN',
        documentType: 'Purchase Order',
        documentRef: 'PO-PARO-SPORTS-2026',
        remarks: 'Infrastructure development for student welfare',
      },
    ],
    validationChecks: [
      {
        key: 'budget-check',
        label: 'Budget Availability Check',
        passed: true,
        message: 'Sufficient funds in CDA for project account',
        status: 'Passed',
      },
      {
        key: 'duplicate-check',
        label: 'Duplicate Transfer Check',
        passed: true,
        message: 'No previous similar transfers this quarter',
        status: 'Passed',
      },
      {
        key: 'ceiling-check',
        label: 'Expenditure Ceiling Check',
        passed: true,
        message: 'Within capital expenditure allocation',
        status: 'Passed',
      },
      {
        key: 'signatory-check',
        label: 'Authorised Signatory Check',
        passed: true,
        message: 'Signed by authorized official',
        status: 'Passed',
      },
      {
        key: 'document-check',
        label: 'Supporting Document Completeness',
        passed: true,
        message: 'All required documents attached',
        status: 'Passed',
      },
    ],
    approvals: [
      {
        id: 'APR-002-001',
        level: 'Agency Finance',
        actor: 'Tenzin Dorji',
        decidedAt: '2026-04-09T14:20:00Z',
        decision: 'Approved',
        remarks: 'Finance review completed, documents verified',
      },
    ],
    releases: [],
    reconciliation: [],
    createdAt: '2026-04-08T10:15:00Z',
    updatedAt: '2026-04-09T14:20:00Z',
  },

  // 3. Fund Replenishment - Ministry of Finance Imprest (Under Review)
  {
    id: 'SOE-2026-003',
    header: {
      transferId: 'TXN-FIN-2026-0503',
      transferType: 'Fund Replenishment',
      direction: 'Inward',
      sourceOfFund: 'Consolidated Fund',
      destinationAccountType: 'Imprest Account',
      originatingAgency: 'Ministry of Finance',
      receivingAgency: 'Ministry of Finance',
      parliamentSanctionRef: 'PS/2025-2026/FIN-01',
      budgetHeadCode: 'BH-1200-01-01',
      currency: 'BTN',
      exchangeRate: '1.00',
      totalAmount: '30000000.00',
      valueDate: '2026-04-12',
      reportingFrequency: 'Monthly',
      expenditureCategory: 'Current Expenditure',
      transferStatus: 'Under Review',
      narrative: 'Replenishment of imprest account for contingency expenditures and urgent operational needs',
    },
    soeLines: [
      {
        id: 'SOL-003-001',
        expenditureCategory: 'Current Expenditure',
        ucoaCode: '5300-01',
        description: 'Contingency fund for emergency expenses',
        amount: '20000000.00',
        currency: 'BTN',
        documentType: 'Receipt',
        documentRef: 'RCP-IMPREST-2026-04',
        remarks: 'Previously released imprest account replenishment',
      },
      {
        id: 'SOL-003-002',
        expenditureCategory: 'Current Expenditure',
        ucoaCode: '5400-02',
        description: 'Petty cash and operational expenses',
        amount: '10000000.00',
        currency: 'BTN',
        documentType: 'Receipt',
        documentRef: 'RCP-PETTY-2026-04',
        remarks: 'For routine office operations and travel',
      },
    ],
    validationChecks: [
      {
        key: 'budget-check',
        label: 'Budget Availability Check',
        passed: true,
        message: 'Budget available for contingency replenishment',
        status: 'Passed',
      },
      {
        key: 'duplicate-check',
        label: 'Duplicate Transfer Check',
        passed: true,
        message: 'Previous replenishment settled, no duplicates',
        status: 'Passed',
      },
      {
        key: 'ceiling-check',
        label: 'Expenditure Ceiling Check',
        passed: true,
        message: 'Within imprest replenishment limits',
        status: 'Passed',
      },
      {
        key: 'signatory-check',
        label: 'Authorised Signatory Check',
        passed: true,
        message: 'Authorized by Deputy Secretary',
        status: 'Passed',
      },
      {
        key: 'document-check',
        label: 'Supporting Document Completeness',
        passed: true,
        message: 'Imprest account statement and receipts attached',
        status: 'Passed',
      },
    ],
    approvals: [
      {
        id: 'APR-003-001',
        level: 'Agency Finance',
        actor: 'Pema Tshering',
        decidedAt: '2026-04-09T11:00:00Z',
        decision: 'Approved',
        remarks: 'Internal Finance review completed',
      },
      {
        id: 'APR-003-002',
        level: 'Budget Division',
        actor: 'Sonam Wangdi',
        decidedAt: '2026-04-10T09:45:00Z',
        decision: 'Under Review',
        remarks: 'Awaiting final verification of previous imprest utilization',
      },
    ],
    releases: [],
    reconciliation: [],
    createdAt: '2026-04-08T08:00:00Z',
    updatedAt: '2026-04-10T09:45:00Z',
  },

  // 4. Grant Disbursement - Thimphu Thromde (Approved)
  {
    id: 'SOE-2026-004',
    header: {
      transferId: 'TXN-THROMDE-2026-0504',
      transferType: 'Grant Disbursement',
      direction: 'Outward',
      sourceOfFund: 'Consolidated Fund',
      destinationAccountType: 'Operating Account',
      originatingAgency: 'Ministry of Finance',
      receivingAgency: 'Thimphu City Thromde',
      parliamentSanctionRef: 'PS/2025-2026/THROMDE-02',
      budgetHeadCode: 'BH-3200-05-02',
      currency: 'BTN',
      exchangeRate: '1.00',
      totalAmount: '85000000.00',
      valueDate: '2026-04-18',
      reportingFrequency: 'Quarterly',
      expenditureCategory: 'Subsidy & Transfer',
      transferStatus: 'Approved',
      narrative: 'Grant disbursement to Thimphu City Thromde for urban infrastructure and municipal services',
    },
    soeLines: [
      {
        id: 'SOL-004-001',
        expenditureCategory: 'Subsidy & Transfer',
        ucoaCode: '7000-01',
        description: 'Urban road maintenance and rehabilitation',
        amount: '40000000.00',
        currency: 'BTN',
        documentType: 'Contract Payment Cert',
        documentRef: 'CERT-ROADS-THRIMPU-2026',
        remarks: 'Maintenance of main arterial roads in Thimphu city',
      },
      {
        id: 'SOL-004-002',
        expenditureCategory: 'Subsidy & Transfer',
        ucoaCode: '7100-02',
        description: 'Waste management and sanitation services',
        amount: '25000000.00',
        currency: 'BTN',
        documentType: 'Invoice',
        documentRef: 'INV-WASTE-THRIMPU-2026-Q2',
        remarks: 'Operational grant for solid waste management',
      },
      {
        id: 'SOL-004-003',
        expenditureCategory: 'Subsidy & Transfer',
        ucoaCode: '7200-03',
        description: 'Municipal administration and support services',
        amount: '20000000.00',
        currency: 'BTN',
        documentType: 'Receipt',
        documentRef: 'RCP-MUNICIPAL-GRANT-2026',
        remarks: 'Administrative grant transfer',
      },
    ],
    validationChecks: [
      {
        key: 'budget-check',
        label: 'Budget Availability Check',
        passed: true,
        message: 'Grant allocation confirmed in BH-3200-05-02',
        status: 'Passed',
      },
      {
        key: 'duplicate-check',
        label: 'Duplicate Transfer Check',
        passed: true,
        message: 'No previous grants this period',
        status: 'Passed',
      },
      {
        key: 'ceiling-check',
        label: 'Expenditure Ceiling Check',
        passed: true,
        message: 'Within grant disbursement ceiling',
        status: 'Passed',
      },
      {
        key: 'signatory-check',
        label: 'Authorised Signatory Check',
        passed: true,
        message: 'Signed by Ministry of Finance authorized officials',
        status: 'Passed',
      },
      {
        key: 'document-check',
        label: 'Supporting Document Completeness',
        passed: true,
        message: 'Grant agreement and utilization plan attached',
        status: 'Passed',
      },
    ],
    approvals: [
      {
        id: 'APR-004-001',
        level: 'Agency Finance',
        actor: 'Kinley Dorji',
        decidedAt: '2026-04-09T13:30:00Z',
        decision: 'Approved',
        remarks: 'Financial review completed, documents in order',
      },
      {
        id: 'APR-004-002',
        level: 'Budget Division',
        actor: 'Yeshi Tshomo',
        decidedAt: '2026-04-10T10:00:00Z',
        decision: 'Approved',
        remarks: 'Budget Division approval confirmed',
      },
      {
        id: 'APR-004-003',
        level: 'DPA Director',
        actor: 'Karma Jamtsho',
        decidedAt: '2026-04-10T14:15:00Z',
        decision: 'Approved',
        remarks: 'Director approval for disbursement',
      },
    ],
    releases: [],
    reconciliation: [],
    createdAt: '2026-04-08T07:30:00Z',
    updatedAt: '2026-04-10T14:15:00Z',
  },

  // 5. Loan Proceeds Transfer - Ministry of Works (Released)
  {
    id: 'SOE-2026-005',
    header: {
      transferId: 'TXN-MOW-2026-0505',
      transferType: 'Loan Proceeds Transfer',
      direction: 'Inward',
      sourceOfFund: 'Donor Trust Fund',
      destinationAccountType: 'Project Account',
      originatingAgency: 'Asian Development Bank',
      receivingAgency: 'Ministry of Works and Human Settlement',
      parliamentSanctionRef: 'PS/2025-2026/MOW-04',
      budgetHeadCode: 'BH-4100-03-01',
      currency: 'USD',
      exchangeRate: '130.50',
      totalAmount: '50000000.00',
      valueDate: '2026-04-05',
      reportingFrequency: 'Quarterly',
      expenditureCategory: 'Capital Expenditure',
      transferStatus: 'Released',
      narrative: 'ADB loan proceeds for road sector modernization and bridge construction projects',
    },
    soeLines: [
      {
        id: 'SOL-005-001',
        expenditureCategory: 'Capital Expenditure',
        ucoaCode: '6300-01',
        description: 'Highway modernization - Paro to Thimphu corridor',
        amount: '30000000.00',
        currency: 'USD',
        documentType: 'Contract Payment Cert',
        documentRef: 'CERT-ROAD-MODERNIZE-2026',
        remarks: 'ADB loan funded infrastructure development',
      },
      {
        id: 'SOL-005-002',
        expenditureCategory: 'Capital Expenditure',
        ucoaCode: '6400-02',
        description: 'Bridge construction and rehabilitation',
        amount: '15000000.00',
        currency: 'USD',
        documentType: 'Invoice',
        documentRef: 'INV-BRIDGE-2026-ADB',
        remarks: 'Multi-bridge rehabilitation project',
      },
      {
        id: 'SOL-005-003',
        expenditureCategory: 'Capital Expenditure',
        ucoaCode: '6500-03',
        description: 'Project management and supervision',
        amount: '5000000.00',
        currency: 'USD',
        documentType: 'Invoice',
        documentRef: 'INV-PROJ-MGMT-2026',
        remarks: 'Technical assistance and project oversight',
      },
    ],
    validationChecks: [
      {
        key: 'budget-check',
        label: 'Budget Availability Check',
        passed: true,
        message: 'Loan facility confirmed in BH-4100-03-01',
        status: 'Passed',
      },
      {
        key: 'duplicate-check',
        label: 'Duplicate Transfer Check',
        passed: true,
        message: 'No duplicate loan disbursements',
        status: 'Passed',
      },
      {
        key: 'ceiling-check',
        label: 'Expenditure Ceiling Check',
        passed: true,
        message: 'Within project loan limit',
        status: 'Passed',
      },
      {
        key: 'signatory-check',
        label: 'Authorised Signatory Check',
        passed: true,
        message: 'ADB disbursement authorized',
        status: 'Passed',
      },
      {
        key: 'document-check',
        label: 'Supporting Document Completeness',
        passed: true,
        message: 'Loan agreement and disbursement certificate attached',
        status: 'Passed',
      },
    ],
    approvals: [
      {
        id: 'APR-005-001',
        level: 'Agency Finance',
        actor: 'Damchoe Penjor',
        decidedAt: '2026-04-03T10:00:00Z',
        decision: 'Approved',
        remarks: 'MOW finance team confirmed loan utilization',
      },
      {
        id: 'APR-005-002',
        level: 'Budget Division',
        actor: 'Sonam Wangdi',
        decidedAt: '2026-04-03T15:30:00Z',
        decision: 'Approved',
        remarks: 'Budget Division approved loan disbursement',
      },
      {
        id: 'APR-005-003',
        level: 'DPA Director',
        actor: 'Karma Jamtsho',
        decidedAt: '2026-04-04T09:00:00Z',
        decision: 'Approved',
        remarks: 'Director approved fund release',
      },
      {
        id: 'APR-005-004',
        level: 'Finance Secretary',
        actor: 'Lyonpo Tandin Dorji',
        decidedAt: '2026-04-04T16:45:00Z',
        decision: 'Approved',
        remarks: 'Finance Secretary approved disbursement',
      },
    ],
    releases: [
      {
        id: 'REL-005-001',
        channel: 'RTGS',
        releasedAt: '2026-04-05T08:30:00Z',
        releasedBy: 'Sangay Tshomo',
        bankReference: 'RTGS-MOW-2026-0405-USD',
        amount: '50000000.00',
        currency: 'USD',
        remarks: 'Released via RTGS to ADB project account',
      },
    ],
    reconciliation: [],
    createdAt: '2026-04-03T08:00:00Z',
    updatedAt: '2026-04-05T08:30:00Z',
  },

  // 6. Budget Release - Ministry of Agriculture (Reconciled)
  {
    id: 'SOE-2026-006',
    header: {
      transferId: 'TXN-MOA-2026-0506',
      transferType: 'Budget Release',
      direction: 'Outward',
      sourceOfFund: 'Consolidated Fund',
      destinationAccountType: 'Operating Account',
      originatingAgency: 'Ministry of Finance',
      receivingAgency: 'Ministry of Agriculture and Forests',
      parliamentSanctionRef: 'PS/2025-2026/MOA-02',
      budgetHeadCode: 'BH-2200-02-02',
      currency: 'BTN',
      exchangeRate: '1.00',
      totalAmount: '65000000.00',
      valueDate: '2026-03-01',
      reportingFrequency: 'Quarterly',
      expenditureCategory: 'Current Expenditure',
      transferStatus: 'Reconciled',
      narrative: 'Q1 budget release for agriculture extension services and livestock development',
    },
    soeLines: [
      {
        id: 'SOL-006-001',
        expenditureCategory: 'Current Expenditure',
        ucoaCode: '5500-01',
        description: 'Agriculture extension worker allowances and incentives',
        amount: '30000000.00',
        currency: 'BTN',
        documentType: 'Utility Bill',
        documentRef: 'SALARY-AGR-EXT-2026-Q1',
        remarks: 'Remuneration for field officers across dzongkhags',
      },
      {
        id: 'SOL-006-002',
        expenditureCategory: 'Current Expenditure',
        ucoaCode: '5600-02',
        description: 'Livestock vaccination and veterinary services',
        amount: '20000000.00',
        currency: 'BTN',
        documentType: 'Invoice',
        documentRef: 'INV-VET-SERVICES-2026-Q1',
        remarks: 'Animal health programs nationwide',
      },
      {
        id: 'SOL-006-003',
        expenditureCategory: 'Current Expenditure',
        ucoaCode: '5700-03',
        description: 'Seeds and fertilizer distribution program',
        amount: '15000000.00',
        currency: 'BTN',
        documentType: 'Receipt',
        documentRef: 'RCP-SEEDS-FERT-2026-Q1',
        remarks: 'Agricultural input support to farmers',
      },
    ],
    validationChecks: [
      {
        key: 'budget-check',
        label: 'Budget Availability Check',
        passed: true,
        message: 'Budget confirmed in BH-2200-02-02',
        status: 'Passed',
      },
      {
        key: 'duplicate-check',
        label: 'Duplicate Transfer Check',
        passed: true,
        message: 'No duplicates identified',
        status: 'Passed',
      },
      {
        key: 'ceiling-check',
        label: 'Expenditure Ceiling Check',
        passed: true,
        message: 'Within quarterly ceiling',
        status: 'Passed',
      },
      {
        key: 'signatory-check',
        label: 'Authorised Signatory Check',
        passed: true,
        message: 'Authorized and signed',
        status: 'Passed',
      },
      {
        key: 'document-check',
        label: 'Supporting Document Completeness',
        passed: true,
        message: 'All documents provided',
        status: 'Passed',
      },
    ],
    approvals: [
      {
        id: 'APR-006-001',
        level: 'Agency Finance',
        actor: 'Dorji Wangchuk',
        decidedAt: '2026-02-28T11:00:00Z',
        decision: 'Approved',
        remarks: 'Finance section approved',
      },
      {
        id: 'APR-006-002',
        level: 'Budget Division',
        actor: 'Yeshi Tshomo',
        decidedAt: '2026-02-28T14:30:00Z',
        decision: 'Approved',
        remarks: 'Budget division approved',
      },
      {
        id: 'APR-006-003',
        level: 'DPA Director',
        actor: 'Karma Jamtsho',
        decidedAt: '2026-03-01T09:15:00Z',
        decision: 'Approved',
        remarks: 'Director approved release',
      },
      {
        id: 'APR-006-004',
        level: 'Finance Secretary',
        actor: 'Lyonpo Tandin Dorji',
        decidedAt: '2026-03-01T10:00:00Z',
        decision: 'Approved',
        remarks: 'Finance Secretary approved',
      },
    ],
    releases: [
      {
        id: 'REL-006-001',
        channel: 'NEFT',
        releasedAt: '2026-03-01T09:45:00Z',
        releasedBy: 'Sonam Choden',
        bankReference: 'NEFT-MOA-2026-0301-001',
        amount: '65000000.00',
        currency: 'BTN',
        remarks: 'Released to MOA operating account via NEFT',
      },
    ],
    reconciliation: [
      {
        id: 'RECON-006-001',
        status: 'Matched',
        reconciledAt: '2026-04-05T16:30:00Z',
        reconciledBy: 'Pema Tshering',
        bankStatementRef: 'BANK-STMT-MOA-2026-03',
        variance: '0.00',
        notes: 'Bank statement fully reconciled with SOE records',
      },
    ],
    createdAt: '2026-02-27T08:00:00Z',
    updatedAt: '2026-04-05T16:30:00Z',
  },

  // 7. Inter-Agency Transfer - Haa Dzongkhag (Draft)
  {
    id: 'SOE-2026-007',
    header: {
      transferId: 'TXN-HAA-2026-0507',
      transferType: 'Inter-Agency Transfer',
      direction: 'Inward',
      sourceOfFund: 'Revenue Account',
      destinationAccountType: 'Operating Account',
      originatingAgency: 'Ministry of Finance - Revenue Division',
      receivingAgency: 'Haa Dzongkhag Administration',
      parliamentSanctionRef: 'PS/2025-2026/HAA-01',
      budgetHeadCode: 'BH-3100-04-01',
      currency: 'BTN',
      exchangeRate: '1.00',
      totalAmount: '18000000.00',
      valueDate: '2026-04-12',
      reportingFrequency: 'Monthly',
      expenditureCategory: 'Current Expenditure',
      transferStatus: 'Draft',
      narrative: 'Inter-agency transfer of revenue proceeds to support local administration and development programs',
    },
    soeLines: [
      {
        id: 'SOL-007-001',
        expenditureCategory: 'Current Expenditure',
        ucoaCode: '5800-01',
        description: 'Local administration staff salaries',
        amount: '10000000.00',
        currency: 'BTN',
        documentType: 'Utility Bill',
        documentRef: 'SALARY-HAA-ADMIN-2026-Q2',
        remarks: 'Dzongkhag administrative staff remuneration',
      },
      {
        id: 'SOL-007-002',
        expenditureCategory: 'Current Expenditure',
        ucoaCode: '5900-02',
        description: 'Local development and community services',
        amount: '5000000.00',
        currency: 'BTN',
        documentType: 'Purchase Order',
        documentRef: 'PO-HAA-COMMUNITY-2026',
        remarks: 'Community development activities',
      },
      {
        id: 'SOL-007-003',
        expenditureCategory: 'Current Expenditure',
        ucoaCode: '6000-03',
        description: 'Administrative operational expenses',
        amount: '3000000.00',
        currency: 'BTN',
        documentType: 'Invoice',
        documentRef: 'INV-HAA-OPERATIONS-2026',
        remarks: 'Office supplies and operational costs',
      },
    ],
    validationChecks: [
      {
        key: 'budget-check',
        label: 'Budget Availability Check',
        passed: true,
        message: 'Revenue available for allocation',
        status: 'Passed',
      },
      {
        key: 'duplicate-check',
        label: 'Duplicate Transfer Check',
        passed: true,
        message: 'No duplicate transfers detected',
        status: 'Passed',
      },
      {
        key: 'ceiling-check',
        label: 'Expenditure Ceiling Check',
        passed: true,
        message: 'Within revenue allocation limits',
        status: 'Passed',
      },
      {
        key: 'signatory-check',
        label: 'Authorised Signatory Check',
        passed: false,
        message: 'Awaiting approval from DPA Director',
        status: 'Pending',
      },
      {
        key: 'document-check',
        label: 'Supporting Document Completeness',
        passed: true,
        message: 'Required documents submitted',
        status: 'Passed',
      },
    ],
    approvals: [],
    releases: [],
    reconciliation: [],
    createdAt: '2026-04-09T13:00:00Z',
    updatedAt: '2026-04-09T13:00:00Z',
  },

  // 8. Fund Replenishment - Trashigang Dzongkhag (Approved)
  {
    id: 'SOE-2026-008',
    header: {
      transferId: 'TXN-TRASH-2026-0508',
      transferType: 'Fund Replenishment',
      direction: 'Inward',
      sourceOfFund: 'Consolidated Fund',
      destinationAccountType: 'Imprest Account',
      originatingAgency: 'Ministry of Finance',
      receivingAgency: 'Trashigang Dzongkhag Administration',
      parliamentSanctionRef: 'PS/2025-2026/TRASH-03',
      budgetHeadCode: 'BH-3100-04-02',
      currency: 'BTN',
      exchangeRate: '1.00',
      totalAmount: '12000000.00',
      valueDate: '2026-04-14',
      reportingFrequency: 'Monthly',
      expenditureCategory: 'Current Expenditure',
      transferStatus: 'Approved',
      narrative: 'Replenishment of Trashigang imprest account for emergency and contingency expenditures',
    },
    soeLines: [
      {
        id: 'SOL-008-001',
        expenditureCategory: 'Current Expenditure',
        ucoaCode: '6100-01',
        description: 'Emergency and contingency fund',
        amount: '8000000.00',
        currency: 'BTN',
        documentType: 'Receipt',
        documentRef: 'RCP-EMERG-TRASH-2026',
        remarks: 'Previously advanced funds replenishment',
      },
      {
        id: 'SOL-008-002',
        expenditureCategory: 'Current Expenditure',
        ucoaCode: '6200-02',
        description: 'Petty cash replenishment',
        amount: '4000000.00',
        currency: 'BTN',
        documentType: 'Receipt',
        documentRef: 'RCP-PETTY-TRASH-2026',
        remarks: 'Daily operational petty cash',
      },
    ],
    validationChecks: [
      {
        key: 'budget-check',
        label: 'Budget Availability Check',
        passed: true,
        message: 'Budget confirmed for replenishment',
        status: 'Passed',
      },
      {
        key: 'duplicate-check',
        label: 'Duplicate Transfer Check',
        passed: true,
        message: 'Previous imprest settled',
        status: 'Passed',
      },
      {
        key: 'ceiling-check',
        label: 'Expenditure Ceiling Check',
        passed: true,
        message: 'Within imprest ceiling',
        status: 'Passed',
      },
      {
        key: 'signatory-check',
        label: 'Authorised Signatory Check',
        passed: true,
        message: 'Signed by authorized officials',
        status: 'Passed',
      },
      {
        key: 'document-check',
        label: 'Supporting Document Completeness',
        passed: true,
        message: 'Imprest account records attached',
        status: 'Passed',
      },
    ],
    approvals: [
      {
        id: 'APR-008-001',
        level: 'Agency Finance',
        actor: 'Kinley Dorji',
        decidedAt: '2026-04-09T10:30:00Z',
        decision: 'Approved',
        remarks: 'Finance review completed',
      },
      {
        id: 'APR-008-002',
        level: 'Budget Division',
        actor: 'Sonam Wangdi',
        decidedAt: '2026-04-09T15:00:00Z',
        decision: 'Approved',
        remarks: 'Budget Division approval',
      },
      {
        id: 'APR-008-003',
        level: 'DPA Director',
        actor: 'Karma Jamtsho',
        decidedAt: '2026-04-10T09:00:00Z',
        decision: 'Approved',
        remarks: 'Director approved replenishment',
      },
    ],
    releases: [],
    reconciliation: [],
    createdAt: '2026-04-08T14:00:00Z',
    updatedAt: '2026-04-10T09:00:00Z',
  },

  // 9. Grant Disbursement - Ministry of Information and Communications (Submitted)
  {
    id: 'SOE-2026-009',
    header: {
      transferId: 'TXN-MIC-2026-0509',
      transferType: 'Grant Disbursement',
      direction: 'Outward',
      sourceOfFund: 'Consolidated Fund',
      destinationAccountType: 'Operating Account',
      originatingAgency: 'Ministry of Finance',
      receivingAgency: 'Ministry of Information and Communications',
      parliamentSanctionRef: 'PS/2025-2026/MIC-01',
      budgetHeadCode: 'BH-2800-02-01',
      currency: 'BTN',
      exchangeRate: '1.00',
      totalAmount: '38000000.00',
      valueDate: '2026-04-16',
      reportingFrequency: 'Quarterly',
      expenditureCategory: 'Current Expenditure',
      transferStatus: 'Submitted',
      narrative: 'Grant disbursement for digital infrastructure, media services, and communication technology initiatives',
    },
    soeLines: [
      {
        id: 'SOL-009-001',
        expenditureCategory: 'Current Expenditure',
        ucoaCode: '5200-01',
        description: 'Broadcasting equipment and infrastructure maintenance',
        amount: '18000000.00',
        currency: 'BTN',
        documentType: 'Invoice',
        documentRef: 'INV-BROADCAST-2026-Q2',
        remarks: 'BBS transmission equipment maintenance',
      },
      {
        id: 'SOL-009-002',
        expenditureCategory: 'Current Expenditure',
        ucoaCode: '5300-02',
        description: 'Digital platform development and IT services',
        amount: '12000000.00',
        currency: 'BTN',
        documentType: 'Invoice',
        documentRef: 'INV-DIGITAL-MIC-2026',
        remarks: 'E-governance and digital communication platform',
      },
      {
        id: 'SOL-009-003',
        expenditureCategory: 'Current Expenditure',
        ucoaCode: '5400-03',
        description: 'Staff and operational costs',
        amount: '8000000.00',
        currency: 'BTN',
        documentType: 'Utility Bill',
        documentRef: 'SALARY-MIC-2026-Q2',
        remarks: 'Administrative and technical staff expenses',
      },
    ],
    validationChecks: [
      {
        key: 'budget-check',
        label: 'Budget Availability Check',
        passed: true,
        message: 'Budget available in BH-2800-02-01',
        status: 'Passed',
      },
      {
        key: 'duplicate-check',
        label: 'Duplicate Transfer Check',
        passed: true,
        message: 'No duplicate grants detected',
        status: 'Passed',
      },
      {
        key: 'ceiling-check',
        label: 'Expenditure Ceiling Check',
        passed: true,
        message: 'Within grant ceiling',
        status: 'Passed',
      },
      {
        key: 'signatory-check',
        label: 'Authorised Signatory Check',
        passed: true,
        message: 'Signed by authorized officials',
        status: 'Passed',
      },
      {
        key: 'document-check',
        label: 'Supporting Document Completeness',
        passed: true,
        message: 'All documents provided',
        status: 'Passed',
      },
    ],
    approvals: [
      {
        id: 'APR-009-001',
        level: 'Agency Finance',
        actor: 'Tenzin Dorji',
        decidedAt: '2026-04-09T12:00:00Z',
        decision: 'Approved',
        remarks: 'Finance section verified',
      },
    ],
    releases: [],
    reconciliation: [],
    createdAt: '2026-04-08T11:30:00Z',
    updatedAt: '2026-04-09T12:00:00Z',
  },

  // 10. Loan Proceeds Transfer - Ministry of Power (Released and Reconciled)
  {
    id: 'SOE-2026-010',
    header: {
      transferId: 'TXN-MOP-2026-0510',
      transferType: 'Loan Proceeds Transfer',
      direction: 'Inward',
      sourceOfFund: 'Donor Trust Fund',
      destinationAccountType: 'Project Account',
      originatingAgency: 'World Bank',
      receivingAgency: 'Ministry of Power and Energy',
      parliamentSanctionRef: 'PS/2025-2026/MOP-02',
      budgetHeadCode: 'BH-4200-02-02',
      currency: 'EUR',
      exchangeRate: '145.75',
      totalAmount: '32000000.00',
      valueDate: '2026-02-15',
      reportingFrequency: 'Quarterly',
      expenditureCategory: 'Capital Expenditure',
      transferStatus: 'Reconciled',
      narrative: 'World Bank loan for hydroelectric power plant rehabilitation and renewable energy projects',
    },
    soeLines: [
      {
        id: 'SOL-010-001',
        expenditureCategory: 'Capital Expenditure',
        ucoaCode: '6600-01',
        description: 'Hydroelectric plant turbine upgrade and refurbishment',
        amount: '18000000.00',
        currency: 'EUR',
        documentType: 'Contract Payment Cert',
        documentRef: 'CERT-HYDRO-UPGRADE-2026',
        remarks: 'Major equipment replacement project',
      },
      {
        id: 'SOL-010-002',
        expenditureCategory: 'Capital Expenditure',
        ucoaCode: '6700-02',
        description: 'Renewable energy research and development',
        amount: '8000000.00',
        currency: 'EUR',
        documentType: 'Invoice',
        documentRef: 'INV-RENEWABLE-MOP-2026',
        remarks: 'Solar and wind energy pilot programs',
      },
      {
        id: 'SOL-010-003',
        expenditureCategory: 'Capital Expenditure',
        ucoaCode: '6800-03',
        description: 'Grid infrastructure development and training',
        amount: '6000000.00',
        currency: 'EUR',
        documentType: 'Invoice',
        documentRef: 'INV-GRID-TRAINING-2026',
        remarks: 'Smart grid technology implementation',
      },
    ],
    validationChecks: [
      {
        key: 'budget-check',
        label: 'Budget Availability Check',
        passed: true,
        message: 'Loan facility confirmed',
        status: 'Passed',
      },
      {
        key: 'duplicate-check',
        label: 'Duplicate Transfer Check',
        passed: true,
        message: 'No duplicates',
        status: 'Passed',
      },
      {
        key: 'ceiling-check',
        label: 'Expenditure Ceiling Check',
        passed: true,
        message: 'Within limit',
        status: 'Passed',
      },
      {
        key: 'signatory-check',
        label: 'Authorised Signatory Check',
        passed: true,
        message: 'World Bank authorization confirmed',
        status: 'Passed',
      },
      {
        key: 'document-check',
        label: 'Supporting Document Completeness',
        passed: true,
        message: 'All documents provided',
        status: 'Passed',
      },
    ],
    approvals: [
      {
        id: 'APR-010-001',
        level: 'Agency Finance',
        actor: 'Damchoe Penjor',
        decidedAt: '2026-02-10T09:30:00Z',
        decision: 'Approved',
        remarks: 'MOP finance team approved loan utilization',
      },
      {
        id: 'APR-010-002',
        level: 'Budget Division',
        actor: 'Yeshi Tshomo',
        decidedAt: '2026-02-10T14:00:00Z',
        decision: 'Approved',
        remarks: 'Budget Division approved',
      },
      {
        id: 'APR-010-003',
        level: 'DPA Director',
        actor: 'Karma Jamtsho',
        decidedAt: '2026-02-11T10:15:00Z',
        decision: 'Approved',
        remarks: 'Director approved release',
      },
      {
        id: 'APR-010-004',
        level: 'Finance Secretary',
        actor: 'Lyonpo Tandin Dorji',
        decidedAt: '2026-02-11T15:30:00Z',
        decision: 'Approved',
        remarks: 'Finance Secretary approved',
      },
    ],
    releases: [
      {
        id: 'REL-010-001',
        channel: 'RTGS',
        releasedAt: '2026-02-15T09:00:00Z',
        releasedBy: 'Sangay Tshomo',
        bankReference: 'RTGS-MOP-2026-0215-EUR',
        amount: '32000000.00',
        currency: 'EUR',
        remarks: 'Released to World Bank project account via RTGS',
      },
    ],
    reconciliation: [
      {
        id: 'RECON-010-001',
        status: 'Matched',
        reconciledAt: '2026-04-06T14:20:00Z',
        reconciledBy: 'Pema Tshering',
        bankStatementRef: 'BANK-STMT-MOP-2026-02',
        variance: '0.00',
        notes: 'Bank statement fully matched with SOE records, all transactions accounted for',
      },
    ],
    createdAt: '2026-02-10T08:00:00Z',
    updatedAt: '2026-04-06T14:20:00Z',
  },
];
