/* ═══════════════════════════════════════════════════════════════════════════
   Retention Money — Seed Data (SRS PRN 9.1 – 9.3)
   Agency-aware demo records for MoF (16), MoH (20), GovTech (70)
   ═══════════════════════════════════════════════════════════════════════════ */
import type { RetentionRecord, RetentionActionForm, RetentionStep } from "../types";

/* ── Demo retention records ─────────────────────────────────────────────── */
export const RETENTION_SEED: RetentionRecord[] = [
  /* ── MoF (16) ─────────────────────────────────────────────────────────── */
  {
    id: "RET-MOF-001",
    contractId: "CTR-WRK-2025-MOF01",
    contractTitle: "MoF HQ Building Renovation Phase II",
    contractorId: "CTR-BIZ-2026-0001",
    contractorName: "Lhaki Construction Pvt Ltd",
    agencyCode: "16",
    agencyName: "Ministry of Finance",
    workId: "WRK-MOF-2025-001",
    contractCategory: "Works",
    contractValue: 45_000_000,
    retentionPct: 10,
    totalRetention: 4_500_000,
    releasedAmount: 0,
    forfeitedAmount: 0,
    balanceRetention: 4_500_000,
    contractStartDate: "2025-03-01",
    contractEndDate: "2026-02-28",
    dlpExpiryDate: "2027-02-28",
    dlpStatus: "active",
    releaseDate: "2027-02-28",
    status: "held",
    nonCfAccountRef: "NCF-MOF-RET-001",
    remarks: "Retention held per PRR — 10% of each running bill",
    billCount: 6,
    currency: "Nu",
  },
  {
    id: "RET-MOF-002",
    contractId: "CTR-WRK-2024-MOF05",
    contractTitle: "Revenue & Customs Office Extension",
    contractorId: "CTR-BIZ-2026-0003",
    contractorName: "Druk Green Construction",
    agencyCode: "16",
    agencyName: "Ministry of Finance",
    workId: "WRK-MOF-2024-005",
    contractCategory: "Works",
    contractValue: 28_000_000,
    retentionPct: 10,
    totalRetention: 2_800_000,
    releasedAmount: 1_400_000,
    forfeitedAmount: 0,
    balanceRetention: 1_400_000,
    contractStartDate: "2024-06-01",
    contractEndDate: "2025-05-31",
    dlpExpiryDate: "2026-05-31",
    dlpStatus: "active",
    releaseDate: "2026-05-31",
    status: "partial-release",
    nonCfAccountRef: "NCF-MOF-RET-005",
    bankGuaranteeRef: "BG-BOB-2024-1234",
    bankGuaranteeAmount: 1_400_000,
    remarks: "50% released via early encashment against Bank Guarantee",
    lastAction: "early-encashment",
    lastActionDate: "2025-12-15",
    billCount: 8,
    currency: "Nu",
  },
  {
    id: "RET-MOF-003",
    contractId: "CTR-WRK-2023-MOF12",
    contractTitle: "Treasury Building Waterproofing",
    contractorId: "CTR-BIZ-2026-0005",
    contractorName: "Tashi Builders & Co",
    agencyCode: "16",
    agencyName: "Ministry of Finance",
    workId: "WRK-MOF-2023-012",
    contractCategory: "Works",
    contractValue: 8_500_000,
    retentionPct: 10,
    totalRetention: 850_000,
    releasedAmount: 0,
    forfeitedAmount: 850_000,
    balanceRetention: 0,
    contractStartDate: "2023-09-01",
    contractEndDate: "2024-06-30",
    dlpExpiryDate: "2025-06-30",
    dlpStatus: "expired",
    releaseDate: "2025-06-30",
    status: "forfeited",
    nonCfAccountRef: "NCF-MOF-RET-012",
    remarks: "Forfeited — contractor failed to rectify waterproofing defects during DLP",
    lastAction: "forfeit",
    lastActionDate: "2025-07-15",
    billCount: 4,
    currency: "Nu",
  },

  /* ── MoH (20) ─────────────────────────────────────────────────────────── */
  {
    id: "RET-MOH-001",
    contractId: "CTR-WRK-2025-MOH01",
    contractTitle: "Jigme Dorji Wangchuck National Referral Hospital — ICU Expansion",
    contractorId: "CTR-BIZ-2026-0002",
    contractorName: "Bhutan Buildcon Pvt Ltd",
    agencyCode: "20",
    agencyName: "Ministry of Health",
    workId: "WRK-MOH-2025-001",
    contractCategory: "Works",
    contractValue: 62_000_000,
    retentionPct: 10,
    totalRetention: 6_200_000,
    releasedAmount: 0,
    forfeitedAmount: 0,
    balanceRetention: 6_200_000,
    contractStartDate: "2025-01-15",
    contractEndDate: "2026-06-30",
    dlpExpiryDate: "2027-06-30",
    dlpStatus: "active",
    releaseDate: "2027-06-30",
    status: "held",
    nonCfAccountRef: "NCF-MOH-RET-001",
    remarks: "Major works — retention held per PRR 10% per bill",
    billCount: 5,
    currency: "Nu",
  },
  {
    id: "RET-MOH-002",
    contractId: "CTR-WRK-2024-MOH03",
    contractTitle: "Punakha District Hospital Renovation",
    contractorId: "CTR-BIZ-2026-0006",
    contractorName: "Pelden Construction",
    agencyCode: "20",
    agencyName: "Ministry of Health",
    workId: "WRK-MOH-2024-003",
    contractCategory: "Works",
    contractValue: 18_500_000,
    retentionPct: 10,
    totalRetention: 1_850_000,
    releasedAmount: 1_850_000,
    forfeitedAmount: 0,
    balanceRetention: 0,
    contractStartDate: "2024-03-01",
    contractEndDate: "2025-01-31",
    dlpExpiryDate: "2026-01-31",
    dlpStatus: "expired",
    releaseDate: "2026-01-31",
    status: "released",
    nonCfAccountRef: "NCF-MOH-RET-003",
    remarks: "Full retention released — DLP expired with no defects reported",
    lastAction: "make-payment",
    lastActionDate: "2026-02-10",
    billCount: 7,
    currency: "Nu",
  },

  /* ── GovTech (70) ─────────────────────────────────────────────────────── */
  {
    id: "RET-GT-001",
    contractId: "CTR-WRK-2025-GT01",
    contractTitle: "GovTech Data Centre Civil Works",
    contractorId: "CTR-BIZ-2026-0004",
    contractorName: "Yangphel Construction Co",
    agencyCode: "70",
    agencyName: "GovTech Agency",
    workId: "WRK-GT-2025-001",
    contractCategory: "Works",
    contractValue: 35_000_000,
    retentionPct: 10,
    totalRetention: 3_500_000,
    releasedAmount: 0,
    forfeitedAmount: 0,
    balanceRetention: 3_500_000,
    contractStartDate: "2025-04-01",
    contractEndDate: "2026-09-30",
    dlpExpiryDate: "2027-09-30",
    dlpStatus: "active",
    releaseDate: "2027-09-30",
    status: "held",
    nonCfAccountRef: "NCF-GT-RET-001",
    remarks: "Active works contract — retention accumulating",
    billCount: 3,
    currency: "Nu",
  },
  {
    id: "RET-GT-002",
    contractId: "CTR-WRK-2024-GT04",
    contractTitle: "Thimphu TechPark Perimeter Wall Construction",
    contractorId: "CTR-BIZ-2026-0007",
    contractorName: "Norbu & Sons Builders",
    agencyCode: "70",
    agencyName: "GovTech Agency",
    workId: "WRK-GT-2024-004",
    contractCategory: "Works",
    contractValue: 12_000_000,
    retentionPct: 10,
    totalRetention: 1_200_000,
    releasedAmount: 0,
    forfeitedAmount: 0,
    balanceRetention: 1_200_000,
    contractStartDate: "2024-07-01",
    contractEndDate: "2025-03-31",
    dlpExpiryDate: "2026-03-31",
    dlpStatus: "expired",
    releaseDate: "2026-03-31",
    status: "pending-action",
    nonCfAccountRef: "NCF-GT-RET-004",
    remarks: "DLP expired — awaiting action (payment / forfeit / early encashment)",
    billCount: 5,
    currency: "Nu",
  },
];

/* ── Initial action form ────────────────────────────────────────────────── */
export const INITIAL_ACTION_FORM: RetentionActionForm = {
  action: "",
  contractStatus: "",
  remarks: "",
  paymentType: "",
  deductionAmount: 0,
  defectRemarks: "",
  bankGuaranteeVerified: false,
  bankGuaranteeAmount: 0,
};

/* ── Initial step ───────────────────────────────────────────────────────── */
export const INITIAL_STEP: RetentionStep = "select-contract";

/* ── localStorage helpers ───────────────────────────────────────────────── */
export const RETENTION_STORAGE_KEY = "ifmis_retention_records";

export function loadRetentionRecords(): RetentionRecord[] {
  try {
    const raw = window.localStorage.getItem(RETENTION_STORAGE_KEY);
    if (raw) return JSON.parse(raw) as RetentionRecord[];
  } catch { /* ignore */ }
  return [...RETENTION_SEED];
}
