/* ═══════════════════════════════════════════════════════════════════════════
   Debt Payment Management — SRS PRN 6.1
   ──────────────────────────────────────
   Process Descriptions rows 81-90:
     Step 1.0  Debt Servicing Data Integration  (User + System)
     Step 2.0  Generate Payment Order            (System / User)
     Step 3.0  Validation Rules for Payment      (System)
     Step 4.0  POST Payment / Meridian Sync     (System + User)
     Step 5.0  Debt Payment Processing          (System)

   Data Dictionary fields covered:
     20.1  Debt_Servicing_ID         (CHAR, system generated)
     20.2  Loan_Instrument_ID        (VARCHAR)
     20.3  Creditor_ID               (CHAR — REF to Contractor / Donor master)
     20.4  Debt_Category             (LoV)
     20.5  Principal Loan_Amount     (DECIMAL)
     20.6  Interest Rate_Amount      (DECIMAL)
     20.7  Due_Date                  (DATE)
     20.8  Payment_Currency_ID       (CHAR — REF to Currency Master)
     20.9  Payment_Status            (LoV)
     20.10 Meridian_Reference_ID     (VARCHAR)
     20.11 Loan Term                 (LoV)
     20.11 Repayment Frequency       (LoV)
     21.11 Amortization Schedule     (LoV)
     20.12 Grace Period              (LoV / DATE)
   ═══════════════════════════════════════════════════════════════════════════ */

/* ── Donor / Lender / Creditor Master (PRN 6.1 Step 1) ──────────────────── */
export interface DonorMaster {
  id: string;                 /* internal record id */
  donorId: string;            /* DN-YYYY-NNNN */
  name: string;
  uniqueIdentificationNo: string;
  creditorType: string;       /* LoV: debt-creditor-type */
  originCountry: string;      /* LoV: country-registration */
  address: string;
  contactName: string;
  contactPhone: string;
  contactEmail: string;
  bankName: string;
  bankAccountNumber: string;
  routingInformation: string;
  swiftCode: string;
  dataSource: string;         /* LoV: debt-data-source */
  meridianLinked: boolean;
  createdAt: string;
}

/* ── Debt Servicing Header (DD 20.1 → 20.12) ──────────────────────────── */
export interface DebtServicingHeader {
  debtServicingId: string;          /* 20.1  System generated DSV-YYYY-NNNN */
  loanInstrumentIdGov: string;      /* 20.2  Loan/Instrument number by government */
  loanInstrumentIdLender: string;   /* 20.2  Loan/Instrument number by lender */
  projectId: string;                /* PRN 6.1 — projectId / project number */
  loanDescription: string;          /* PRN 6.1 — description of loan */
  creditorId: string;               /* 20.3  REF Donor Master */
  creditorName: string;             /*       denormalised for display */
  debtCategory: string;             /* 20.4  LoV: debt-category */
  paymentType: string;              /* PRN 6.1 — Principal / Interest / Composite */
  principalLoanAmount: string;      /* 20.5  DECIMAL */
  interestRate: string;             /* 20.6  DECIMAL (% pa) */
  paymentCurrencyId: string;        /* 20.8  LoV: debt-payment-currency */
  loanTermValue: string;            /* 20.11 numeric tenure */
  loanTermUnit: string;             /* 20.11 LoV: debt-loan-term-unit */
  repaymentFrequency: string;       /* 20.11 LoV: debt-repayment-frequency */
  amortizationSchedule: string;     /* 21.11 LoV: debt-amortization-schedule */
  gracePeriodEnd: string;           /* 20.12 DATE */
  applicableDeduction: string;      /* PRN 6.1 — LoV debt-applicable-deduction */
  meridianReferenceId: string;      /* 20.10 VARCHAR */
  dataSource: string;               /* LoV: debt-data-source */
  paymentStatus: string;            /* 20.9  LoV: debt-payment-status */
}

/* ── Repayment / Payment Order (PRN 6.1 Step 2) ─────────────────────── */
export interface DebtRepayment {
  id: string;
  paymentOrderId: string;            /* PO-YYYY-NNNN */
  debtServicingId: string;           /* FK */
  dueDate: string;                   /* 20.7 */
  amountToPay: string;               /* DECIMAL */
  currency: string;                  /* LoV: debt-payment-currency */
  payeeName: string;                 /* recipient details */
  payeeBankAccount: string;
  payeeRoutingDetails: string;
  sourceOfFund: string;              /* LoV: debt-source-of-fund */
  paymentType: string;               /* LoV: debt-payment-type */
  transmissionChannel: string;       /* LoV: debt-payment-order-channel */
  createdManually: boolean;          /* false → auto-generated by system */
  status: string;                    /* LoV: debt-payment-status */
  remarks: string;
}

/* ── Validation result (PRN 6.1 Step 3) ────────────────────────────── */
export interface DebtValidationCheck {
  key: string;
  label: string;
  passed: boolean;
  message: string;
}

/* ── POST Payment / Meridian sync entry (PRN 6.1 Step 4) ──────────── */
export interface DebtMeridianAction {
  id: string;
  action: string;                    /* LoV: debt-meridian-action */
  performedAt: string;
  performedBy: string;
  notes: string;
}

/* ── Stored debt servicing record (the wizard's whole state) ───────── */
export interface StoredDebt {
  id: string;
  header: DebtServicingHeader;
  donor: DonorMaster | null;
  repayments: DebtRepayment[];
  validationChecks: DebtValidationCheck[];
  meridianLog: DebtMeridianAction[];
  createdAt: string;
  updatedAt: string;
}

/* Form state used by the page wizard. */
export interface DebtFormState {
  header: DebtServicingHeader;
  donor: DonorMaster | null;
  repayments: DebtRepayment[];
  validationChecks: DebtValidationCheck[];
  meridianLog: DebtMeridianAction[];
}

export const initialDonor: DonorMaster = {
  id: "",
  donorId: "",
  name: "",
  uniqueIdentificationNo: "",
  creditorType: "",
  originCountry: "",
  address: "",
  contactName: "",
  contactPhone: "",
  contactEmail: "",
  bankName: "",
  bankAccountNumber: "",
  routingInformation: "",
  swiftCode: "",
  dataSource: "",
  meridianLinked: false,
  createdAt: "",
};

export const initialDebtForm: DebtFormState = {
  header: {
    debtServicingId: "",
    loanInstrumentIdGov: "",
    loanInstrumentIdLender: "",
    projectId: "",
    loanDescription: "",
    creditorId: "",
    creditorName: "",
    debtCategory: "",
    paymentType: "",
    principalLoanAmount: "",
    interestRate: "",
    paymentCurrencyId: "",
    loanTermValue: "",
    loanTermUnit: "",
    repaymentFrequency: "",
    amortizationSchedule: "",
    gracePeriodEnd: "",
    applicableDeduction: "",
    meridianReferenceId: "",
    dataSource: "",
    paymentStatus: "",
  },
  donor: null,
  repayments: [],
  validationChecks: [],
  meridianLog: [],
};
