import { MasterDataGroup } from "../masterData";

export const contractGroups: MasterDataGroup[] = [
  {
    /* SRS Expenditure Module — Data Dictionary field 14.1.22 (Contract_Category)
       cross-referenced with LoV sheet row 84 (Data Field 7.4 — Contract category).
       Canonical Goods / Works / Services taxonomy. The "Mixed" entries reflect
       the SRS LoV row 87 note that one or more values may be selected during
       process mapping. This master data drives the Contract Category filter on
       the Approved Contractors table and the document checklist routing. */
    id: "contractual-type",
    title: "Contractual Type",
    description: "Business contractor registration master data",
    values: ["Works Contractor", "Goods Supplier", "Consultancy Services", "Non-Consultancy Services"]
  },
  {
    id: "contract-category",
    title: "Contract Category",
    description: "SRS DD 14.1.22 / LoV 7.4 — Contract_Category (Goods / Works / Services)",
    values: [
      "Goods",
      "Works",
      "Services",
      "Goods and Services",
      "Works and Goods"
    ]
  },
  {
    /* Alias of Contract Category exposed under the SRS-friendly "Contract Type"
       label so admins searching for either term land on the same canonical
       Goods / Works / Services taxonomy. Kept as a separate group so the two
       can diverge if SRS revisions ever split them. */
    id: "contract-type",
    title: "Contract Type",
    description: "SRS DD 14.1.22 — Contract Type (Goods / Works / Services)",
    values: [
      "Goods",
      "Works",
      "Services"
    ]
  },
  {
    id: "contract-budget-code",
    title: "Contract Budget Code",
    description: "DD 14.1.7 / contract creation funding section",
    values: ["BUD-2026-0045", "BUD-2026-0102", "BUD-2026-0188"]
  },
  {
    id: "contract-sub-sector-id",
    title: "Contract Sub Sector ID",
    description: "DD 14.1.10 / contract creation funding section",
    values: ["GoB", "Donor", "Loan"]
  },
  {
    id: "contract-funding-source",
    title: "Contract Funding Source",
    description: "DD 14.1.11 / LoV 7.2 / contract creation funding section",
    values: ["RGOB", "Donor Agency", "Loan"]
  },
  {
    id: "contract-payment-source",
    title: "Contract Payment Source",
    description: "DD 14.1.13 / LoV 7.3 / contract creation funding section",
    values: ["TSA", "Project Account", "Agency Account"]
  },
  {
    id: "contract-expenditure-type",
    title: "Contract Expenditure Type",
    description: "LoV 7.4 — Type of expenditure for a contract",
    values: ["Expenses", "Non-Financial Assets"]
  },
  {
    id: "contract-classification-type",
    title: "Contract Classification",
    description: "LoV 7.5 — Whether contract spans within or beyond fiscal year",
    values: ["In-Year", "Multi-Year"]
  },
  {
    id: "amendment-origin-type",
    title: "Amendment Origin",
    description: "PRN 2.2 — Who initiated the contract amendment",
    values: ["Contractor-Initiated", "Agency-Initiated"]
  },
  {
    id: "amendment-direction",
    title: "Amendment Direction",
    description: "PRN 2.2 — Whether amendment increases or decreases the value",
    values: ["Increase", "Decrease"]
  },
  {
    id: "milestone-adjustment-type",
    title: "Milestone Adjustment Type",
    description: "PRN 2.2 — Type of adjustment applied to a milestone",
    values: ["Modify Date", "Modify Amount", "Delete Milestone"]
  },
  {
    id: "tax-applicability",
    title: "Tax Applicability",
    description: "DD 14.1.x — Whether tax applies to a line / contract",
    values: ["Tax Applicable", "Tax Exempt"]
  },
  {
    id: "contract-payment-structure",
    title: "Contract Payment Structure",
    description: "Process Desc Step 1 — How contract payments are structured",
    values: ["Milestone Based", "Lump Sum", "Periodic"]
  },
  {
    id: "advance-recovery-schedule",
    title: "Advance Recovery Schedule",
    description: "PRN 2.2 — How advance amounts are recovered from bills",
    values: ["Pro-rata from RA bills", "Lump sum", "Custom schedule"]
  },
  {
    id: "po-cancellation-reason",
    title: "Payment Order Cancellation Reason",
    description: "PRN — Payment Order cancellation reason codes",
    values: [
      "Generated by mistake",
      "Duplicate payment",
      "Invoice dispute",
      "Contractor bank details incorrect",
      "Insufficient funds",
      "Cancelled by user request"
    ]
  },
  {
    id: "closure-reason",
    title: "Contract Closure Reason",
    description: "PRN — Contract closure reason codes",
    values: [
      "Scope completed",
      "Mutual termination",
      "Breach of contract",
      "Force majeure",
      "Budget cancellation",
      "Contractor default"
    ]
  },
  {
    id: "income-tax-rate",
    title: "Income Tax Rate",
    description: "DD 14.1.x — Income tax rate applied to contracts (PIT/BIT/CIT)",
    values: [
      "PIT - Ceiling not exceeding",
      "BIT - 5%",
      "CIT - Standard",
      "Non-Bhutanese Rule"
    ]
  },
  {
    id: "agency-contract-id",
    title: "Agency Contract ID",
    description: "DD 14.1.2 — Agency-assigned contract identifiers (imported from procurement system)",
    values: ["AGY-CTR-001", "AGY-CTR-002", "AGY-CTR-003", "AGY-CTR-004", "AGY-CTR-005"]
  },
  {
    id: "contract-creation-source",
    title: "Contract Creation Source",
    description: "LoV 1.1 — Channel through which contract data is created",
    values: [
      "Manual Entry",
      "Bulk Upload",
      "e-GP (Electronic Government Procurement)",
      "CMS (Contract Management System)",
      "IBLS (Integrated Business Licensing)",
      "BTFN Interface"
    ]
  },
  {
    id: "contractor-source-system",
    title: "Contractor Source System",
    description: "External systems from which contractor profiles may be fetched",
    values: [
      "e-GP (Electronic Government Procurement)",
      "CMS (Contract Management System)",
      "IBLS (Integrated Business Licensing)"
    ]
  }
];
