import {
  StoredSb,
  SbProgramHeader,
  SbBeneficiary,
  SbDeduction,
  SbValidationCheck,
  SbApprovalEntry,
  SbPaymentTransaction,
} from './types';

// Helper function to generate IDs
const generateId = (prefix: string): string => {
  return `${prefix}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
};

// Helper function for Bhutanese date format (YYYY-MM-DD)
const today = new Date().toISOString().split('T')[0];
const pastDate = (days: number): string => {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString().split('T')[0];
};

const futureDate = (days: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
};

export const SEED_SB_RECORDS: StoredSb[] = [
  // 1. National Pension Scheme — Elderly Citizens
  {
    id: generateId('SB'),
    header: {
      sbId: 'PENSION-2024-001',
      programType: 'Pension',
      programName: 'National Pension Scheme for Elderly Citizens',
      programShortName: 'NPS-Elderly',
      programDescription: 'Monthly pension support for Bhutanese citizens aged 65 and above with valid citizenship',
      implementingAgency: 'Ministry of Labour and Human Resources',
      budgetSource: 'RGOB Current Budget',
      budgetCode: 'MLOHR-PENSION-001',
      expenditureType: 'Pension — Monthly',
      paymentAccount: 'Agency Operating Account',
      startDate: '2020-01-15',
      plannedEndDate: '2030-12-31',
      allocatedBudget: '450000000',
      programStatus: 'Active',
    },
    beneficiaries: [
      {
        id: generateId('BEN'),
        beneficiaryType: 'Individual',
        beneficiaryCategory: 'Elderly Citizen',
        cid: '00001-27-0001',
        firstName: 'Tenzin',
        middleName: 'Dorji',
        lastName: 'Tshering',
        nationality: 'Bhutanese',
        gender: 'Male',
        dob: '1955-03-12',
        ageGroup: 'Above 60',
        phoneNumber: '+975-17123456',
        studentCode: '',
        studentCategory: '',
        agencyId: 'MLOHR-001',
        officeId: 'THIMPHU-001',
        bankName: 'Bank of Bhutan',
        bankBranch: 'Thimphu Main Branch',
        bankAccountNo: '1001234567890',
        accountType: 'Savings',
        beneficiaryStatus: 'Active',
        remarks: 'Verified pensioner, eligible for full pension',
      },
      {
        id: generateId('BEN'),
        beneficiaryType: 'Individual',
        beneficiaryCategory: 'Elderly Citizen',
        cid: '00001-27-0002',
        firstName: 'Pema',
        middleName: 'Lhakdrup',
        lastName: 'Wangchuk',
        nationality: 'Bhutanese',
        gender: 'Female',
        dob: '1950-07-22',
        ageGroup: 'Above 60',
        phoneNumber: '+975-17123457',
        studentCode: '',
        studentCategory: '',
        agencyId: 'MLOHR-001',
        officeId: 'PARO-001',
        bankName: 'BNB Bank',
        bankBranch: 'Paro Branch',
        bankAccountNo: '2001234567891',
        accountType: 'Savings',
        beneficiaryStatus: 'Active',
        remarks: 'Widow, eligible for enhanced pension benefit',
      },
      {
        id: generateId('BEN'),
        beneficiaryType: 'Individual',
        beneficiaryCategory: 'Elderly Citizen',
        cid: '00001-27-0003',
        firstName: 'Kinley',
        middleName: 'Norbu',
        lastName: 'Gyeltshen',
        nationality: 'Bhutanese',
        gender: 'Male',
        dob: '1952-11-05',
        ageGroup: 'Above 60',
        phoneNumber: '+975-17123458',
        studentCode: '',
        studentCategory: '',
        agencyId: 'MLOHR-001',
        officeId: 'BUMTHANG-001',
        bankName: 'BDBL Bank',
        bankBranch: 'Bumthang Branch',
        bankAccountNo: '3001234567892',
        accountType: 'Savings',
        beneficiaryStatus: 'Active',
        remarks: 'Ex-serviceperson, receiving pension and ex-serviceperson allowance',
      },
    ],
    deductions: [
      {
        id: generateId('DED'),
        beneficiaryRefId: 'BEN-0001',
        deductionType: 'Insurance Premium',
        amount: '5000',
        recipientBankAccount: 'INSURANCE-POOL-001',
        remarks: 'Health insurance premium deduction',
      },
    ],
    validationChecks: [
      {
        key: 'cid-verification',
        label: 'CID Verification',
        passed: true,
        message: 'All beneficiary CIDs verified with National Population Register',
      },
      {
        key: 'duplicate-check',
        label: 'Duplicate Beneficiary Check',
        passed: true,
        message: 'No duplicate beneficiaries found in database',
      },
      {
        key: 'budget-ceiling',
        label: 'Budget Ceiling Check',
        passed: true,
        message: 'Total allocation within approved budget ceiling',
      },
      {
        key: 'bank-validation',
        label: 'Bank Account Validation',
        passed: true,
        message: 'All bank accounts validated with participating banks',
      },
    ],
    approvals: [
      {
        id: generateId('APR'),
        level: 'Coordinator',
        actor: 'Sonam Penjor',
        decidedAt: pastDate(5),
        decision: 'Approved',
        remarks: 'Data entry and eligibility verification completed',
      },
      {
        id: generateId('APR'),
        level: 'Agency Finance',
        actor: 'Dorji Wangchuk',
        decidedAt: pastDate(3),
        decision: 'Approved',
        remarks: 'Financial compliance check passed',
      },
      {
        id: generateId('APR'),
        level: 'Head of Agency',
        actor: 'Kinzang Dorji',
        decidedAt: pastDate(1),
        decision: 'Approved',
        remarks: 'Approved for payment processing',
      },
    ],
    transactions: [
      {
        id: generateId('TXN'),
        beneficiaryRefId: 'BEN-0001',
        invoiceId: 'INV-PENSION-2024-0001',
        billId: 'BILL-PENSION-2024-0001',
        grossAmount: '10000',
        deductionAmount: '5000',
        netPayableAmount: '5000',
        paymentOrderId: 'PO-PENSION-2024-0001',
        period: '2024-04',
        txnStatus: 'Paid',
        remarks: 'Payment processed successfully',
      },
      {
        id: generateId('TXN'),
        beneficiaryRefId: 'BEN-0002',
        invoiceId: 'INV-PENSION-2024-0002',
        billId: 'BILL-PENSION-2024-0002',
        grossAmount: '12000',
        deductionAmount: '0',
        netPayableAmount: '12000',
        paymentOrderId: 'PO-PENSION-2024-0002',
        period: '2024-04',
        txnStatus: 'Paid',
        remarks: 'Widow pension enhanced amount paid',
      },
    ],
    createdAt: pastDate(30),
    updatedAt: today,
  },

  // 2. Disability Allowance Program
  {
    id: generateId('SB'),
    header: {
      sbId: 'DISABILITY-2024-001',
      programType: 'Disability Allowance',
      programName: 'Disability Allowance Support Program',
      programShortName: 'DAP-2024',
      programDescription: 'Monthly allowance for Bhutanese citizens with registered disabilities',
      implementingAgency: 'Ministry of Health',
      budgetSource: 'RGOB Current Budget',
      budgetCode: 'MOHEALTH-DISABILITY-001',
      expenditureType: 'Social Benefit — Monthly',
      paymentAccount: 'Social Protection Fund',
      startDate: '2022-06-01',
      plannedEndDate: '2027-12-31',
      allocatedBudget: '180000000',
      programStatus: 'Active',
    },
    beneficiaries: [
      {
        id: generateId('BEN'),
        beneficiaryType: 'Individual',
        beneficiaryCategory: 'Person with Disability',
        cid: '00001-28-0001',
        firstName: 'Tenzin',
        middleName: 'Namgyal',
        lastName: 'Dorji',
        nationality: 'Bhutanese',
        gender: 'Male',
        dob: '1985-02-14',
        ageGroup: '26-40',
        phoneNumber: '+975-17234561',
        studentCode: '',
        studentCategory: '',
        agencyId: 'MOHEALTH-001',
        officeId: 'THIMPHU-002',
        bankName: 'Bank of Bhutan',
        bankBranch: 'Thimphu Branch',
        bankAccountNo: '1001234567893',
        accountType: 'Savings',
        beneficiaryStatus: 'Active',
        remarks: 'Registered with 60% disability, receiving Category A allowance',
      },
      {
        id: generateId('BEN'),
        beneficiaryType: 'Individual',
        beneficiaryCategory: 'Person with Disability',
        cid: '00001-28-0002',
        firstName: 'Lhakpa',
        middleName: 'Chorten',
        lastName: 'Tshering',
        nationality: 'Bhutanese',
        gender: 'Female',
        dob: '1995-09-28',
        ageGroup: '18-25',
        phoneNumber: '+975-17234562',
        studentCode: '',
        studentCategory: '',
        agencyId: 'MOHEALTH-001',
        officeId: 'PUNAKHA-001',
        bankName: 'BNB Bank',
        bankBranch: 'Punakha Branch',
        bankAccountNo: '2001234567894',
        accountType: 'Savings',
        beneficiaryStatus: 'Active',
        remarks: 'Visual impairment registered, receiving Category B allowance',
      },
    ],
    deductions: [
      {
        id: generateId('DED'),
        beneficiaryRefId: 'BEN-0001',
        deductionType: 'Insurance Premium',
        amount: '3000',
        recipientBankAccount: 'DISABILITY-INSURANCE-POOL',
        remarks: 'Medical insurance premium for disability coverage',
      },
    ],
    validationChecks: [
      {
        key: 'cid-verification',
        label: 'CID Verification',
        passed: true,
        message: 'CIDs verified against population registry',
      },
      {
        key: 'eligibility-criteria',
        label: 'Eligibility Criteria Check',
        passed: true,
        message: 'All beneficiaries meet disability registration requirements',
      },
      {
        key: 'budget-ceiling',
        label: 'Budget Ceiling Check',
        passed: true,
        message: 'Allocation within approved budget',
      },
      {
        key: 'bank-validation',
        label: 'Bank Account Validation',
        passed: true,
        message: 'All accounts active and verified',
      },
    ],
    approvals: [
      {
        id: generateId('APR'),
        level: 'Coordinator',
        actor: 'Pema Gyaltshen',
        decidedAt: pastDate(7),
        decision: 'Approved',
        remarks: 'Disability verification documents reviewed',
      },
      {
        id: generateId('APR'),
        level: 'Agency Finance',
        actor: 'Kinzang Choden',
        decidedAt: pastDate(4),
        decision: 'Approved',
        remarks: 'Budget allocation verified',
      },
    ],
    transactions: [
      {
        id: generateId('TXN'),
        beneficiaryRefId: 'BEN-0001',
        invoiceId: 'INV-DISABILITY-2024-0001',
        billId: 'BILL-DISABILITY-2024-0001',
        grossAmount: '8000',
        deductionAmount: '3000',
        netPayableAmount: '5000',
        paymentOrderId: 'PO-DISABILITY-2024-0001',
        period: '2024-04',
        txnStatus: 'Paid',
        remarks: 'Category A disability allowance disbursed',
      },
      {
        id: generateId('TXN'),
        beneficiaryRefId: 'BEN-0002',
        invoiceId: 'INV-DISABILITY-2024-0002',
        billId: 'BILL-DISABILITY-2024-0002',
        grossAmount: '6000',
        deductionAmount: '0',
        netPayableAmount: '6000',
        paymentOrderId: 'PO-DISABILITY-2024-0002',
        period: '2024-04',
        txnStatus: 'Paid',
        remarks: 'Category B disability allowance disbursed',
      },
    ],
    createdAt: pastDate(60),
    updatedAt: today,
  },

  // 3. RGOB Undergraduate Scholarship — India
  {
    id: generateId('SB'),
    header: {
      sbId: 'SCHOLAR-IND-2024-001',
      programType: 'Stipend — Foreign',
      programName: 'RGOB Undergraduate Scholarship Program — India',
      programShortName: 'RGOB-UG-India',
      programDescription: 'Monthly stipend for Bhutanese undergraduate students studying in India',
      implementingAgency: 'Ministry of Education',
      budgetSource: 'RGOB Current Budget',
      budgetCode: 'MOED-SCHOLAR-INDIA-001',
      expenditureType: 'Stipend — Living Allowance',
      paymentAccount: 'Scholarship Trust Account',
      startDate: '2023-08-01',
      plannedEndDate: '2027-07-31',
      allocatedBudget: '250000000',
      programStatus: 'Active',
    },
    beneficiaries: [
      {
        id: generateId('BEN'),
        beneficiaryType: 'Individual',
        beneficiaryCategory: 'Student — Undergraduate',
        cid: '00001-29-0001',
        firstName: 'Rinchen',
        middleName: 'Tenzin',
        lastName: 'Wangchuk',
        nationality: 'Bhutanese',
        gender: 'Male',
        dob: '2002-05-10',
        ageGroup: '18-25',
        phoneNumber: '+91-9876543210',
        studentCode: 'STUDENT-IND-001',
        studentCategory: 'Undergraduate',
        agencyId: 'MOED-001',
        officeId: 'NEW-DELHI-001',
        bankName: 'Bank of Bhutan',
        bankBranch: 'New Delhi Representative Office',
        bankAccountNo: '1001234567895',
        accountType: 'Student',
        beneficiaryStatus: 'Active',
        remarks: 'Studying B.Tech at Delhi University, 2nd year',
      },
      {
        id: generateId('BEN'),
        beneficiaryType: 'Individual',
        beneficiaryCategory: 'Student — Undergraduate',
        cid: '00001-29-0002',
        firstName: 'Yeshi',
        middleName: 'Dolma',
        lastName: 'Choden',
        nationality: 'Bhutanese',
        gender: 'Female',
        dob: '2003-08-22',
        ageGroup: '18-25',
        phoneNumber: '+91-9876543211',
        studentCode: 'STUDENT-IND-002',
        studentCategory: 'Undergraduate',
        agencyId: 'MOED-001',
        officeId: 'BANGALORE-001',
        bankName: 'BDBL Bank',
        bankBranch: 'Bangalore Representative Office',
        bankAccountNo: '3001234567896',
        accountType: 'Student',
        beneficiaryStatus: 'Active',
        remarks: 'Studying B.Sc Biology at Christ University, 1st year',
      },
      {
        id: generateId('BEN'),
        beneficiaryType: 'Individual',
        beneficiaryCategory: 'Student — Undergraduate',
        cid: '00001-29-0003',
        firstName: 'Jigme',
        middleName: 'Phub',
        lastName: 'Dorji',
        nationality: 'Bhutanese',
        gender: 'Male',
        dob: '2001-12-03',
        ageGroup: '18-25',
        phoneNumber: '+91-9876543212',
        studentCode: 'STUDENT-IND-003',
        studentCategory: 'Undergraduate',
        agencyId: 'MOED-001',
        officeId: 'PUNE-001',
        bankName: 'BNB Bank',
        bankBranch: 'Pune Representative Office',
        bankAccountNo: '2001234567897',
        accountType: 'Student',
        beneficiaryStatus: 'Active',
        remarks: 'Studying B.Com at Pune University, 3rd year',
      },
    ],
    deductions: [
      {
        id: generateId('DED'),
        beneficiaryRefId: 'BEN-0001',
        deductionType: 'Hostel Fee',
        amount: '15000',
        recipientBankAccount: 'DELHI-UNIVERSITY-HOSTEL',
        remarks: 'Hostel accommodation fee deduction',
      },
      {
        id: generateId('DED'),
        beneficiaryRefId: 'BEN-0002',
        deductionType: 'Insurance Premium',
        amount: '5000',
        recipientBankAccount: 'STUDENT-INSURANCE-POOL',
        remarks: 'Student health insurance premium',
      },
      {
        id: generateId('DED'),
        beneficiaryRefId: 'BEN-0003',
        deductionType: 'Hostel Fee',
        amount: '12000',
        recipientBankAccount: 'PUNE-UNIVERSITY-HOSTEL',
        remarks: 'Hostel accommodation fee deduction',
      },
    ],
    validationChecks: [
      {
        key: 'cid-verification',
        label: 'CID Verification',
        passed: true,
        message: 'All student CIDs verified with MOE database',
      },
      {
        key: 'duplicate-check',
        label: 'Duplicate Beneficiary Check',
        passed: true,
        message: 'No duplicate registrations found',
      },
      {
        key: 'eligibility-criteria',
        label: 'Eligibility Criteria Check',
        passed: true,
        message: 'All students meet scholarship eligibility requirements',
      },
      {
        key: 'bank-validation',
        label: 'Bank Account Validation',
        passed: true,
        message: 'All accounts validated with overseas branch networks',
      },
    ],
    approvals: [
      {
        id: generateId('APR'),
        level: 'Coordinator',
        actor: 'Rinchen Choden',
        decidedAt: pastDate(10),
        decision: 'Approved',
        remarks: 'Student enrollment documents verified',
      },
      {
        id: generateId('APR'),
        level: 'Agency Finance',
        actor: 'Tenzin Gyeltshen',
        decidedAt: pastDate(7),
        decision: 'Approved',
        remarks: 'Budget allocation for foreign stipend approved',
      },
      {
        id: generateId('APR'),
        level: 'Head of Agency',
        actor: 'Sonam Wangdi',
        decidedAt: pastDate(5),
        decision: 'Approved',
        remarks: 'Final approval for stipend disbursement',
      },
    ],
    transactions: [
      {
        id: generateId('TXN'),
        beneficiaryRefId: 'BEN-0001',
        invoiceId: 'INV-SCHOLAR-IND-2024-0001',
        billId: 'BILL-SCHOLAR-IND-2024-0001',
        grossAmount: '50000',
        deductionAmount: '15000',
        netPayableAmount: '35000',
        paymentOrderId: 'PO-SCHOLAR-IND-2024-0001',
        period: '2024-04',
        txnStatus: 'Paid',
        remarks: 'Monthly stipend transferred to India account',
      },
      {
        id: generateId('TXN'),
        beneficiaryRefId: 'BEN-0002',
        invoiceId: 'INV-SCHOLAR-IND-2024-0002',
        billId: 'BILL-SCHOLAR-IND-2024-0002',
        grossAmount: '50000',
        deductionAmount: '5000',
        netPayableAmount: '45000',
        paymentOrderId: 'PO-SCHOLAR-IND-2024-0002',
        period: '2024-04',
        txnStatus: 'Paid',
        remarks: 'Monthly stipend transferred to India account',
      },
      {
        id: generateId('TXN'),
        beneficiaryRefId: 'BEN-0003',
        invoiceId: 'INV-SCHOLAR-IND-2024-0003',
        billId: 'BILL-SCHOLAR-IND-2024-0003',
        grossAmount: '50000',
        deductionAmount: '12000',
        netPayableAmount: '38000',
        paymentOrderId: 'PO-SCHOLAR-IND-2024-0003',
        period: '2024-04',
        txnStatus: 'Paid',
        remarks: 'Monthly stipend transferred to India account',
      },
    ],
    createdAt: pastDate(90),
    updatedAt: today,
  },

  // 4. RCSC In-Country HRD Stipend
  {
    id: generateId('SB'),
    header: {
      sbId: 'RCSC-HRD-2024-001',
      programType: 'Stipend — Domestic',
      programName: 'RCSC In-Country Human Resource Development Stipend',
      programShortName: 'RCSC-HRD-Domestic',
      programDescription: 'Monthly stipend for civil servants undergoing in-country professional development and training programs',
      implementingAgency: 'Royal Civil Service Commission',
      budgetSource: 'RGOB Current Budget',
      budgetCode: 'RCSC-HRD-2024-001',
      expenditureType: 'Stipend — Living Allowance',
      paymentAccount: 'Agency Operating Account',
      startDate: '2023-01-01',
      plannedEndDate: '2026-12-31',
      allocatedBudget: '120000000',
      programStatus: 'Active',
    },
    beneficiaries: [
      {
        id: generateId('BEN'),
        beneficiaryType: 'Individual',
        beneficiaryCategory: 'Student — Undergraduate',
        cid: '00001-30-0001',
        firstName: 'Karma',
        middleName: 'Cheten',
        lastName: 'Wangdi',
        nationality: 'Bhutanese',
        gender: 'Male',
        dob: '1995-03-18',
        ageGroup: '26-40',
        phoneNumber: '+975-17345671',
        studentCode: 'RCSC-HRD-001',
        studentCategory: 'Diploma / Certificate',
        agencyId: 'RCSC-001',
        officeId: 'THIMPHU-003',
        bankName: 'Bank of Bhutan',
        bankBranch: 'Thimphu Civil Service Branch',
        bankAccountNo: '1001234567898',
        accountType: 'Salary',
        beneficiaryStatus: 'Active',
        remarks: 'Officer undergoing MBA at RIM, Thimphu',
      },
      {
        id: generateId('BEN'),
        beneficiaryType: 'Individual',
        beneficiaryCategory: 'Student — Undergraduate',
        cid: '00001-30-0002',
        firstName: 'Nidup',
        middleName: 'Tenzin',
        lastName: 'Gyeltshen',
        nationality: 'Bhutanese',
        gender: 'Male',
        dob: '1993-07-25',
        ageGroup: '26-40',
        phoneNumber: '+975-17345672',
        studentCode: 'RCSC-HRD-002',
        studentCategory: 'Diploma / Certificate',
        agencyId: 'RCSC-001',
        officeId: 'PARO-002',
        bankName: 'BNB Bank',
        bankBranch: 'Paro Civil Service Branch',
        bankAccountNo: '2001234567899',
        accountType: 'Salary',
        beneficiaryStatus: 'Active',
        remarks: 'Officer undergoing Advanced Management Course at CSI',
      },
    ],
    deductions: [
      {
        id: generateId('DED'),
        beneficiaryRefId: 'BEN-0001',
        deductionType: 'HR Deduction',
        amount: '10000',
        recipientBankAccount: 'RCSC-SALARY-DEDUCTIONS',
        remarks: 'Salary advance recovery',
      },
    ],
    validationChecks: [
      {
        key: 'cid-verification',
        label: 'CID Verification',
        passed: true,
        message: 'CIDs verified with RCSC database',
      },
      {
        key: 'eligibility-criteria',
        label: 'Eligibility Criteria Check',
        passed: true,
        message: 'All officers verified as active civil servants',
      },
      {
        key: 'budget-ceiling',
        label: 'Budget Ceiling Check',
        passed: true,
        message: 'Allocation within HRD budget limits',
      },
    ],
    approvals: [
      {
        id: generateId('APR'),
        level: 'Coordinator',
        actor: 'Pema Dorji',
        decidedAt: pastDate(8),
        decision: 'Approved',
        remarks: 'Training program enrollment verified',
      },
      {
        id: generateId('APR'),
        level: 'Agency Finance',
        actor: 'Tenzin Choden',
        decidedAt: pastDate(5),
        decision: 'Approved',
        remarks: 'Budget authorization approved',
      },
    ],
    transactions: [
      {
        id: generateId('TXN'),
        beneficiaryRefId: 'BEN-0001',
        invoiceId: 'INV-RCSC-HRD-2024-0001',
        billId: 'BILL-RCSC-HRD-2024-0001',
        grossAmount: '25000',
        deductionAmount: '10000',
        netPayableAmount: '15000',
        paymentOrderId: 'PO-RCSC-HRD-2024-0001',
        period: '2024-04',
        txnStatus: 'Paid',
        remarks: 'HRD stipend disbursed to RCSC officer',
      },
      {
        id: generateId('TXN'),
        beneficiaryRefId: 'BEN-0002',
        invoiceId: 'INV-RCSC-HRD-2024-0002',
        billId: 'BILL-RCSC-HRD-2024-0002',
        grossAmount: '25000',
        deductionAmount: '0',
        netPayableAmount: '25000',
        paymentOrderId: 'PO-RCSC-HRD-2024-0002',
        period: '2024-04',
        txnStatus: 'Paid',
        remarks: 'HRD stipend disbursed to RCSC officer',
      },
    ],
    createdAt: pastDate(45),
    updatedAt: today,
  },

  // 5. Monastic Education Stipend
  {
    id: generateId('SB'),
    header: {
      sbId: 'MONASTIC-EDU-2024-001',
      programType: 'Stipend — Domestic',
      programName: 'Monastic Education Support Stipend Program',
      programShortName: 'Monastic-Education',
      programDescription: 'Monthly support stipend for ordained monks pursuing monastic studies in Bhutan',
      implementingAgency: 'Ministry of Education',
      budgetSource: 'RGOB Current Budget',
      budgetCode: 'MOED-MONASTIC-001',
      expenditureType: 'Stipend — Living Allowance',
      paymentAccount: 'Agency Operating Account',
      startDate: '2022-01-01',
      plannedEndDate: '2028-12-31',
      allocatedBudget: '85000000',
      programStatus: 'Active',
    },
    beneficiaries: [
      {
        id: generateId('BEN'),
        beneficiaryType: 'Institutional',
        beneficiaryCategory: 'Monastic Body',
        cid: '00001-31-0001',
        firstName: 'Thangthong',
        middleName: 'Gyelpo',
        lastName: 'Monasteries Association',
        nationality: 'Bhutanese',
        gender: 'Others',
        dob: '1960-01-01',
        ageGroup: 'Above 60',
        phoneNumber: '+975-17456781',
        studentCode: 'MONASTIC-GRP-001',
        studentCategory: 'Monastic Studies',
        agencyId: 'MOED-002',
        officeId: 'THIMPHU-004',
        bankName: 'Bank of Bhutan',
        bankBranch: 'Thimphu Monastic Account Branch',
        bankAccountNo: '1001234567900',
        accountType: 'Current',
        beneficiaryStatus: 'Active',
        remarks: 'Collective account for 45 monks at Thangthong Gyelpo Monastery',
      },
      {
        id: generateId('BEN'),
        beneficiaryType: 'Institutional',
        beneficiaryCategory: 'Monastic Body',
        cid: '00001-31-0002',
        firstName: 'Simtokha',
        middleName: 'Dzong',
        lastName: 'Monastic Institute',
        nationality: 'Bhutanese',
        gender: 'Others',
        dob: '1962-01-01',
        ageGroup: 'Above 60',
        phoneNumber: '+975-17456782',
        studentCode: 'MONASTIC-GRP-002',
        studentCategory: 'Monastic Studies',
        agencyId: 'MOED-002',
        officeId: 'THIMPHU-004',
        bankName: 'BNB Bank',
        bankBranch: 'Thimphu Monastic Account Branch',
        bankAccountNo: '2001234567901',
        accountType: 'Current',
        beneficiaryStatus: 'Active',
        remarks: 'Collective account for 32 monks at Simtokha Dzong',
      },
    ],
    deductions: [
      {
        id: generateId('DED'),
        beneficiaryRefId: 'BEN-0001',
        deductionType: 'Mess Deduction',
        amount: '20000',
        recipientBankAccount: 'MONASTIC-MESS-FUND-001',
        remarks: 'Centralized mess management deduction',
      },
      {
        id: generateId('DED'),
        beneficiaryRefId: 'BEN-0002',
        deductionType: 'Mess Deduction',
        amount: '18000',
        recipientBankAccount: 'MONASTIC-MESS-FUND-002',
        remarks: 'Centralized mess management deduction',
      },
    ],
    validationChecks: [
      {
        key: 'eligibility-criteria',
        label: 'Eligibility Criteria Check',
        passed: true,
        message: 'All monastic institutions verified with Department of Culture',
      },
      {
        key: 'duplicate-check',
        label: 'Duplicate Beneficiary Check',
        passed: true,
        message: 'No duplicate institutional registrations found',
      },
      {
        key: 'budget-ceiling',
        label: 'Budget Ceiling Check',
        passed: true,
        message: 'Monastic education stipend within approved ceiling',
      },
      {
        key: 'bank-validation',
        label: 'Bank Account Validation',
        passed: true,
        message: 'Institutional accounts verified and active',
      },
    ],
    approvals: [
      {
        id: generateId('APR'),
        level: 'Coordinator',
        actor: 'Tenzin Norbu',
        decidedAt: pastDate(12),
        decision: 'Approved',
        remarks: 'Monastic institution registration verified',
      },
      {
        id: generateId('APR'),
        level: 'Agency Finance',
        actor: 'Kesang Dorji',
        decidedAt: pastDate(8),
        decision: 'Approved',
        remarks: 'Budgetary compliance confirmed',
      },
    ],
    transactions: [
      {
        id: generateId('TXN'),
        beneficiaryRefId: 'BEN-0001',
        invoiceId: 'INV-MONASTIC-2024-0001',
        billId: 'BILL-MONASTIC-2024-0001',
        grossAmount: '180000',
        deductionAmount: '20000',
        netPayableAmount: '160000',
        paymentOrderId: 'PO-MONASTIC-2024-0001',
        period: '2024-04',
        txnStatus: 'Paid',
        remarks: 'Monthly stipend for 45 monks disbursed',
      },
      {
        id: generateId('TXN'),
        beneficiaryRefId: 'BEN-0002',
        invoiceId: 'INV-MONASTIC-2024-0002',
        billId: 'BILL-MONASTIC-2024-0002',
        grossAmount: '128000',
        deductionAmount: '18000',
        netPayableAmount: '110000',
        paymentOrderId: 'PO-MONASTIC-2024-0002',
        period: '2024-04',
        txnStatus: 'Paid',
        remarks: 'Monthly stipend for 32 monks disbursed',
      },
    ],
    createdAt: pastDate(120),
    updatedAt: today,
  },

  // 6. Widow & Orphan Support Program
  {
    id: generateId('SB'),
    header: {
      sbId: 'WIDOW-ORPHAN-2024-001',
      programType: 'Social Benefit',
      programName: 'Widow and Orphan Support Program',
      programShortName: 'WOSP-2024',
      programDescription: 'Monthly financial support for widows and orphaned children in Bhutan',
      implementingAgency: 'Ministry of Labour and Human Resources',
      budgetSource: 'RGOB Current Budget',
      budgetCode: 'MLOHR-WIDOW-ORPHAN-001',
      expenditureType: 'Social Benefit — Monthly',
      paymentAccount: 'Social Protection Fund',
      startDate: '2021-03-15',
      plannedEndDate: '2029-12-31',
      allocatedBudget: '220000000',
      programStatus: 'Active',
    },
    beneficiaries: [
      {
        id: generateId('BEN'),
        beneficiaryType: 'Individual',
        beneficiaryCategory: 'Widow / Orphan',
        cid: '00001-32-0001',
        firstName: 'Deki',
        middleName: 'Yangzom',
        lastName: 'Penjor',
        nationality: 'Bhutanese',
        gender: 'Female',
        dob: '1965-06-30',
        ageGroup: '41-60',
        phoneNumber: '+975-17567891',
        studentCode: '',
        studentCategory: '',
        agencyId: 'MLOHR-002',
        officeId: 'PUNAKHA-002',
        bankName: 'Bank of Bhutan',
        bankBranch: 'Punakha Branch',
        bankAccountNo: '1001234567902',
        accountType: 'Savings',
        beneficiaryStatus: 'Active',
        remarks: 'Widow with 3 dependent children, primary earner',
      },
      {
        id: generateId('BEN'),
        beneficiaryType: 'Individual',
        beneficiaryCategory: 'Widow / Orphan',
        cid: '00001-32-0002',
        firstName: 'Sonam',
        middleName: 'Choki',
        lastName: 'Wangmo',
        nationality: 'Bhutanese',
        gender: 'Female',
        dob: '1975-11-12',
        ageGroup: '41-60',
        phoneNumber: '+975-17567892',
        studentCode: '',
        studentCategory: '',
        agencyId: 'MLOHR-002',
        officeId: 'WANGSEL-001',
        bankName: 'BDBL Bank',
        bankBranch: 'Wangsel Branch',
        bankAccountNo: '3001234567903',
        accountType: 'Savings',
        beneficiaryStatus: 'Active',
        remarks: 'Widow with 2 dependent children, receiving enhanced benefit',
      },
      {
        id: generateId('BEN'),
        beneficiaryType: 'Individual',
        beneficiaryCategory: 'Widow / Orphan',
        cid: '00001-32-0003',
        firstName: 'Pelzom',
        middleName: 'Tshering',
        lastName: 'Dorji',
        nationality: 'Bhutanese',
        gender: 'Female',
        dob: '1968-04-05',
        ageGroup: '41-60',
        phoneNumber: '+975-17567893',
        studentCode: '',
        studentCategory: '',
        agencyId: 'MLOHR-002',
        officeId: 'DAGANA-001',
        bankName: 'BNB Bank',
        bankBranch: 'Dagana Branch',
        bankAccountNo: '2001234567904',
        accountType: 'Savings',
        beneficiaryStatus: 'Active',
        remarks: 'Widow, elderly support additional to widow benefits',
      },
    ],
    deductions: [
      {
        id: generateId('DED'),
        beneficiaryRefId: 'BEN-0001',
        deductionType: 'Insurance Premium',
        amount: '4000',
        recipientBankAccount: 'WIDOW-INSURANCE-POOL',
        remarks: 'Family welfare insurance premium',
      },
      {
        id: generateId('DED'),
        beneficiaryRefId: 'BEN-0002',
        deductionType: 'HR Deduction',
        amount: '2000',
        recipientBankAccount: 'MLOHR-ADMINISTRATIVE-FUND',
        remarks: 'Administrative processing fee',
      },
    ],
    validationChecks: [
      {
        key: 'cid-verification',
        label: 'CID Verification',
        passed: true,
        message: 'All beneficiary CIDs verified with population registry',
      },
      {
        key: 'duplicate-check',
        label: 'Duplicate Beneficiary Check',
        passed: true,
        message: 'No duplicate registrations in widow/orphan database',
      },
      {
        key: 'eligibility-criteria',
        label: 'Eligibility Criteria Check',
        passed: true,
        message: 'All beneficiaries meet widow/orphan support criteria',
      },
      {
        key: 'bank-validation',
        label: 'Bank Account Validation',
        passed: true,
        message: 'All bank accounts validated and active',
      },
    ],
    approvals: [
      {
        id: generateId('APR'),
        level: 'Coordinator',
        actor: 'Kinley Penjor',
        decidedAt: pastDate(9),
        decision: 'Approved',
        remarks: 'Widow status and dependent verification completed',
      },
      {
        id: generateId('APR'),
        level: 'Agency Finance',
        actor: 'Tenzin Yeshi',
        decidedAt: pastDate(6),
        decision: 'Approved',
        remarks: 'Financial clearance granted',
      },
      {
        id: generateId('APR'),
        level: 'Head of Agency',
        actor: 'Dorji Tshering',
        decidedAt: pastDate(2),
        decision: 'Approved',
        remarks: 'Final approval for disbursement',
      },
    ],
    transactions: [
      {
        id: generateId('TXN'),
        beneficiaryRefId: 'BEN-0001',
        invoiceId: 'INV-WIDOW-2024-0001',
        billId: 'BILL-WIDOW-2024-0001',
        grossAmount: '12000',
        deductionAmount: '4000',
        netPayableAmount: '8000',
        paymentOrderId: 'PO-WIDOW-2024-0001',
        period: '2024-04',
        txnStatus: 'Paid',
        remarks: 'Widow support benefit disbursed',
      },
      {
        id: generateId('TXN'),
        beneficiaryRefId: 'BEN-0002',
        invoiceId: 'INV-WIDOW-2024-0002',
        billId: 'BILL-WIDOW-2024-0002',
        grossAmount: '11000',
        deductionAmount: '2000',
        netPayableAmount: '9000',
        paymentOrderId: 'PO-WIDOW-2024-0002',
        period: '2024-04',
        txnStatus: 'Paid',
        remarks: 'Enhanced widow support benefit disbursed',
      },
      {
        id: generateId('TXN'),
        beneficiaryRefId: 'BEN-0003',
        invoiceId: 'INV-WIDOW-2024-0003',
        billId: 'BILL-WIDOW-2024-0003',
        grossAmount: '10000',
        deductionAmount: '0',
        netPayableAmount: '10000',
        paymentOrderId: 'PO-WIDOW-2024-0003',
        period: '2024-04',
        txnStatus: 'Paid',
        remarks: 'Widow support benefit with elderly allowance disbursed',
      },
    ],
    createdAt: pastDate(150),
    updatedAt: today,
  },

  // 7. PhD Fellowship Program — Abroad
  {
    id: generateId('SB'),
    header: {
      sbId: 'PHD-FELLOWSHIP-2024-001',
      programType: 'Stipend — Foreign',
      programName: 'PhD Fellowship Program — International',
      programShortName: 'PhD-Fellowship-Intl',
      programDescription: 'Monthly fellowship support for Bhutanese citizens pursuing PhD studies abroad',
      implementingAgency: 'Ministry of Education',
      budgetSource: 'RGOB Current Budget',
      budgetCode: 'MOED-PHD-FELLOWSHIP-001',
      expenditureType: 'Stipend — Living Allowance',
      paymentAccount: 'Scholarship Trust Account',
      startDate: '2023-09-01',
      plannedEndDate: '2028-08-31',
      allocatedBudget: '350000000',
      programStatus: 'Active',
    },
    beneficiaries: [
      {
        id: generateId('BEN'),
        beneficiaryType: 'Individual',
        beneficiaryCategory: 'Student — Graduate',
        cid: '00001-33-0001',
        firstName: 'Tenzing',
        middleName: 'Dawa',
        lastName: 'Gyaltsen',
        nationality: 'Bhutanese',
        gender: 'Male',
        dob: '1996-02-18',
        ageGroup: '26-40',
        phoneNumber: '+1-6175551234',
        studentCode: 'PHD-INTL-001',
        studentCategory: 'PhD / Doctoral',
        agencyId: 'MOED-003',
        officeId: 'CAMBRIDGE-001',
        bankName: 'Bank of Bhutan',
        bankBranch: 'London Representative Office',
        bankAccountNo: '1001234567905',
        accountType: 'Student',
        beneficiaryStatus: 'Active',
        remarks: 'Pursuing PhD in Environmental Science at MIT, USA',
      },
      {
        id: generateId('BEN'),
        beneficiaryType: 'Individual',
        beneficiaryCategory: 'Student — Graduate',
        cid: '00001-33-0002',
        firstName: 'Yeshi',
        middleName: 'Dema',
        lastName: 'Tshering',
        nationality: 'Bhutanese',
        gender: 'Female',
        dob: '1997-09-25',
        ageGroup: '26-40',
        phoneNumber: '+44-2073468900',
        studentCode: 'PHD-INTL-002',
        studentCategory: 'PhD / Doctoral',
        agencyId: 'MOED-003',
        officeId: 'LONDON-001',
        bankName: 'BDBL Bank',
        bankBranch: 'London Representative Office',
        bankAccountNo: '3001234567906',
        accountType: 'Student',
        beneficiaryStatus: 'Active',
        remarks: 'Pursuing PhD in Public Health at London School of Economics',
      },
    ],
    deductions: [
      {
        id: generateId('DED'),
        beneficiaryRefId: 'BEN-0001',
        deductionType: 'Insurance Premium',
        amount: '8000',
        recipientBankAccount: 'PHD-STUDENT-INSURANCE-POOL',
        remarks: 'International student health and accident insurance',
      },
      {
        id: generateId('DED'),
        beneficiaryRefId: 'BEN-0002',
        deductionType: 'Insurance Premium',
        amount: '8000',
        recipientBankAccount: 'PHD-STUDENT-INSURANCE-POOL',
        remarks: 'International student health and accident insurance',
      },
    ],
    validationChecks: [
      {
        key: 'cid-verification',
        label: 'CID Verification',
        passed: true,
        message: 'All CIDs verified with MOE international student records',
      },
      {
        key: 'eligibility-criteria',
        label: 'Eligibility Criteria Check',
        passed: true,
        message: 'All students verified as enrolled in accredited PhD programs',
      },
      {
        key: 'duplicate-check',
        label: 'Duplicate Beneficiary Check',
        passed: true,
        message: 'No duplicate international fellowship records',
      },
      {
        key: 'bank-validation',
        label: 'Bank Account Validation',
        passed: true,
        message: 'All accounts validated with overseas banking partners',
      },
    ],
    approvals: [
      {
        id: generateId('APR'),
        level: 'Coordinator',
        actor: 'Pema Choden',
        decidedAt: pastDate(15),
        decision: 'Approved',
        remarks: 'International enrollment credentials verified',
      },
      {
        id: generateId('APR'),
        level: 'Agency Finance',
        actor: 'Kinzang Gyelpo',
        decidedAt: pastDate(11),
        decision: 'Approved',
        remarks: 'International fellowship budget approved',
      },
      {
        id: generateId('APR'),
        level: 'Budget Division',
        actor: 'Sonam Yeshi',
        decidedAt: pastDate(8),
        decision: 'Approved',
        remarks: 'Central budget approval granted for PhD fellowships',
      },
    ],
    transactions: [
      {
        id: generateId('TXN'),
        beneficiaryRefId: 'BEN-0001',
        invoiceId: 'INV-PHD-INTL-2024-0001',
        billId: 'BILL-PHD-INTL-2024-0001',
        grossAmount: '75000',
        deductionAmount: '8000',
        netPayableAmount: '67000',
        paymentOrderId: 'PO-PHD-INTL-2024-0001',
        period: '2024-04',
        txnStatus: 'Paid',
        remarks: 'PhD fellowship transferred to USA account',
      },
      {
        id: generateId('TXN'),
        beneficiaryRefId: 'BEN-0002',
        invoiceId: 'INV-PHD-INTL-2024-0002',
        billId: 'BILL-PHD-INTL-2024-0002',
        grossAmount: '75000',
        deductionAmount: '8000',
        netPayableAmount: '67000',
        paymentOrderId: 'PO-PHD-INTL-2024-0002',
        period: '2024-04',
        txnStatus: 'Paid',
        remarks: 'PhD fellowship transferred to UK account',
      },
    ],
    createdAt: pastDate(75),
    updatedAt: today,
  },

  // 8. Vocational Training Allowance
  {
    id: generateId('SB'),
    header: {
      sbId: 'VOCATIONAL-TRAIN-2024-001',
      programType: 'Stipend — Domestic',
      programName: 'Vocational Training Allowance Program',
      programShortName: 'VTA-2024',
      programDescription: 'Monthly stipend for participants in government-approved vocational training programs',
      implementingAgency: 'Ministry of Labour and Human Resources',
      budgetSource: 'RGOB Current Budget',
      budgetCode: 'MLOHR-VOCATIONAL-001',
      expenditureType: 'Stipend — Living Allowance',
      paymentAccount: 'Agency Operating Account',
      startDate: '2023-04-01',
      plannedEndDate: '2027-03-31',
      allocatedBudget: '95000000',
      programStatus: 'Active',
    },
    beneficiaries: [
      {
        id: generateId('BEN'),
        beneficiaryType: 'Individual',
        beneficiaryCategory: 'Student — Vocational',
        cid: '00001-34-0001',
        firstName: 'Tenzin',
        middleName: 'Choki',
        lastName: 'Pelzom',
        nationality: 'Bhutanese',
        gender: 'Male',
        dob: '2004-01-30',
        ageGroup: '18-25',
        phoneNumber: '+975-17678901',
        studentCode: 'VOCATIONAL-001',
        studentCategory: 'Diploma / Certificate',
        agencyId: 'MLOHR-003',
        officeId: 'THIMPHU-005',
        bankName: 'Bank of Bhutan',
        bankBranch: 'Thimphu Vocational Branch',
        bankAccountNo: '1001234567907',
        accountType: 'Student',
        beneficiaryStatus: 'Active',
        remarks: 'Pursuing Automotive Technology diploma at Bhutan Khamdung College',
      },
      {
        id: generateId('BEN'),
        beneficiaryType: 'Individual',
        beneficiaryCategory: 'Student — Vocational',
        cid: '00001-34-0002',
        firstName: 'Lhakpa',
        middleName: 'Tenzin',
        lastName: 'Wangmo',
        nationality: 'Bhutanese',
        gender: 'Female',
        dob: '2003-07-14',
        ageGroup: '18-25',
        phoneNumber: '+975-17678902',
        studentCode: 'VOCATIONAL-002',
        studentCategory: 'Diploma / Certificate',
        agencyId: 'MLOHR-003',
        officeId: 'PARO-003',
        bankName: 'BNB Bank',
        bankBranch: 'Paro Vocational Branch',
        bankAccountNo: '2001234567908',
        accountType: 'Student',
        beneficiaryStatus: 'Active',
        remarks: 'Pursuing Hospitality Management diploma at Paro College of Hotel Management',
      },
      {
        id: generateId('BEN'),
        beneficiaryType: 'Individual',
        beneficiaryCategory: 'Student — Vocational',
        cid: '00001-34-0003',
        firstName: 'Dorji',
        middleName: 'Kuenga',
        lastName: 'Tshering',
        nationality: 'Bhutanese',
        gender: 'Male',
        dob: '2002-11-08',
        ageGroup: '18-25',
        phoneNumber: '+975-17678903',
        studentCode: 'VOCATIONAL-003',
        studentCategory: 'Diploma / Certificate',
        agencyId: 'MLOHR-003',
        officeId: 'BUMTHANG-002',
        bankName: 'BDBL Bank',
        bankBranch: 'Bumthang Vocational Branch',
        bankAccountNo: '3001234567909',
        accountType: 'Student',
        beneficiaryStatus: 'Active',
        remarks: 'Pursuing Agricultural Technology diploma at Bumthang Institute of Agriculture',
      },
      {
        id: generateId('BEN'),
        beneficiaryType: 'Individual',
        beneficiaryCategory: 'Student — Vocational',
        cid: '00001-34-0004',
        firstName: 'Yeshe',
        middleName: 'Dema',
        lastName: 'Choden',
        nationality: 'Bhutanese',
        gender: 'Female',
        dob: '2003-05-20',
        ageGroup: '18-25',
        phoneNumber: '+975-17678904',
        studentCode: 'VOCATIONAL-004',
        studentCategory: 'Diploma / Certificate',
        agencyId: 'MLOHR-003',
        officeId: 'WANGSEL-002',
        bankName: 'Bank of Bhutan',
        bankBranch: 'Wangsel Vocational Branch',
        bankAccountNo: '1001234567910',
        accountType: 'Student',
        beneficiaryStatus: 'Active',
        remarks: 'Pursuing Fashion Design and Technology diploma at Institute of Vocational Studies',
      },
    ],
    deductions: [
      {
        id: generateId('DED'),
        beneficiaryRefId: 'BEN-0001',
        deductionType: 'Hostel Fee',
        amount: '8000',
        recipientBankAccount: 'BHUTAN-KHAMDUNG-HOSTEL',
        remarks: 'Hostel accommodation fee',
      },
      {
        id: generateId('DED'),
        beneficiaryRefId: 'BEN-0002',
        deductionType: 'Hostel Fee',
        amount: '7000',
        recipientBankAccount: 'PARO-COLLEGE-HOSTEL',
        remarks: 'Hostel accommodation fee',
      },
      {
        id: generateId('DED'),
        beneficiaryRefId: 'BEN-0003',
        deductionType: 'Mess Deduction',
        amount: '6000',
        recipientBankAccount: 'BUMTHANG-INSTITUTE-MESS',
        remarks: 'Dining and mess facilities deduction',
      },
    ],
    validationChecks: [
      {
        key: 'cid-verification',
        label: 'CID Verification',
        passed: true,
        message: 'All CIDs verified with population registry',
      },
      {
        key: 'eligibility-criteria',
        label: 'Eligibility Criteria Check',
        passed: true,
        message: 'All trainees enrolled in approved vocational institutions',
      },
      {
        key: 'budget-ceiling',
        label: 'Budget Ceiling Check',
        passed: true,
        message: 'Vocational training allowance within budget allocation',
      },
      {
        key: 'bank-validation',
        label: 'Bank Account Validation',
        passed: true,
        message: 'All accounts validated with participating banks',
      },
    ],
    approvals: [
      {
        id: generateId('APR'),
        level: 'Coordinator',
        actor: 'Karma Dorji',
        decidedAt: pastDate(11),
        decision: 'Approved',
        remarks: 'Vocational training enrollment verified at approved institutions',
      },
      {
        id: generateId('APR'),
        level: 'Agency Finance',
        actor: 'Pema Choden',
        decidedAt: pastDate(8),
        decision: 'Approved',
        remarks: 'Budget allocation approved for vocational training',
      },
    ],
    transactions: [
      {
        id: generateId('TXN'),
        beneficiaryRefId: 'BEN-0001',
        invoiceId: 'INV-VOCATIONAL-2024-0001',
        billId: 'BILL-VOCATIONAL-2024-0001',
        grossAmount: '18000',
        deductionAmount: '8000',
        netPayableAmount: '10000',
        paymentOrderId: 'PO-VOCATIONAL-2024-0001',
        period: '2024-04',
        txnStatus: 'Paid',
        remarks: 'Vocational training allowance disbursed',
      },
      {
        id: generateId('TXN'),
        beneficiaryRefId: 'BEN-0002',
        invoiceId: 'INV-VOCATIONAL-2024-0002',
        billId: 'BILL-VOCATIONAL-2024-0002',
        grossAmount: '17000',
        deductionAmount: '7000',
        netPayableAmount: '10000',
        paymentOrderId: 'PO-VOCATIONAL-2024-0002',
        period: '2024-04',
        txnStatus: 'Paid',
        remarks: 'Vocational training allowance disbursed',
      },
      {
        id: generateId('TXN'),
        beneficiaryRefId: 'BEN-0003',
        invoiceId: 'INV-VOCATIONAL-2024-0003',
        billId: 'BILL-VOCATIONAL-2024-0003',
        grossAmount: '16000',
        deductionAmount: '6000',
        netPayableAmount: '10000',
        paymentOrderId: 'PO-VOCATIONAL-2024-0003',
        period: '2024-04',
        txnStatus: 'Paid',
        remarks: 'Vocational training allowance disbursed',
      },
      {
        id: generateId('TXN'),
        beneficiaryRefId: 'BEN-0004',
        invoiceId: 'INV-VOCATIONAL-2024-0004',
        billId: 'BILL-VOCATIONAL-2024-0004',
        grossAmount: '17000',
        deductionAmount: '0',
        netPayableAmount: '17000',
        paymentOrderId: 'PO-VOCATIONAL-2024-0004',
        period: '2024-04',
        txnStatus: 'Paid',
        remarks: 'Vocational training allowance disbursed without deductions',
      },
    ],
    createdAt: pastDate(85),
    updatedAt: today,
  },
];
