import { FormFieldConfig } from "../../shared/types";

export const OPS_EMPLOYEE_MASTER_FIELDS: FormFieldConfig[] = [
  // Basic Info Section - Same 38 fields but OPS context
  {
    id: "empIdMasterId",
    label: "Master ID",
    type: "text",
    mandatory: true,
    source: "Auto-generated",
  },
  {
    id: "employeeId",
    label: "Employee ID",
    type: "text",
    mandatory: true,
    source: "Agency System",
  },
  {
    id: "firstName",
    label: "First Name",
    type: "text",
    mandatory: true,
    source: "Agency System",
  },
  {
    id: "middleName",
    label: "Middle Name",
    type: "text",
    mandatory: false,
    source: "Agency System",
  },
  {
    id: "lastName",
    label: "Last Name",
    type: "text",
    mandatory: true,
    source: "Agency System",
  },
  {
    id: "gender",
    label: "Gender",
    type: "dropdown",
    mandatory: true,
    source: "Agency System",
    lovKey: "genderValues",
  },
  {
    id: "nationality",
    label: "Nationality",
    type: "dropdown",
    mandatory: true,
    source: "Agency System",
    lovKey: "countryList",
  },
  {
    id: "cid",
    label: "CID (11-digit)",
    type: "text",
    mandatory: true,
    source: "DCRC/BCRS",
    minLength: 11,
  },
  {
    id: "workPermit",
    label: "Work Permit",
    type: "text",
    mandatory: false,
    source: "DOI/Agency System",
  },
  {
    id: "tpn",
    label: "TPN",
    type: "text",
    mandatory: false,
    source: "DRC/RAMIS",
  },

  // Employment Section
  {
    id: "employeeCategory",
    label: "Employee Category",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "opsEmployeeCategories",
  },
  {
    id: "employeeType",
    label: "Employee Type",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "opsEmployeeTypes",
  },
  {
    id: "dateOfBirth",
    label: "Date of Birth",
    type: "date",
    mandatory: true,
    source: "DCRC/Agency System",
  },
  {
    id: "positionTitle",
    label: "Position Title",
    type: "text",
    mandatory: true,
    source: "Agency System",
  },
  {
    id: "designation",
    label: "Designation",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "designationList",
  },
  {
    id: "positionLevel",
    label: "Position Level",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "opsPositionLevels",
  },
  {
    id: "payScale",
    label: "Pay Scale (Min-Increment-Max)",
    type: "text",
    mandatory: false,
    source: "Agency System",
  },
  {
    id: "monthlyBasicPay",
    label: "Monthly Basic Pay",
    type: "number",
    mandatory: true,
    source: "Agency System",
    step: 0.01,
  },
  {
    id: "workingAgency",
    label: "Working Agency",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "opsAgencyList",
  },
  {
    id: "organizationSegment",
    label: "Organization Segment",
    type: "dropdown",
    mandatory: false,
    source: "System",
    lovKey: "opsOrgSegmentList",
  },
  {
    id: "appointmentDate",
    label: "Appointment Date",
    type: "date",
    mandatory: true,
    source: "Agency System",
  },
  {
    id: "joiningDate",
    label: "Joining Date",
    type: "date",
    mandatory: true,
    source: "Agency System",
  },
  {
    id: "incrementDate",
    label: "Increment Date",
    type: "date",
    mandatory: false,
    source: "Agency System",
  },
  {
    id: "superannuationDate",
    label: "Superannuation Date",
    type: "date",
    mandatory: false,
    source: "Agency System",
  },
  {
    id: "contractEndDate",
    label: "Contract End Date",
    type: "date",
    mandatory: false,
    source: "Agency System",
  },
  {
    id: "employeeStatus",
    label: "Employee Status",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "employeeStatuses",
  },
  {
    id: "pfEligible",
    label: "PF Eligible",
    type: "dropdown",
    mandatory: false,
    source: "System",
    lovKey: "yesNoValues",
  },
  {
    id: "pfAccountNumber",
    label: "PF Account Number",
    type: "text",
    mandatory: false,
    source: "System",
  },
  {
    id: "gisEligible",
    label: "GIS Eligible",
    type: "dropdown",
    mandatory: false,
    source: "System",
    lovKey: "yesNoValues",
  },
  {
    id: "gisNumber",
    label: "GIS Number",
    type: "text",
    mandatory: false,
    source: "System",
  },
  {
    id: "isTaxExempted",
    label: "Is Tax Exempted",
    type: "dropdown",
    mandatory: false,
    source: "System",
    lovKey: "yesNoValues",
  },
  {
    id: "reasonForTaxExemption",
    label: "Reason for Tax Exemption",
    type: "text",
    mandatory: false,
    source: "System",
  },
  {
    id: "isHealthContributionExempted",
    label: "Is Health Contribution Exempted",
    type: "dropdown",
    mandatory: false,
    source: "System",
    lovKey: "yesNoValues",
  },
  {
    id: "emailId",
    label: "Email",
    type: "text",
    mandatory: false,
    source: "Agency System",
  },
  {
    id: "mobileNumber",
    label: "Mobile Number",
    type: "text",
    mandatory: false,
    source: "Agency System",
  },
  {
    id: "bankName",
    label: "Bank Name",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "bankNames",
  },
  {
    id: "bankAccountNumber",
    label: "Bank Account Number",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "bankBranch",
    label: "Bank Branch",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "bankBranches",
  },
];
