import { FormFieldConfig } from "../../shared/types";

export const OPS_HR_ACTION_FIELDS: FormFieldConfig[] = [
  {
    id: "hrAction",
    label: "HR Action",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "hrActionTypes",
  },
  {
    id: "employeeId",
    label: "Employee ID",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "oldBasicPay",
    label: "Old Basic Pay",
    type: "number",
    mandatory: false,
    source: "System",
  },
  {
    id: "newBasicPay",
    label: "New Basic Pay",
    type: "number",
    mandatory: false,
    source: "System",
  },
  {
    id: "increment",
    label: "Increment Amount",
    type: "number",
    mandatory: false,
    source: "System",
  },
  {
    id: "promotionType",
    label: "Promotion Type",
    type: "dropdown",
    mandatory: false,
    source: "System",
    lovKey: "promotionTypes",
  },
  {
    id: "newPositionTitle",
    label: "New Position Title",
    type: "text",
    mandatory: false,
    source: "System",
  },
  {
    id: "newPayScale",
    label: "New Pay Scale",
    type: "text",
    mandatory: false,
    source: "System",
  },
  {
    id: "newWorkingAgency",
    label: "New Working Agency",
    type: "dropdown",
    mandatory: false,
    source: "System",
    lovKey: "opsAgencyList",
  },
  {
    id: "newIncrementDate",
    label: "New Increment Date",
    type: "date",
    mandatory: false,
    source: "System",
  },
  {
    id: "transferType",
    label: "Transfer Type",
    type: "dropdown",
    mandatory: false,
    source: "System",
    lovKey: "transferTypes",
  },
  {
    id: "dateOfJoining",
    label: "Date of Joining",
    type: "date",
    mandatory: false,
    source: "System",
  },
  {
    id: "contractExtendedDate",
    label: "Contract Extended Until",
    type: "date",
    mandatory: false,
    source: "System",
  },
  {
    id: "secondmentFrom",
    label: "Secondment From",
    type: "text",
    mandatory: false,
    source: "System",
  },
  {
    id: "secondmentUntil",
    label: "Secondment Until",
    type: "date",
    mandatory: false,
    source: "System",
  },
  {
    id: "secondmentCountry",
    label: "Secondment Country",
    type: "dropdown",
    mandatory: false,
    source: "System",
    lovKey: "countryList",
  },
  {
    id: "leaveType",
    label: "Leave Type",
    type: "dropdown",
    mandatory: false,
    source: "System",
    lovKey: "leaveTypes",
  },
  {
    id: "separationType",
    label: "Separation Type",
    type: "dropdown",
    mandatory: false,
    source: "System",
    lovKey: "separationTypes",
  },
  {
    id: "remarks",
    label: "Remarks",
    type: "textarea",
    mandatory: false,
    source: "System",
  },
];
