import { FormFieldConfig } from "../../shared/types";

export const OPS_MUSTERROLL_DETAILS_FIELDS: FormFieldConfig[] = [
  {
    id: "name",
    label: "Name",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "cid",
    label: "CID",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "workPermit",
    label: "Work Permit",
    type: "text",
    mandatory: false,
    source: "System",
  },
  {
    id: "nationality",
    label: "Nationality",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "countryList",
  },
  {
    id: "agency",
    label: "Agency",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "opsAgencyList",
  },
  {
    id: "category",
    label: "Category",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "position",
    label: "Position/Job",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "musterrollJobs",
  },
  {
    id: "dailyWage",
    label: "Daily Wage",
    type: "number",
    mandatory: true,
    source: "System",
    step: 0.01,
  },
  {
    id: "lumpsumAmount",
    label: "Lumpsum Amount",
    type: "number",
    mandatory: false,
    source: "System",
    step: 0.01,
  },
  {
    id: "location",
    label: "Location",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "bankName",
    label: "Bank Name",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "bankNames",
  },
  {
    id: "bankAccountNumber",
    label: "Bank Account Number",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "tpn",
    label: "TPN",
    type: "text",
    mandatory: false,
    source: "System",
  },
];

export const OPS_MUSTERROLL_PAYMENT_FIELDS: FormFieldConfig[] = [
  {
    id: "name",
    label: "Name",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "cid",
    label: "CID",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "workPermit",
    label: "Work Permit",
    type: "text",
    mandatory: false,
    source: "System",
  },
  {
    id: "agency",
    label: "Agency",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "opsAgencyList",
  },
  {
    id: "position",
    label: "Position/Job",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "musterrollJobs",
  },
  {
    id: "dailyWage",
    label: "Daily Wage",
    type: "number",
    mandatory: true,
    source: "System",
    step: 0.01,
  },
  {
    id: "monthlyWage",
    label: "Monthly Wage",
    type: "number",
    mandatory: false,
    source: "System",
    step: 0.01,
  },
  {
    id: "otherAllowance",
    label: "Other Allowance",
    type: "dropdown",
    mandatory: false,
    source: "System",
    lovKey: "musterrollAllowances",
  },
  {
    id: "deduction",
    label: "Deduction",
    type: "dropdown",
    mandatory: false,
    source: "System",
    lovKey: "musterrollDeductions",
  },
  {
    id: "netPay",
    label: "Net Pay",
    type: "number",
    mandatory: false,
    source: "System",
    step: 0.01,
  },
];
