import { FormFieldConfig } from "../../shared/types";

export const OPS_PAYROLL_PROCESSING_FIELDS: FormFieldConfig[] = [
  {
    id: "employeeName",
    label: "Employee Name",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "positionTitle",
    label: "Position Title",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "cid",
    label: "CID",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "monthlyBasicPay",
    label: "Monthly Basic Pay",
    type: "number",
    mandatory: true,
    source: "System",
    step: 0.01,
  },
  {
    id: "arrears",
    label: "Arrears",
    type: "number",
    mandatory: false,
    source: "System",
    step: 0.01,
  },
  {
    id: "fixedPay",
    label: "Fixed Pay",
    type: "dropdown",
    mandatory: false,
    source: "System",
    lovKey: "opsFixedPayAllowances",
  },
  {
    id: "variablePay",
    label: "Variable Pay",
    type: "dropdown",
    mandatory: false,
    source: "System",
    lovKey: "opsVariablePayAllowances",
  },
  {
    id: "grossPay",
    label: "Gross Pay",
    type: "number",
    mandatory: false,
    source: "System",
    step: 0.01,
  },
  {
    id: "statutoryDeductions",
    label: "Statutory Deductions",
    type: "dropdown",
    mandatory: false,
    source: "System",
    lovKey: "opsStatutoryDeductions",
  },
  {
    id: "otherDeductions",
    label: "Other Deductions",
    type: "dropdown",
    mandatory: false,
    source: "System",
    lovKey: "opsOtherDeductions",
  },
  {
    id: "totalDeductions",
    label: "Total Deductions",
    type: "number",
    mandatory: false,
    source: "System",
    step: 0.01,
  },
  {
    id: "netPay",
    label: "Net Pay",
    type: "number",
    mandatory: false,
    source: "System",
    step: 0.01,
  },
];
