import { FormFieldConfig } from "../../shared/types";

export const OPS_RETIREMENT_BENEFITS_FIELDS: FormFieldConfig[] = [
  {
    id: "retirementType",
    label: "Retirement Type",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "retirementTypes",
  },
  {
    id: "agencyCode",
    label: "Agency Code",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "budgetCode",
    label: "Budget Code",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "employeeName",
    label: "Employee Name",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "cid",
    label: "CID",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "employeeId",
    label: "Employee ID",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "workPermit",
    label: "Work Permit",
    type: "text",
    mandatory: false,
    source: "System",
  },
  {
    id: "tpn",
    label: "TPN",
    type: "text",
    mandatory: false,
    source: "System",
  },
  {
    id: "lastWorkingAgency",
    label: "Last Working Agency",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "opsAgencyList",
  },
  {
    id: "payrollDepartment",
    label: "Payroll Department",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "yearsOfService",
    label: "Completed Years of Service (verified with ZESt)",
    type: "number",
    mandatory: true,
    source: "System",
  },
  {
    id: "gratuityAmount",
    label: "Gratuity Amount",
    type: "number",
    mandatory: true,
    source: "System",
    step: 0.01,
  },
  {
    id: "transferGrant",
    label: "Transfer Grant",
    type: "number",
    mandatory: false,
    source: "System",
    step: 0.01,
  },
  {
    id: "travellingAllowance",
    label: "Travelling Allowance",
    type: "number",
    mandatory: false,
    source: "System",
    step: 0.01,
  },
  {
    id: "transportCharges",
    label: "Transport Charges",
    type: "number",
    mandatory: false,
    source: "System",
    step: 0.01,
  },
  {
    id: "leaveBalanceEncashment",
    label: "Leave Balance Encashment",
    type: "number",
    mandatory: false,
    source: "System",
    step: 0.01,
  },
  {
    id: "mileage",
    label: "Mileage",
    type: "number",
    mandatory: false,
    source: "System",
    step: 0.01,
  },
  {
    id: "grossBenefitAmount",
    label: "Gross Benefit Amount",
    type: "number",
    mandatory: false,
    source: "System",
    step: 0.01,
  },
  {
    id: "taxesDeductions",
    label: "Taxes or Deductions",
    type: "number",
    mandatory: false,
    source: "System",
    step: 0.01,
  },
  {
    id: "netBenefitAmount",
    label: "Net Benefit Amount",
    type: "number",
    mandatory: false,
    source: "System",
    step: 0.01,
  },
];
