import { FormFieldConfig } from "../../shared/types";

export const OPS_SITTING_FEE_FIELDS: FormFieldConfig[] = [
  {
    id: "name",
    label: "Name",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "cid",
    label: "CID",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "workPermit",
    label: "Work Permit",
    type: "text",
    mandatory: false,
    source: "System",
  },
  {
    id: "tpn",
    label: "TPN",
    type: "text",
    mandatory: false,
    source: "System",
  },
  {
    id: "startDate",
    label: "Start Date",
    type: "date",
    mandatory: true,
    source: "System",
  },
  {
    id: "endDate",
    label: "End Date",
    type: "date",
    mandatory: true,
    source: "System",
  },
  {
    id: "duration",
    label: "Duration/No. of Days",
    type: "number",
    mandatory: true,
    source: "System",
  },
  {
    id: "ratePerUnit",
    label: "Rate per hour/day",
    type: "number",
    mandatory: true,
    source: "System",
    step: 0.01,
  },
  {
    id: "grossAmount",
    label: "Gross Amount",
    type: "number",
    mandatory: true,
    source: "System",
    step: 0.01,
  },
  {
    id: "taxesDeductions",
    label: "Taxes or Deductions",
    type: "number",
    mandatory: false,
    source: "System",
    step: 0.01,
  },
  {
    id: "netPay",
    label: "Net Pay",
    type: "number",
    mandatory: false,
    source: "System",
    step: 0.01,
  },
];

export const OPS_HONORARIUM_FIELDS: FormFieldConfig[] = [
  {
    id: "name",
    label: "Name",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "cid",
    label: "CID",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "workPermit",
    label: "Work Permit",
    type: "text",
    mandatory: false,
    source: "System",
  },
  {
    id: "tpn",
    label: "TPN",
    type: "text",
    mandatory: false,
    source: "System",
  },
  {
    id: "startDate",
    label: "Start Date",
    type: "date",
    mandatory: true,
    source: "System",
  },
  {
    id: "endDate",
    label: "End Date",
    type: "date",
    mandatory: true,
    source: "System",
  },
  {
    id: "duration",
    label: "Duration/No. of Days",
    type: "number",
    mandatory: true,
    source: "System",
  },
  {
    id: "ratePerUnit",
    label: "Rate per hour/day",
    type: "number",
    mandatory: true,
    source: "System",
    step: 0.01,
  },
  {
    id: "grossAmount",
    label: "Gross Amount",
    type: "number",
    mandatory: true,
    source: "System",
    step: 0.01,
  },
  {
    id: "taxesDeductions",
    label: "Taxes or Deductions",
    type: "number",
    mandatory: false,
    source: "System",
    step: 0.01,
  },
  {
    id: "netPay",
    label: "Net Pay",
    type: "number",
    mandatory: false,
    source: "System",
    step: 0.01,
  },
];
