import { FormFieldConfig } from "../../shared/types";

export const OPS_TRAVEL_ADVANCE_LOCAL_FIELDS: FormFieldConfig[] = [
  {
    id: "employeeName",
    label: "Employee Name",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "positionTitle",
    label: "Position Title",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "cid",
    label: "CID",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "agencyName",
    label: "Agency Name",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "opsAgencyList",
  },
  {
    id: "budgetCode",
    label: "Budget Code",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "approvedTARefNo",
    label: "Approved TA Ref No (e-DATS)",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "approvedAmount",
    label: "Approved Amount",
    type: "number",
    mandatory: true,
    source: "System",
    step: 0.01,
  },
  {
    id: "dateOfApproval",
    label: "Date of Approval",
    type: "date",
    mandatory: true,
    source: "System",
  },
  {
    id: "travelPurpose",
    label: "Travel Purpose",
    type: "text",
    mandatory: true,
    source: "System",
  },
];

export const OPS_TRAVEL_ADVANCE_FOREIGN_FIELDS: FormFieldConfig[] = [
  {
    id: "employeeName",
    label: "Employee Name",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "positionTitle",
    label: "Position Title",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "cid",
    label: "CID",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "agencyName",
    label: "Agency Name",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "opsAgencyList",
  },
  {
    id: "budgetCode",
    label: "Budget Code",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "approvedTARefNo",
    label: "Approved TA Ref No (e-DATS)",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "approvedAmount",
    label: "Approved Amount",
    type: "number",
    mandatory: true,
    source: "System",
    step: 0.01,
  },
  {
    id: "dateOfApproval",
    label: "Date of Approval",
    type: "date",
    mandatory: true,
    source: "System",
  },
  {
    id: "travelPurpose",
    label: "Travel Purpose",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "countryOfTravel",
    label: "Country of Travel",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "countryList",
  },
  {
    id: "currency",
    label: "Currency",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "currencyList",
  },
];
