import { FormFieldConfig } from "../../shared/types";

export const CS_SALARY_ADVANCE_FIELDS: FormFieldConfig[] = [
  {
    id: "employeeName",
    label: "Employee Name",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "positionTitle",
    label: "Position Title",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "cid",
    label: "CID",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "basicPay",
    label: "Basic Pay",
    type: "number",
    mandatory: true,
    source: "System",
    step: 0.01,
  },
  {
    id: "grossPay",
    label: "Gross Pay",
    type: "number",
    mandatory: true,
    source: "System",
    step: 0.01,
  },
  {
    id: "advanceRequested",
    label: "Advance Requested",
    type: "number",
    mandatory: true,
    source: "System",
    step: 0.01,
  },
  {
    id: "payrollDepartment",
    label: "Payroll Department Name",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "agencyName",
    label: "Agency Name",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "agencyList",
  },
  {
    id: "budgetCode",
    label: "Budget Code",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "deductionMethod",
    label: "Deduction Method",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "deductionMethods",
  },
];

export const CS_FLOATING_DEDUCTIONS_FIELDS: FormFieldConfig[] = [
  {
    id: "employeeName",
    label: "Employee Name",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "positionTitle",
    label: "Position Title",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "cid",
    label: "CID",
    type: "text",
    mandatory: true,
    source: "System",
  },
  {
    id: "basicPay",
    label: "Basic Pay",
    type: "number",
    mandatory: true,
    source: "System",
    step: 0.01,
  },
  {
    id: "grossPay",
    label: "Gross Pay",
    type: "number",
    mandatory: true,
    source: "System",
    step: 0.01,
  },
  {
    id: "floatingDeductionName",
    label: "Name of Floating Deductions",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "csFloatingDeductions",
  },
  {
    id: "deductionMethod",
    label: "Deduction Method",
    type: "dropdown",
    mandatory: true,
    source: "System",
    lovKey: "floatingDeductionMethods",
  },
];
