/* Simulated contractor data for amendment preview */
import type { ContractorKind } from "../../../../../shared/types";
import type { FormState } from "../../stages/sharedTypes";

export function getSimulatedContractorData(kind: ContractorKind): FormState {
  if (kind === "individual") {
    return {
      contractorId: "CONT-IND-2024-00892",
      contractorType: "Individual Contractor",
      contractualType: "",
      category: "Individual",
      nationality: "Bhutanese",
      entryMethod: "Manual Entry",
      dataSource: "BCRS",
      registrationDate: "2024-03-15 10:30:00",
      contractorStatusPrimary: "Active",
      contractorStatusSecondary: "-- Select --",
      statusReason: "",
      isPrimaryContractor: "No",
      salutation: "Mrs.",
      displayName: "Dechen Wangmo",
      firstName: "Dechen",
      middleName: "",
      lastName: "Wangmo",
      gender: "Female",
      dateOfBirth: "1992-08-14",
      businessRegistrationDate: "",
      countryOfRegistration: "Bhutan",
      secondaryName: "",
      registrationNumber: "11501001234",
      licenseNumber: "",
      gstNumber: "",
      taxNumber: "TPN-BT-54321",
      email: "dechen.wangmo@example.bt",
      phone: "+975-17-123456",
      secondaryPhone: "+975-17-654321",
      faxNumber: "",
      address: "Thimphu",
      addressLine2: "Ward 3",
      addressLine3: "",
      gewog: "Thimphu Gewog",
      dungkhag: "Thimphu Dungkhag",
      thromde: "Thimphu Thromde",
      district: "Thimphu",
      cityTown: "",
      stateProvince: "",
      region: "",
      postalCode: "",
      bankName: "Bank of Bhutan",
      bankBranchCode: "THI001",
      bankBranchName: "Thimphu Main Branch",
      accountType: "Savings",
      currencyType: "BTN",
      accountStatus: "Active",
      accountCategory: "",
      ifscCode: "",
      swiftCode: "",
      bankAccountNumber: "00001234567890",
      bankAccountName: "Dechen Wangmo",
      contactPerson: "Dechen Wangmo",
      contactRole: "Owner",
      sanctionsCheck: "Clear",
      sanctionCategory: "Temporary Suspension",
      sanctionType: "",
      sanctionStartDate: "",
      sanctionEndDate: "",
      autoReactivation: "Yes",
      sanctionReason: "",
      affectedAgency: "",
      sanctioningAgency: "",
      supportingDocuments: "",
      sanctionStatus: "Active",
      remarks: "",
      workflowNote: "Yes",
    };
  }

  return {
    contractorId: "CONT-BUS-2024-00234",
    contractorType: "Contractor",
    contractualType: "Works Contractor",
    category: "Business",
    nationality: "Bhutanese",
    entryMethod: "Manual Entry",
    dataSource: "IBLS",
    registrationDate: "2024-02-20 14:15:00",
    contractorStatusPrimary: "Active",
    contractorStatusSecondary: "-- Select --",
    statusReason: "",
    isPrimaryContractor: "Yes",
    salutation: "",
    displayName: "Druk Green Power Corporation Ltd.",
    firstName: "",
    middleName: "",
    lastName: "",
    gender: "",
    dateOfBirth: "",
    businessRegistrationDate: "2019-04-10",
    countryOfRegistration: "Bhutan",
    secondaryName: "DGPC Ltd.",
    registrationNumber: "BRN-BT-2019-04567",
    licenseNumber: "LIC-2019-04567",
    gstNumber: "GST-BT-98765",
    taxNumber: "TPN-BT-98765",
    email: "info@drukgreen.bt",
    phone: "+975-2-322-8000",
    secondaryPhone: "+975-2-322-8001",
    faxNumber: "+975-2-322-8099",
    address: "Thimphu",
    addressLine2: "Chang Bhang",
    addressLine3: "",
    gewog: "Thimphu Gewog",
    dungkhag: "Thimphu Dungkhag",
    thromde: "Thimphu Thromde",
    district: "Thimphu",
    cityTown: "",
    stateProvince: "",
    region: "",
    postalCode: "",
    bankName: "Bank of Bhutan",
    bankBranchCode: "THI001",
    bankBranchName: "Thimphu Main Branch",
    accountType: "Current",
    currencyType: "BTN",
    accountStatus: "Active",
    accountCategory: "",
    ifscCode: "",
    swiftCode: "",
    bankAccountNumber: "00009876543210",
    bankAccountName: "Druk Green Power Corporation Ltd.",
    contactPerson: "Tenzin Dorji",
    contactRole: "Director",
    sanctionsCheck: "Clear",
    sanctionCategory: "Temporary Suspension",
    sanctionType: "",
    sanctionStartDate: "",
    sanctionEndDate: "",
    autoReactivation: "Yes",
    sanctionReason: "",
    affectedAgency: "",
    sanctioningAgency: "",
    supportingDocuments: "",
    sanctionStatus: "Active",
    remarks: "",
    workflowNote: "Yes",
  };
}
