export const CS_LOV_DEFINITIONS: Record<string, string[]> = {
  csEmployeeCategories: ["Civil Servants"],
  csEmployeeTypes: [
    "Regular",
    "Contract",
    "Consolidated-Contract",
    "Contract: GSP / ESP",
    "Para-Regular",
  ],
  csPositionLevels: [
    "EX",
    "EX1",
    "EX2",
    "EX3",
    "ES1",
    "ES2",
    "ES3",
    "P1",
    "P2",
    "P3",
    "P4",
    "P5",
    "S1",
    "S2",
    "S3",
    "S4",
    "S5",
    "O1",
    "O2",
    "O3",
    "O4",
    "O5",
    "GSP",
    "ESP",
  ],
  csFixedPayAllowances: ["Basic Salary", "LE Allowance"],
  csVariablePayAllowances: [
    "LTC Allowance",
    "Professional Allowance",
    "Patang Allowance",
    "Uniform Allowance",
    "Foreign Allowance",
    "Child Education Allowance",
    "Night Duty Allowance",
    "Overtime Allowance",
    "Pay Arrears",
    "Radiation Allowance",
    "Contract Allowance",
    "Difficulty Area Allowance",
    "High Altitude Allowance",
    "Personal Pay",
    "Scarcity Allowance",
    "Soilra",
    "Bonus",
    "Teaching Allowance",
    "Communication Allowance",
    "Royal Audit Allowance",
    "ACC Allowance-Investigation",
    "ACC Allowance-Others",
    "City Allowance",
    "Prosecutor Allowance",
    "Officiating Allowance",
    "Red Scarf Allowance",
    "Other Allowances",
    "Discretionary Allowance",
    "Compensatory Allowance",
    "Leave Encashment (MVC)",
    "Lump Sum Revision",
    "One-off 5% Indexation",
    "One-Off Fixed Payment",
  ],
  csStatutoryDeductions: [
    "Provident Fund (PF)",
    "Group Insurance Scheme (GIS)",
    "Health Contribution (HC)",
    "Tax Deducted at Source (Tax on Salary)",
    "House Rent DRC",
    "House Rent NHDCL",
  ],
  csOtherDeductions: [
    "House Rent",
    "Advance Salary Recovery",
    "PWA Employees Advance Recovery",
    "Training Bond Recovery",
    "Penalties or Fines",
    "Civil Servants Welfare Scheme (CSWS) RCSC",
    "Audit Recovery",
    "Employees Loss and Investigations Recoveries",
  ],
  csFloatingDeductions: [
    "House Rent",
    "Advance Salary Recovery",
    "PWA Employees Advance Recovery",
    "Training Bond Recovery",
    "Penalties or Fines",
    "Civil Servants Welfare Scheme (CSWS)",
    "Audit Recovery",
    "Employees Loss and Investigations",
  ],
};
