export const OPS_LOV_DEFINITIONS: Record<string, string[]> = {
  opsEmployeeCategories: [
    "Constitutional Bodies",
    "Foreign Services",
    "Foreign Services (Local Recruit)",
    "Judiciary",
    "Local Government",
    "Parliament (Members of NA/NC)",
    "Religious Services",
    "Other Public Servants: RUB",
    "Royal Bhutan Police",
    "Royal Bhutan Police (Civil)",
    "Local Recruits",
  ],
  opsEmployeeTypes: [
    "Regular",
    "Contract",
    "Consolidated-Contract",
    "Parliamentary",
  ],
  opsPositionLevels: [
    "EX",
    "EX1",
    "EX2",
    "EX3",
    "ES1",
    "ES2",
    "ES3",
    "P1",
    "P2",
    "P3",
    "P4",
    "P5",
    "S1",
    "S2",
    "S3",
    "S4",
    "S5",
    "O1",
    "O2",
    "O3",
    "O4",
    "O5",
  ],
  opsFixedPayAllowances: ["Basic Salary", "LE Allowance"],
  opsVariablePayAllowances: [
    "LTC Allowance",
    "Professional Allowance",
    "Patang Allowance",
    "Uniform Allowance",
    "Foreign Allowance",
    "Child Education Allowance",
    "Night Duty Allowance",
    "Overtime Allowance",
    "Armed Force Special Allowance",
    "Kit Maintenance Allowance",
    "Dog Handling Allowance",
    "Chief Title Allowance",
    "Hospitality Allowance",
    "DCHU Allowance",
    "Orderly Allowance",
    "Soelra on Promotion",
    "Technical and Trade Allowance",
    "Medal Allowance",
    "Higher Post Benefits",
    "Guard Mounting Allowance",
    "Plain Cloth Allowance",
    "Wireless Operator Allowance",
    "Driver Allowance",
    "Fuel and Maintenance Allowance",
    "Special Responsibility Allowance",
    "Border Hardship Allowance",
    "Occupational Hazard Allowance",
    "Prison Duty Allowance",
    "Vegetable Allowance",
    "Druk Yulgyel",
    "Drakpoi Wangyel",
    "Drakpoi Thugsay",
    "Drakpoi Khorlo",
    "Allowance for ADC/PSOs",
    "Liaison & Media Allowances",
    "LLB/LLM Allowance",
    "Other Allowances",
  ],
  opsStatutoryDeductions: [
    "Provident Fund (PF)",
    "Group Insurance Scheme (GIS)",
    "Health Contribution (HC)",
    "Tax Deducted at Source (Tax on Salary)",
  ],
  opsOtherDeductions: [
    "Armed Force Welfare Scheme (AFWS)",
    "RBP Ration",
    "Absentees Deductions",
  ],
  opsFloatingDeductions: [
    "House Rent",
    "Advance Salary Recovery",
    "Training Bond Recovery",
    "Penalties or Fines",
    "Armed Force Welfare Scheme (AFWS)",
    "RBP Ration",
    "Audit Recovery",
  ],
  employeeStatuses: ["Active", "Suspended", "Long-term Leave", "Separated"],
};
